// Generated by ChatGPT and Riko Balakit/Pearl Grey

#if UNITY_EDITOR

using System;
using Runtime.Tooling;
using UnityEditor;
using UnityEngine;

namespace Editor.Tooling
{
    [CustomEditor(typeof(TaskVisualizer))]
    public class TaskVisualizerEditor : UnityEditor.Editor
    {
        private double _nextRepaintTimeEditorSeconds;

        public override void OnInspectorGUI()
        {
            var taskVisualizer = (TaskVisualizer)target;

            DrawDefaultInspector();

            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Task State Visualization", EditorStyles.boldLabel);

            if (GUILayout.Button("Refresh"))
            {
                Repaint();
            }

            if (taskVisualizer.AutoRefresh)
            {
                var now = EditorApplication.timeSinceStartup;

                if (now >= _nextRepaintTimeEditorSeconds)
                {
                    _nextRepaintTimeEditorSeconds =
                        now + Math.Max(0.1f, taskVisualizer.AutoRefreshIntervalSeconds);

                    Repaint();
                }
            }

            EditorGUILayout.Space();

            var taskState = taskVisualizer.GetTaskState();

            if (taskState == null)
            {
                EditorGUILayout.HelpBox("TaskState not available.", MessageType.Warning);
                return;
            }

            var tasks = taskState.Tasks;

            if (tasks == null || tasks.Count == 0)
            {
                EditorGUILayout.HelpBox("No tasks in TaskState.", MessageType.Info);
                return;
            }

            for (var i = 0; i < tasks.Count; i++)
            {
                var task = tasks[i];

                if (task == null)
                {
                    continue;
                }

                if (!taskVisualizer.ShowDoneTasks && task.status == TaskStatus.DONE)
                {
                    continue;
                }

                if (!taskVisualizer.ShowCancelledTasks && task.status == TaskStatus.CANCELLED)
                {
                    continue;
                }

                DrawTaskCard(task);
            }
        }

        private static void DrawTaskCard(TaskData task)
        {
            EditorGUILayout.BeginVertical(EditorStyles.helpBox);

            EditorGUILayout.LabelField(
                "[" + task.taskId.ToString("D4") + "] " + Safe(task.name),
                EditorStyles.boldLabel);

            EditorGUILayout.LabelField("Category", task.category.ToString());
            EditorGUILayout.LabelField("Priority", task.priority.ToString());
            EditorGUILayout.LabelField("Urgency", task.urgency.ToString());
            EditorGUILayout.LabelField("Status", task.status.ToString());
            EditorGUILayout.LabelField("Added", task.datetimeAdded.ToString("yyyy-MM-dd HH:mm:ss"));

            if (!string.IsNullOrWhiteSpace(task.notes))
            {
                EditorGUILayout.Space();
                EditorGUILayout.LabelField("Notes");
                EditorGUILayout.HelpBox(task.notes, MessageType.None);
            }

            EditorGUILayout.EndVertical();
            EditorGUILayout.Space();
        }

        private static string Safe(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return "(Unnamed Task)";
            }

            return value;
        }
    }
}

#endif

// Generated by ChatGPT and Riko Balakit/Pearl Grey