// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System.Threading.Tasks;
using NaughtyAttributes;
using TMPro;
using UnityEngine;
using Runtime.Reasoning;

namespace Runtime.Avatar
{
    public class SpeakAndEmoteController : PearlBehaviour
    {
        [Header("Stuff she says")]
        [TextArea(6, 20)]
        [SerializeField] private string _thingToSpeak;

        [Header("Client")]
        [SerializeField] private bool _isWaiting;

        [Header("Reply")]
        [ReadOnly]
        [SerializeField] private QueryHandler.AssistantEmotionResponse _emotion = QueryHandler.AssistantEmotionResponse.Neutral;

        [SerializeField] private TMP_Text _dialogText;

        public void Start()
        {
            SetInitialized();
        }

        public void SendPhraseAndEmotion(
            string thingToSpeak,
            QueryHandler.AssistantEmotionResponse emotion,
            bool promptAfterwards = false)
        {
            _thingToSpeak = thingToSpeak;
            _emotion = emotion;
            SendRoutine(promptAfterwards);
        }

        [Button("Send And Wait For Answer")]
        private void SendRoutine(bool promptAfterwards = false)
        {
            if (_isWaiting)
            {
                LogWarning("Already waiting for response.");
                return;
            }

            _ = SpeakRoutine(promptAfterwards);
        }

        // ReSharper disable Unity.PerformanceAnalysis
        private async Task SpeakRoutine(bool promptAfterwards = false)
        {
            _isWaiting = true;
            MarkDirty();

            try
            {
                ApplyEmotion(_emotion);

                _dialogText.text = _thingToSpeak;
                GlobalManager.I.TtsPlayer.GenerateAndPlay(_thingToSpeak);

                if (promptAfterwards)
                {
                    while (GlobalManager.I.TtsPlayer.IsSpeaking)
                    {
                        await Task.Yield();
                    }

                    await Task.Delay((int)(GlobalManager.I.Configuration.DelayToPromptSttSeconds * 1000));
                    GlobalManager.I.WakeWordSidecarClient.OnWakeWordTriggered();
                }
            }
            catch (System.Exception exception)
            {
                LogError("[SpeakAndEmoteController] Error while speaking: " + exception);
            }

            _isWaiting = false;
            MarkDirty();
        }

        private void ApplyEmotion(QueryHandler.AssistantEmotionResponse emotion)
        {
            switch (emotion)
            {
                case QueryHandler.AssistantEmotionResponse.Neutral:
                    GlobalManager.I.AvatarController.SetEmotionNeutral();
                    break;
                case QueryHandler.AssistantEmotionResponse.Pissed:
                    GlobalManager.I.AvatarController.SetEmotionPissed();
                    break;
                case QueryHandler.AssistantEmotionResponse.MildlyHappy:
                    GlobalManager.I.AvatarController.SetEmotionGlad();
                    break;
                case QueryHandler.AssistantEmotionResponse.Ecstatic:
                    GlobalManager.I.AvatarController.SetEmotionEcstatic();
                    break;
                case QueryHandler.AssistantEmotionResponse.Annoyed:
                    GlobalManager.I.AvatarController.SetEmotionAnnoyed();
                    break;
                case QueryHandler.AssistantEmotionResponse.Surprised:
                    GlobalManager.I.AvatarController.SetEmotionSurprised();
                    break;
                default:
                    GlobalManager.I.AvatarController.SetEmotionNeutral();
                    break;
            }
        }

#if UNITY_EDITOR
        private void MarkDirty()
        {
            UnityEditor.EditorUtility.SetDirty(this);
        }
#else
        private void MarkDirty() {}
#endif
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey