// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using NaughtyAttributes;
using Runtime.Inputs.Presence;
using Runtime.Reasoning.DataTypes;
using TMPro;
using UnityEngine;

namespace Runtime.Behaviour
{
    public class ProactiveAgencyController : PearlBehaviour
    {
        [SerializeField]
        private bool _testTimeEnabled = false;

        [Header("Debug UI")]
        [SerializeField]
        private TMP_Text _promptCooldownRemainingText;

        [SerializeField]
        private TMP_Text _awayAssumptionRemainingText;

        private DateTime _lastTimeUserWasPrompted = DateTime.MinValue;
        private DateTime _lastTimePresenceStateChangedUtc = DateTime.UtcNow;
        private PresenceState _lastKnownPresenceState = PresenceState.Unknown;

        private bool _shouldAskIfThisIsANewDayAfterLongAbsence = false;

        public void Initialize()
        {
            _lastKnownPresenceState = GlobalManager.I.State.PresenceState;
            _lastTimePresenceStateChangedUtc = DateTime.UtcNow;
            SetInitialized();
        }

        public void Update()
        {
            if (!IsInitialized)
            {
                return;
            }

            UpdatePresenceTracking();
            UpdateDebugTexts();

            if (GlobalManager.I.State.PresenceState == PresenceState.Absent)
            {
                return;
            }

            if (GlobalManager.I.State.QuietModeEnabled)
            {
                return;
            }

            var userPromptCooldownMinutes = GlobalManager.I.Configuration.GetCurrentModePromptConfiguration().ProactiveLoopbackTimeMinutes;
            var userWentAsleepAssumptionMinutes = GlobalManager.I.Configuration.MinutesToAssumeUserWentToSleep;

            if (_testTimeEnabled)
            {
                userPromptCooldownMinutes *= 0.2f;
                userWentAsleepAssumptionMinutes *= 0.2f;
            }

            if (userPromptCooldownMinutes < 0f)
            {
                return;
            }

            var hasExceededUserInteractionCooldown =
                GlobalManager.I.State.MinutesSinceLastUserInteraction > userPromptCooldownMinutes;

            var hasExceededPromptRepeatCooldown =
                DateTime.UtcNow - _lastTimeUserWasPrompted > TimeSpan.FromMinutes(userPromptCooldownMinutes);

            if (hasExceededUserInteractionCooldown && hasExceededPromptRepeatCooldown)
            {
                AskProactiveQuestion();
            }
        }

        private void UpdatePresenceTracking()
        {
            var currentPresenceState = GlobalManager.I.State.PresenceState;

            if (currentPresenceState != _lastKnownPresenceState)
            {
                var previousPresenceState = _lastKnownPresenceState;
                var nowUtc = DateTime.UtcNow;

                if (previousPresenceState == PresenceState.Absent && currentPresenceState != PresenceState.Absent)
                {
                    var userWentAsleepAssumptionMinutes = GlobalManager.I.Configuration.MinutesToAssumeUserWentToSleep;

                    if (_testTimeEnabled)
                    {
                        userWentAsleepAssumptionMinutes *= 0.2f;
                    }

                    var absenceDuration = nowUtc - _lastTimePresenceStateChangedUtc;

                    if (absenceDuration >= TimeSpan.FromMinutes(userWentAsleepAssumptionMinutes))
                    {
                        _shouldAskIfThisIsANewDayAfterLongAbsence = true;
                    }
                }

                _lastKnownPresenceState = currentPresenceState;
                _lastTimePresenceStateChangedUtc = nowUtc;
            }
        }

        private void UpdateDebugTexts()
        {
            var userPromptCooldownMinutes = GlobalManager.I.Configuration.GetCurrentModePromptConfiguration().ProactiveLoopbackTimeMinutes;
            var userWentAsleepAssumptionMinutes = GlobalManager.I.Configuration.MinutesToAssumeUserWentToSleep;

            if (_testTimeEnabled)
            {
                userPromptCooldownMinutes *= 0.2f;
                userWentAsleepAssumptionMinutes *= 0.2f;
            }

            if (_promptCooldownRemainingText != null)
            {
                if (userPromptCooldownMinutes < 0f)
                {
                    _promptCooldownRemainingText.text = "Prompt Cooldown: Disabled";
                }
                else
                {
                    var remainingPromptCooldown = TimeSpan.FromMinutes(userPromptCooldownMinutes) - TimeSpan.FromMinutes(GlobalManager.I.State.MinutesSinceLastUserInteraction);

                    if (DateTime.UtcNow - _lastTimeUserWasPrompted < TimeSpan.FromMinutes(userPromptCooldownMinutes))
                    {
                        var repeatPromptRemaining = TimeSpan.FromMinutes(userPromptCooldownMinutes) - (DateTime.UtcNow - _lastTimeUserWasPrompted);

                        if (repeatPromptRemaining > remainingPromptCooldown)
                        {
                            remainingPromptCooldown = repeatPromptRemaining;
                        }
                    }

                    if (remainingPromptCooldown < TimeSpan.Zero)
                    {
                        remainingPromptCooldown = TimeSpan.Zero;
                    }

                    _promptCooldownRemainingText.text = "Prompt Cooldown: " + FormatTimeSpanMinutesSeconds(remainingPromptCooldown);
                }
            }

            if (_awayAssumptionRemainingText != null)
            {
                if (GlobalManager.I.State.PresenceState == PresenceState.Absent)
                {
                    var absentDuration = DateTime.UtcNow - _lastTimePresenceStateChangedUtc;
                    var remainingAwayAssumption = TimeSpan.FromMinutes(userWentAsleepAssumptionMinutes) - absentDuration;

                    if (remainingAwayAssumption < TimeSpan.Zero)
                    {
                        remainingAwayAssumption = TimeSpan.Zero;
                    }

                    _awayAssumptionRemainingText.text = "Away/Sleep Assumption: " + FormatTimeSpanMinutesSeconds(remainingAwayAssumption);
                }
                else
                {
                    _awayAssumptionRemainingText.text = "Away/Sleep Assumption: " + FormatTimeSpanMinutesSeconds(TimeSpan.FromMinutes(userWentAsleepAssumptionMinutes));
                }
            }
        }

        [Button]
        public void SimpleAskUserForTaskUpdates()
        {
            AskProactiveQuestion();
        }

        private void AskProactiveQuestion()
        {
            if (_shouldAskIfThisIsANewDayAfterLongAbsence)
            {
                GlobalManager.I.QueryHandler.HandleNewMessage(
                    "I want to ask the user whether this is basically a new day for productivity and whether they want to start a new to-do list or continue the old one. Keep the message concise and to the point.",
                    QuerySource.AssistantSelf);

                _shouldAskIfThisIsANewDayAfterLongAbsence = false;
            }
            else
            {
                GlobalManager.I.QueryHandler.HandleNewMessage(
                    "I want to ask the user about updates on their to-do list. If there are no tasks left, ask if there are new tasks or if we should switch to a different mode or be finished with productivity for the day. Keep the message concise and to the point.",
                    QuerySource.AssistantSelf);
            }

            _lastTimeUserWasPrompted = DateTime.UtcNow;
        }

        private string FormatTimeSpanMinutesSeconds(TimeSpan timeSpan)
        {
            if (timeSpan < TimeSpan.Zero)
            {
                timeSpan = TimeSpan.Zero;
            }

            return $"{(int)timeSpan.TotalMinutes:00}:{timeSpan.Seconds:00}";
        }
    }
}