// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Networking;
namespace Runtime.Inputs.Presence
{
    public class CvPresenceTracker : MonoBehaviour
    {
        [Serializable]
        private class PresenceStatusResponse
        {
            public string presence;
        }


        [Header("Debug")]
        [SerializeField] private bool _logStateChanges = true;
        [SerializeField] private bool _logRequestFailures = false;

        [Header("Runtime")]
        [SerializeField] private PresenceState _currentPresenceState = PresenceState.Unknown;
        [SerializeField] private PresenceState _previousPresenceState = PresenceState.Unknown;
        [SerializeField] private string _lastRawResponse;
        [SerializeField] private string _lastError;
        [SerializeField] private string _lastSuccessfulPollUtc;
        [SerializeField] private string _lastStateChangeUtc;

        private Coroutine _pollCoroutine;

        public PresenceState CurrentPresenceState => _currentPresenceState;
        public PresenceState PreviousPresenceState => _previousPresenceState;
        public string LastRawResponse => _lastRawResponse;
        public string LastError => _lastError;
        public string LastSuccessfulPollUtc => _lastSuccessfulPollUtc;
        public string LastStateChangeUtc => _lastStateChangeUtc;

        public event Action<PresenceState, PresenceState> PresenceStateChanged;

        public void Initialize()
        {
            StartPolling();
        }

        private void OnDestroy()
        {
            StopPolling();
        }

        [ContextMenu("Start Polling")]
        public void StartPolling()
        {
            if (_pollCoroutine != null)
            {
                return;
            }

            _pollCoroutine = StartCoroutine(PollPresenceCoroutine());
        }

        [ContextMenu("Stop Polling")]
        public void StopPolling()
        {
            if (_pollCoroutine == null)
            {
                return;
            }

            StopCoroutine(_pollCoroutine);
            _pollCoroutine = null;
        }

        [ContextMenu("Poll Once")]
        public void PollOnce()
        {
            StartCoroutine(PollPresenceOnceCoroutine());
        }

        private IEnumerator PollPresenceCoroutine()
        {
            while (true)
            {
                yield return PollPresenceOnceCoroutine();
                yield return new WaitForSeconds(GlobalManager.I.Configuration.CVPollIntervalSeconds);
            }
        }

        private IEnumerator PollPresenceOnceCoroutine()
        {
            using (var webRequest = UnityWebRequest.Get(GlobalManager.I.Configuration.CVStatusUrl))
            {
                webRequest.timeout = Mathf.Max(1, Mathf.CeilToInt(GlobalManager.I.Configuration.CVPollRequestTimeoutSeconds));

                yield return webRequest.SendWebRequest();

                if (webRequest.result != UnityWebRequest.Result.Success)
                {
                    _lastError = webRequest.error;
                    _lastRawResponse = string.Empty;

                    if (_logRequestFailures)
                    {
                        Debug.LogWarning($"[CvPresenceTracker] Failed to reach CV sidecar. Error: {_lastError}");
                    }

                    SetPresenceState(PresenceState.Unknown);
                    yield break;
                }

                _lastError = string.Empty;
                _lastRawResponse = webRequest.downloadHandler.text;
                _lastSuccessfulPollUtc = DateTime.UtcNow.ToString("o");

                PresenceStatusResponse presenceStatusResponse = null;

                try
                {
                    presenceStatusResponse = JsonConvert.DeserializeObject<PresenceStatusResponse>(_lastRawResponse);
                }
                catch (Exception exception)
                {
                    _lastError = exception.Message;

                    if (_logRequestFailures)
                    {
                        Debug.LogWarning($"[CvPresenceTracker] Failed to parse CV sidecar JSON. Error: {_lastError}");
                    }

                    SetPresenceState(PresenceState.Unknown);
                    yield break;
                }

                if (presenceStatusResponse == null || string.IsNullOrWhiteSpace(presenceStatusResponse.presence))
                {
                    _lastError = "Response JSON did not include a valid presenceState field.";

                    if (_logRequestFailures)
                    {
                        Debug.LogWarning("[CvPresenceTracker] Response JSON missing presenceState.");
                    }

                    SetPresenceState(PresenceState.Unknown);
                    yield break;
                }

                var parsedPresenceState = ParsePresenceState(presenceStatusResponse.presence);
                SetPresenceState(parsedPresenceState);
            }
        }

        private PresenceState ParsePresenceState(string presenceStateString)
        {
            if (string.IsNullOrWhiteSpace(presenceStateString))
            {
                return PresenceState.Unknown;
            }

            if (presenceStateString.ToLower() == "true")
            {
                return PresenceState.Present;
            }
            else if (presenceStateString.ToLower() == "false")
            {
                return PresenceState.Absent;
            }
            
            return PresenceState.Unknown;
        }

        private void SetPresenceState(PresenceState newPresenceState)
        {
            if (_currentPresenceState == newPresenceState)
            {
                return;
            }

            _previousPresenceState = _currentPresenceState;
            _currentPresenceState = newPresenceState;
            _lastStateChangeUtc = DateTime.UtcNow.ToString("o");

            if (_logStateChanges)
            {
                Debug.Log($"[CvPresenceTracker] Presence state changed: {_previousPresenceState} -> {_currentPresenceState}");
                GlobalManager.I.State.PresenceState = _currentPresenceState;
            }

            PresenceStateChanged?.Invoke(_previousPresenceState, _currentPresenceState);
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey