// Generated by ChatGPT and Riko Balakit/Pearl Grey

using UnityEngine;
namespace Runtime.UI
{
    public class SinusoidalScaleAnimator : MonoBehaviour
    {
        [Header("Scale Bounds")]
        [SerializeField]
        private Vector3 _lowScale = Vector3.one;

        [SerializeField]
        private Vector3 _highScale = Vector3.one * 1.2f;

        [Header("Timing")]
        [SerializeField]
        private float _periodSeconds = 2f;

        [Header("Optional")]
        [SerializeField]
        private bool _useUnscaledTime = false;

        private float _elapsedSeconds;

        private void Update()
        {
            if (_periodSeconds <= 0f)
            {
                return;
            }

            var deltaSeconds = _useUnscaledTime ? Time.unscaledDeltaTime : Time.deltaTime;
            _elapsedSeconds += deltaSeconds;

            var phase = (_elapsedSeconds / _periodSeconds) * Mathf.PI * 2f;

            // Convert sin range (-1..1) → (0..1)
            var normalized = (Mathf.Sin(phase) + 1f) * 0.5f;

            transform.localScale = Vector3.Lerp(_lowScale, _highScale, normalized);
        }
    }
}