// Generated by ChatGPT and Riko Balakit/Pearl Grey

using Runtime.Tooling;
using UnityEngine;

namespace Runtime.Tooling
{
    public class TaskVisualizer : MonoBehaviour
    {
        [SerializeField]
        private bool _autoRefresh = true;

        [SerializeField]
        private float _autoRefreshIntervalSeconds = 1.0f;

        [SerializeField]
        private bool _showDoneTasks = true;

        [SerializeField]
        private bool _showCancelledTasks = true;

        public bool AutoRefresh => _autoRefresh;
        public float AutoRefreshIntervalSeconds => _autoRefreshIntervalSeconds;
        public bool ShowDoneTasks => _showDoneTasks;
        public bool ShowCancelledTasks => _showCancelledTasks;

        public TaskState GetTaskState()
        {
            if (GlobalManager.I == null)
            {
                return null;
            }

            return GlobalManager.I.TaskState;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey