// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Diagnostics;
using System.IO;
using UnityEngine;

namespace Runtime.Tooling
{
    public class LogSendTool : BaseTool
    {
        protected override void InitializeInternal()
        {
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            var unityConsoleLogPath = Application.consoleLogPath;

            if (string.IsNullOrWhiteSpace(unityConsoleLogPath))
            {
                executionSummary = "Unity did not provide a console log path on this platform.";
                return false;
            }

            if (!File.Exists(unityConsoleLogPath))
            {
                executionSummary = "Unity log file was not found at path: " + unityConsoleLogPath;
                return false;
            }

            try
            {
                var processStartInfo = new ProcessStartInfo
                {
                    FileName = unityConsoleLogPath,
                    UseShellExecute = true
                };

                Process.Start(processStartInfo);

                executionSummary = "Opened Unity log file: " + unityConsoleLogPath;
                Log(executionSummary);
                return true;
            }
            catch (Exception exception)
            {
                executionSummary = "Failed to open Unity log file. Exception: " + exception.Message;
                LogError(executionSummary);
                return false;
            }
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey