// Generated by ChatGPT and Riko Balakit/Pearl Grey
// Updated for OpenClaw WebSocket Gateway Protocol

using System;
using System.Collections;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;

namespace Runtime.Tooling
{
    public class OpenClawTool : BaseTool
    {
        private const float CONNECTION_CHECK_INTERVAL_SECONDS = 10f;
        private const float ERROR_BOX_DURATION_SECONDS = 10f;
        private const int REQUEST_TIMEOUT_SECONDS = 3;

        [Header("Connection UI")]
        [SerializeField]
        private GameObject _openClawErrorBox;

        [Header("Connection Config")]
        [SerializeField]
        private string _openClawGatewayUrl = "ws://localhost:18789";

        [SerializeField]
        private string _openClawChannel = "webchat";

        [SerializeField]
        private string _openClawSessionKey = "agent:main:main";

        private bool _isConnected;
        private bool _wsConnected;
        private ClientWebSocket _webSocket;
        private CancellationTokenSource _cts;
        private Coroutine _connectionCheckCoroutine;
        private Coroutine _errorDisplayCoroutine;

        public bool IsConnected => _isConnected;

        [Serializable]
        private class OpenClawToolPayload
        {
            public string request;
        }

        // WebSocket protocol message structures
        [Serializable]
        private class ConnectRequest
        {
            public string type = "req";
            public string id;
            public string method = "connect";
            public ConnectParams @params = new ConnectParams();
        }

        [Serializable]
        private class ConnectParams
        {
            public int minProtocol = 3;
            public int maxProtocol = 3;
            public ClientInfo client = new ClientInfo();
            public string role = "operator";
            public string[] scopes = new[] { "operator.read", "operator.write" };
            public string[] caps = new string[0];
            public string[] commands = new string[0];
            public string locale = "en-US";
            public string userAgent = "unity-openclaw-client/1.0";
            public AuthInfo auth = new AuthInfo();  // ADD THIS
        }

        
        [Serializable]
        private class AuthInfo
        {
            public string token = Secrets.OpenClawAuthToken;  // Placeholder for authentication token
        }
        
        [Serializable]
        private class ClientInfo
        {
            public string id = "unity-client";
            public string version = "1.0.0";
            public string platform = "windows";
            public string mode = "operator";
        }

        [Serializable]
        private class ChatSendRequest
        {
            public string type = "req";
            public string id;
            public string method = "chat.send";
            public ChatSendParams @params = new ChatSendParams();
        }

        [Serializable]
        private class ChatSendParams
        {
            public string channel;
            public string message;
            public string sessionKey;
        }

        [Serializable]
        private class WebSocketResponse
        {
            public string type;
            public string id;
            public bool ok;
            public Payload payload;
            public Error error;
        }

        [Serializable]
        private class Payload
        {
            public string type;
        }

        [Serializable]
        private class Error
        {
            public string message;
            public int code;
        }

        public override void Initialize()
        {
            if (_connectionCheckCoroutine != null)
            {
                StopCoroutine(_connectionCheckCoroutine);
            }

            if (_errorDisplayCoroutine != null)
            {
                StopCoroutine(_errorDisplayCoroutine);
                _errorDisplayCoroutine = null;
            }

            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(false);
            }

            SetConnectionState(false);

            _cts = new CancellationTokenSource();
            _ = ConnectWebSocketAsync();

            _connectionCheckCoroutine = StartCoroutine(ConnectionCheckCoroutine());

            SetInitialized();
        }

        private async Task ConnectWebSocketAsync()
        {
            try
            {
                _webSocket = new ClientWebSocket();
                await _webSocket.ConnectAsync(new Uri(_openClawGatewayUrl), _cts.Token);
                _wsConnected = true;

                // Send connect handshake
                var connectReq = new ConnectRequest
                {
                    id = Guid.NewGuid().ToString()
                };
                var connectJson = JsonUtility.ToJson(connectReq);
                await SendWebSocketMessageAsync(connectJson);

                // Start receive loop
                _ = ReceiveLoopAsync();

                SetConnectionState(true);
                Log("OpenClaw WebSocket connected");
            }
            catch (Exception ex)
            {
                LogError("OpenClaw WebSocket connection failed: " + ex.Message);
                SetConnectionState(false);
            }
        }

        private async Task ReceiveLoopAsync()
        {
            var buffer = new byte[4096];

            while (_webSocket.State == WebSocketState.Open && !_cts.Token.IsCancellationRequested)
            {
                try
                {
                    var result = await _webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), _cts.Token);

                    if (result.MessageType == WebSocketMessageType.Close)
                    {
                        await _webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, string.Empty, _cts.Token);
                        break;
                    }

                    var message = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    Log("OpenClaw received: " + message);

                    // Handle hello-ok response
                    if (message.Contains("hello-ok"))
                    {
                        SetConnectionState(true);
                    }
                }
                catch (Exception ex)
                {
                    LogError("WebSocket receive error: " + ex.Message);
                    break;
                }
            }

            _wsConnected = false;
            SetConnectionState(false);
        }

        private async Task SendWebSocketMessageAsync(string message)
        {
            if (_webSocket?.State == WebSocketState.Open)
            {
                var bytes = Encoding.UTF8.GetBytes(message);
                await _webSocket.SendAsync(new ArraySegment<byte>(bytes), WebSocketMessageType.Text, true, _cts.Token);
            }
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            if (!_isConnected || !_wsConnected)
            {
                ReportConnectionError();
                executionSummary = "OpenClaw is not currently connected.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "OpenClaw payload JSON was empty.";
                return false;
            }

            OpenClawToolPayload payload;

            try
            {
                payload = JsonUtility.FromJson<OpenClawToolPayload>(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "Failed to parse OpenClaw payload JSON. " + exception.Message;
                return false;
            }

            if (payload == null)
            {
                executionSummary = "Parsed OpenClaw payload was null.";
                return false;
            }

            if (!string.Equals(payload.request, "hello_world_test", StringComparison.Ordinal))
            {
                executionSummary = "Unsupported OpenClaw request: " + payload.request;
                return false;
            }

            _ = SendHelloWorldAsync();

            executionSummary = "Sent hello world test message to OpenClaw.";
            return true;
        }

        private async Task SendHelloWorldAsync()
        {
            await SendMessageToOpenClawAsync("hello OpenClaw, this is the Unity Client making first contact with you!");
        }

        private async Task SendMessageToOpenClawAsync(string messageText)
        {
            var chatReq = new ChatSendRequest
            {
                id = Guid.NewGuid().ToString(),
                @params = new ChatSendParams
                {
                    channel = _openClawChannel,
                    message = messageText,
                    sessionKey = _openClawSessionKey
                }
            };

            var json = JsonUtility.ToJson(chatReq);
            await SendWebSocketMessageAsync(json);
            Log("Sent to OpenClaw: " + messageText);
        }

        private IEnumerator ConnectionCheckCoroutine()
        {
            while (true)
            {
                // Check health via WebSocket state
                var connected = _webSocket?.State == WebSocketState.Open;
                if (connected != _isConnected)
                {
                    SetConnectionState(connected);
                }

                // Reconnect if needed
                if (!_wsConnected && _webSocket?.State != WebSocketState.Connecting)
                {
                    _ = ConnectWebSocketAsync();
                }

                yield return new WaitForSeconds(CONNECTION_CHECK_INTERVAL_SECONDS);
            }
        }

        private void SetConnectionState(bool connected)
        {
            _isConnected = connected;
            GlobalManager.I.State.OpenClawConnected = connected;
        }

        public void ReportConnectionError()
        {
            if (_errorDisplayCoroutine != null)
            {
                StopCoroutine(_errorDisplayCoroutine);
            }

            _errorDisplayCoroutine = StartCoroutine(ShowErrorBoxCoroutine());
        }

        private IEnumerator ShowErrorBoxCoroutine()
        {
            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(true);
            }

            yield return new WaitForSeconds(ERROR_BOX_DURATION_SECONDS);

            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(false);
            }

            _errorDisplayCoroutine = null;
        }

        private void OnDestroy()
        {
            _cts?.Cancel();
            _webSocket?.CloseAsync(WebSocketCloseStatus.NormalClosure, "Closing", CancellationToken.None).Wait();
            _webSocket?.Dispose();
        }
    }
}
