// Generated by ChatGPT and Riko Balakit/Pearl Grey
// HTTP health checks + WebSocket only for messaging

using System;
using System.Collections;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.Networking;

namespace Runtime.Tooling
{
    public class OpenClawTool : BaseTool
    {
        private const float CONNECTION_CHECK_INTERVAL_SECONDS = 10f;
        private const float ERROR_BOX_DURATION_SECONDS = 10f;
        private const int REQUEST_TIMEOUT_SECONDS = 3;

        [Header("Connection UI")]
        [SerializeField]
        private GameObject _openClawErrorBox;

        [Header("Connection Config")]
        [SerializeField]
        private string _openClawHealthEndpoint = "http://localhost:18789/health";

        [SerializeField]
        private string _openClawGatewayUrl = "ws://localhost:18789";

        [SerializeField]
        private string _openClawChannel = "webchat";

        [SerializeField]
        private string _openClawSessionKey = "agent:main:main";

        [Header("Auth")]
        [SerializeField]
        private string _openClawToken = "f538bb993f684055a3757bb83861a3ff0cddbdde869202c3";

        private bool _isConnected;
        private Coroutine _connectionCheckCoroutine;
        private Coroutine _errorDisplayCoroutine;

        public bool IsConnected => _isConnected;

        [Serializable]
        private class OpenClawToolPayload
        {
            public string request;
        }

        [Serializable]
        private class ConnectRequest
        {
            public string type = "req";
            public string id;
            public string method = "connect";
            public ConnectParams @params = new ConnectParams();
        }

        [Serializable]
        private class ConnectParams
        {
            public int minProtocol = 3;
            public int maxProtocol = 3;
            public ClientInfo client = new ClientInfo();
            public string role = "operator";
            public string[] scopes = new[] { "operator.read", "operator.write" };
            public string locale = "en-US";
            public string userAgent = "unity-openclaw-client/1.0";
            public AuthInfo auth = new AuthInfo();
        }

        [Serializable]
        private class ClientInfo
        {
            public string id = "unity-client";
            public string version = "1.0.0";
            public string platform = "windows";
            public string mode = "operator";
        }

        [Serializable]
        private class AuthInfo
        {
            public string token;
        }

        [Serializable]
        private class ChatSendRequest
        {
            public string type = "req";
            public string id;
            public string method = "chat.send";
            public ChatSendParams @params = new ChatSendParams();
        }

        [Serializable]
        private class ChatSendParams
        {
            public string channel;
            public string message;
            public string sessionKey;
        }

        public override void Initialize()
        {
            if (_connectionCheckCoroutine != null)
            {
                StopCoroutine(_connectionCheckCoroutine);
            }

            if (_errorDisplayCoroutine != null)
            {
                StopCoroutine(_errorDisplayCoroutine);
                _errorDisplayCoroutine = null;
            }

            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(false);
            }

            SetConnectionState(false);
            _connectionCheckCoroutine = StartCoroutine(ConnectionCheckCoroutine());
            SetInitialized();
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            if (!_isConnected)
            {
                ReportConnectionError();
                executionSummary = "OpenClaw is not currently connected.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "OpenClaw payload JSON was empty.";
                return false;
            }

            OpenClawToolPayload payload;

            try
            {
                payload = JsonUtility.FromJson<OpenClawToolPayload>(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "Failed to parse OpenClaw payload JSON. " + exception.Message;
                return false;
            }

            if (payload == null)
            {
                executionSummary = "Parsed OpenClaw payload was null.";
                return false;
            }

            if (!string.Equals(payload.request, "hello_world_test", StringComparison.Ordinal))
            {
                executionSummary = "Unsupported OpenClaw request: " + payload.request;
                return false;
            }

            _ = SendHelloWorldAsync();

            executionSummary = "Sent hello world test message to OpenClaw.";
            return true;
        }

        private async Task SendHelloWorldAsync()
        {
            await SendMessageToOpenClawAsync("hello OpenClaw, this is the Unity Client making first contact with you!");
        }

        private async Task SendMessageToOpenClawAsync(string messageText)
        {
            using (var webSocket = new ClientWebSocket())
            using (var cts = new CancellationTokenSource(TimeSpan.FromSeconds(REQUEST_TIMEOUT_SECONDS)))
            {
                try
                {
                    await webSocket.ConnectAsync(new Uri(_openClawGatewayUrl), cts.Token);

                    // Send connect handshake with auth
                    var connectReq = new ConnectRequest
                    {
                        id = Guid.NewGuid().ToString()
                    };
                    connectReq.@params.auth.token = _openClawToken;

                    var connectJson = JsonUtility.ToJson(connectReq);
                    await SendWebSocketMessageAsync(webSocket, connectJson, cts.Token);

                    // Wait for hello-ok response
                    var buffer = new byte[4096];
                    var result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), cts.Token);
                    var response = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    Log("OpenClaw connect response: " + response);

                    if (!response.Contains("hello-ok"))
                    {
                        LogError("OpenClaw authentication failed");
                        return;
                    }

                    // Send the actual message
                    var chatReq = new ChatSendRequest
                    {
                        id = Guid.NewGuid().ToString(),
                        @params = new ChatSendParams
                        {
                            channel = _openClawChannel,
                            message = messageText,
                            sessionKey = _openClawSessionKey
                        }
                    };

                    var chatJson = JsonUtility.ToJson(chatReq);
                    await SendWebSocketMessageAsync(webSocket, chatJson, cts.Token);
                    Log("Sent to OpenClaw: " + messageText);

                    // Wait for response
                    result = await webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), cts.Token);
                    var sendResponse = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    Log("OpenClaw send response: " + sendResponse);

                    await webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Done", cts.Token);
                }
                catch (Exception ex)
                {
                    LogError("OpenClaw WebSocket error: " + ex.Message);
                }
            }
        }

        private async Task SendWebSocketMessageAsync(ClientWebSocket webSocket, string message, CancellationToken token)
        {
            if (webSocket?.State == WebSocketState.Open)
            {
                var bytes = Encoding.UTF8.GetBytes(message);
                await webSocket.SendAsync(new ArraySegment<byte>(bytes), WebSocketMessageType.Text, true, token);
            }
        }

        private IEnumerator ConnectionCheckCoroutine()
        {
            while (true)
            {
                yield return CheckConnectionCoroutine();

                var startTime = DateTime.UtcNow;
                while ((DateTime.UtcNow - startTime).TotalSeconds < CONNECTION_CHECK_INTERVAL_SECONDS)
                {
                    yield return null;
                }
            }
        }

        private IEnumerator CheckConnectionCoroutine()
        {
            using (var request = UnityWebRequest.Get(_openClawHealthEndpoint))
            {
                request.timeout = REQUEST_TIMEOUT_SECONDS;

                yield return request.SendWebRequest();

                if (request.result == UnityWebRequest.Result.Success)
                {
                    SetConnectionState(true);
                }
                else
                {
                    SetConnectionState(false);
                    LogError("OpenClaw health check failed: " + request.error);
                }
            }
        }

        private void SetConnectionState(bool connected)
        {
            _isConnected = connected;
            GlobalManager.I.State.OpenClawConnected = connected;
        }

        public void ReportConnectionError()
        {
            if (_errorDisplayCoroutine != null)
            {
                StopCoroutine(_errorDisplayCoroutine);
            }

            _errorDisplayCoroutine = StartCoroutine(ShowErrorBoxCoroutine());
        }

        private IEnumerator ShowErrorBoxCoroutine()
        {
            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(true);
            }

            var startTime = DateTime.UtcNow;

            while ((DateTime.UtcNow - startTime).TotalSeconds < ERROR_BOX_DURATION_SECONDS)
            {
                yield return null;
            }

            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(false);
            }

            _errorDisplayCoroutine = null;
        }
    }
}
