// Generated by ChatGPT and Riko Balakit/Pearl Grey
// Updated for HTTP health checks + OpenClaw WebSocket chat

using System;
using System.Collections;
using System.Net.WebSockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.Networking;

namespace Runtime.Tooling
{
    public class OpenClawTool : BaseTool
    {
        private const float CONNECTION_CHECK_INTERVAL_SECONDS = 10f;
        private const float ERROR_BOX_DURATION_SECONDS = 10f;
        private const int HTTP_REQUEST_TIMEOUT_SECONDS = 3;

        [Header("Connection UI")]
        [SerializeField]
        private GameObject _openClawErrorBox;

        [Header("Connection Config")]
        [SerializeField]
        private string _openClawHealthEndpoint = "http://localhost:18789/health";

        [SerializeField]
        private string _openClawGatewayUrl = "ws://localhost:18789";

        [SerializeField]
        private string _openClawChannel = "webchat";

        [SerializeField]
        private string _openClawSessionKey = "agent:main:main";

        private bool _isConnected;
        private bool _isWebSocketConnected;

        private ClientWebSocket _webSocket;
        private CancellationTokenSource _cancellationTokenSource;

        private Coroutine _connectionCheckCoroutine;
        private Coroutine _errorDisplayCoroutine;

        public bool IsConnected => _isConnected;

        [Serializable]
        private class OpenClawToolPayload
        {
            public string request;
        }

        [Serializable]
        private class ConnectRequest
        {
            public string type = "req";
            public string id;
            public string method = "connect";
            public ConnectParams @params = new ConnectParams();
        }

        [Serializable]
        private class ConnectParams
        {
            public int minProtocol = 3;
            public int maxProtocol = 3;
            public ClientInfo client = new ClientInfo();
            public string role = "operator";
            public string[] scopes = new[] { "operator.read", "operator.write" };
            public string[] caps = new string[0];
            public string[] commands = new string[0];
            public string locale = "en-US";
            public string userAgent = "unity-openclaw-client/1.0";
            public AuthInfo auth = new AuthInfo();
        }

        [Serializable]
        private class AuthInfo
        {
            public string token = Secrets.OpenClawAuthToken;
        }

        [Serializable]
        private class ClientInfo
        {
            public string id = "unity-client";
            public string version = "1.0.0";
            public string platform = "windows";
            public string mode = "operator";
        }

        [Serializable]
        private class ChatSendRequest
        {
            public string type = "req";
            public string id;
            public string method = "chat.send";
            public ChatSendParams @params = new ChatSendParams();
        }

        [Serializable]
        private class ChatSendParams
        {
            public string channel;
            public string message;
            public string sessionKey;
        }

        public override void Initialize()
        {
            if (_connectionCheckCoroutine != null)
            {
                StopCoroutine(_connectionCheckCoroutine);
                _connectionCheckCoroutine = null;
            }

            if (_errorDisplayCoroutine != null)
            {
                StopCoroutine(_errorDisplayCoroutine);
                _errorDisplayCoroutine = null;
            }

            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(false);
            }

            SetConnectionState(false);
            _isWebSocketConnected = false;

            _connectionCheckCoroutine = StartCoroutine(ConnectionCheckCoroutine());

            SetInitialized();
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            if (!_isConnected)
            {
                ReportConnectionError();
                executionSummary = "OpenClaw health check is failing.";
                return false;
            }

            if (!_isWebSocketConnected)
            {
                ReportConnectionError();
                executionSummary = "OpenClaw WebSocket is not currently connected.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "OpenClaw payload JSON was empty.";
                return false;
            }

            OpenClawToolPayload payload;

            try
            {
                payload = JsonUtility.FromJson<OpenClawToolPayload>(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "Failed to parse OpenClaw payload JSON. " + exception.Message;
                return false;
            }

            if (payload == null)
            {
                executionSummary = "Parsed OpenClaw payload was null.";
                return false;
            }

            if (!string.Equals(payload.request, "hello_world_test", StringComparison.Ordinal))
            {
                executionSummary = "Unsupported OpenClaw request: " + payload.request;
                return false;
            }

            _ = SendHelloWorldAsync();

            executionSummary = "Sent hello world test message to OpenClaw.";
            return true;
        }

        private IEnumerator ConnectionCheckCoroutine()
        {
            while (true)
            {
                yield return CheckHealthCoroutine();

                if (_isConnected)
                {
                    EnsureWebSocketConnection();
                }
                else
                {
                    if (_isWebSocketConnected)
                    {
                        _ = DisconnectWebSocketAsync();
                    }
                }

                var startTime = DateTime.UtcNow;

                while ((DateTime.UtcNow - startTime).TotalSeconds < CONNECTION_CHECK_INTERVAL_SECONDS)
                {
                    yield return null;
                }
            }
        }

        private IEnumerator CheckHealthCoroutine()
        {
            using (var request = UnityWebRequest.Get(_openClawHealthEndpoint))
            {
                request.timeout = HTTP_REQUEST_TIMEOUT_SECONDS;

                yield return request.SendWebRequest();

                if (request.result == UnityWebRequest.Result.Success)
                {
                    SetConnectionState(true);
                }
                else
                {
                    SetConnectionState(false);
                }
            }
        }

        private void EnsureWebSocketConnection()
        {
            if (_webSocket != null)
            {
                if (_webSocket.State == WebSocketState.Open || _webSocket.State == WebSocketState.Connecting)
                {
                    return;
                }
            }

            _ = ConnectWebSocketAsync();
        }

        private async Task ConnectWebSocketAsync()
        {
            try
            {
                await DisconnectWebSocketAsync();

                _cancellationTokenSource = new CancellationTokenSource();
                _webSocket = new ClientWebSocket();

                await _webSocket.ConnectAsync(new Uri(_openClawGatewayUrl), _cancellationTokenSource.Token);

                var connectRequest = new ConnectRequest
                {
                    id = Guid.NewGuid().ToString()
                };

                var connectJson = JsonUtility.ToJson(connectRequest);
                await SendWebSocketMessageAsync(connectJson);

                _isWebSocketConnected = true;
                Log("OpenClaw WebSocket connected.");

                _ = ReceiveLoopAsync();
            }
            catch (Exception exception)
            {
                _isWebSocketConnected = false;
                LogError("OpenClaw WebSocket connection failed: " + exception.Message);
            }
        }

        private async Task ReceiveLoopAsync()
        {
            var buffer = new byte[4096];

            try
            {
                while (_webSocket != null
                    && _webSocket.State == WebSocketState.Open
                    && _cancellationTokenSource != null
                    && !_cancellationTokenSource.Token.IsCancellationRequested)
                {
                    var result = await _webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), _cancellationTokenSource.Token);

                    if (result.MessageType == WebSocketMessageType.Close)
                    {
                        break;
                    }

                    var message = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    Log("OpenClaw received: " + message);
                }
            }
            catch (Exception exception)
            {
                LogError("OpenClaw WebSocket receive loop failed: " + exception.Message);
            }

            _isWebSocketConnected = false;
        }

        private async Task SendHelloWorldAsync()
        {
            await SendMessageToOpenClawAsync("hello OpenClaw, this is the Unity Client making first contact with you!");
        }

        private async Task SendMessageToOpenClawAsync(string messageText)
        {
            if (!_isWebSocketConnected)
            {
                LogError("Cannot send message to OpenClaw because the WebSocket is not connected.");
                return;
            }

            var chatRequest = new ChatSendRequest
            {
                id = Guid.NewGuid().ToString(),
                @params = new ChatSendParams
                {
                    channel = _openClawChannel,
                    message = messageText,
                    sessionKey = _openClawSessionKey
                }
            };

            var json = JsonUtility.ToJson(chatRequest);
            await SendWebSocketMessageAsync(json);

            Log("Sent to OpenClaw: " + messageText);
        }

        private async Task SendWebSocketMessageAsync(string message)
        {
            if (_webSocket == null || _webSocket.State != WebSocketState.Open)
            {
                LogError("Tried to send a WebSocket message while the socket was not open.");
                return;
            }

            var bytes = Encoding.UTF8.GetBytes(message);

            await _webSocket.SendAsync(
                new ArraySegment<byte>(bytes),
                WebSocketMessageType.Text,
                true,
                _cancellationTokenSource.Token);
        }

        private async Task DisconnectWebSocketAsync()
        {
            try
            {
                _isWebSocketConnected = false;

                if (_cancellationTokenSource != null)
                {
                    _cancellationTokenSource.Cancel();
                    _cancellationTokenSource.Dispose();
                    _cancellationTokenSource = null;
                }

                if (_webSocket != null)
                {
                    if (_webSocket.State == WebSocketState.Open || _webSocket.State == WebSocketState.CloseReceived)
                    {
                        await _webSocket.CloseAsync(
                            WebSocketCloseStatus.NormalClosure,
                            "Closing",
                            CancellationToken.None);
                    }

                    _webSocket.Dispose();
                    _webSocket = null;
                }
            }
            catch (Exception exception)
            {
                LogError("OpenClaw WebSocket disconnect failed: " + exception.Message);
            }
        }

        private void SetConnectionState(bool connected)
        {
            _isConnected = connected;
            GlobalManager.I.State.OpenClawConnected = connected;
        }

        public void ReportConnectionError()
        {
            if (_errorDisplayCoroutine != null)
            {
                StopCoroutine(_errorDisplayCoroutine);
            }

            _errorDisplayCoroutine = StartCoroutine(ShowErrorBoxCoroutine());
        }

        private IEnumerator ShowErrorBoxCoroutine()
        {
            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(true);
            }

            var startTime = DateTime.UtcNow;

            while ((DateTime.UtcNow - startTime).TotalSeconds < ERROR_BOX_DURATION_SECONDS)
            {
                yield return null;
            }

            if (_openClawErrorBox != null)
            {
                _openClawErrorBox.SetActive(false);
            }

            _errorDisplayCoroutine = null;
        }

        private void OnDestroy()
        {
            _ = DisconnectWebSocketAsync();
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey