// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using Configuration;
using Newtonsoft.Json;
using UnityEngine;

namespace Runtime.Tooling
{
    public class SettingsTool : BaseTool
    {
        public override void Initialize()
        {
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "SettingsTool received an empty payloadJson.";
                return false;
            }

            SettingsToolPayload payload;

            try
            {
                payload = JsonConvert.DeserializeObject<SettingsToolPayload>(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "SettingsTool failed to parse payloadJson. Exception: " + exception.Message;
                return false;
            }

            if (payload == null)
            {
                executionSummary = "SettingsTool payload deserialized to null.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payload.settingName))
            {
                executionSummary = "SettingsTool payload did not include settingName.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payload.value))
            {
                executionSummary = "SettingsTool payload did not include value.";
                return false;
            }

            var normalizedSettingName = payload.settingName.Trim();
            var normalizedValue = payload.value.Trim();

            if (string.Equals(normalizedSettingName, "Mode", StringComparison.OrdinalIgnoreCase))
            {
                return TryApplyMode(normalizedValue, out executionSummary);
            }

            if (string.Equals(normalizedSettingName, "AuditMode", StringComparison.OrdinalIgnoreCase))
            {
                return TryApplyAuditMode(normalizedValue, out executionSummary);
            }

            if (string.Equals(normalizedSettingName, "QuietMode", StringComparison.OrdinalIgnoreCase))
            {
                return TryApplyQuietMode(normalizedValue, out executionSummary);
            }

            if (string.Equals(normalizedSettingName, "RespondToName", StringComparison.OrdinalIgnoreCase))
            {
                return TryApplyRespondToName(normalizedValue, out executionSummary);
            }

            executionSummary = "SettingsTool received unknown settingName: " + normalizedSettingName;
            return false;
        }

        private bool TryApplyMode(string value, out string executionSummary)
        {
            if (string.Equals(value, "Chill", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.CurrentMode = BehaviourMode.Chill;
                executionSummary = "Changed Mode to Chill.";
                return true;
            }

            if (string.Equals(value, "ProductiveHobby", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveHobby;
                executionSummary = "Changed Mode to ProductiveHobby.";
                return true;
            }

            if (string.Equals(value, "ProductiveWork", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveWork;
                executionSummary = "Changed Mode to ProductiveWork.";
                return true;
            }

            if (string.Equals(value, "ProductiveDomestic", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveDomestic;
                executionSummary = "Changed Mode to ProductiveDomestic.";
                return true;
            }

            executionSummary = "SettingsTool received invalid Mode value: " + value;
            return false;
        }

        private bool TryApplyAuditMode(string value, out string executionSummary)
        {
            if (string.Equals(value, "On", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.AuditModeEnabled = true;
                executionSummary = "Changed AuditMode to On.";
                return true;
            }

            if (string.Equals(value, "Off", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.AuditModeEnabled = false;
                executionSummary = "Changed AuditMode to Off.";
                return true;
            }

            executionSummary = "SettingsTool received invalid AuditMode value: " + value;
            return false;
        }

        private bool TryApplyQuietMode(string value, out string executionSummary)
        {
            if (string.Equals(value, "On", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.QuietModeEnabled = true;
                executionSummary = "Changed QuietMode to On.";
                return true;
            }

            if (string.Equals(value, "Off", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.QuietModeEnabled = false;
                executionSummary = "Changed QuietMode to Off.";
                return true;
            }

            executionSummary = "SettingsTool received invalid QuietMode value: " + value;
            return false;
        }

        private bool TryApplyRespondToName(string value, out string executionSummary)
        {
            if (string.Equals(value, "On", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.RespondToNameEnabled = true;
                executionSummary = "Changed RespondToName to On.";
                return true;
            }

            if (string.Equals(value, "Off", StringComparison.OrdinalIgnoreCase))
            {
                GlobalManager.I.State.RespondToNameEnabled = false;
                executionSummary = "Changed RespondToName to Off.";
                return true;
            }

            executionSummary = "SettingsTool received invalid RespondToName value: " + value;
            return false;
        }

        [Serializable]
        private class SettingsToolPayload
        {
            public string settingName;
            public string value;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey