// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace Runtime.Tooling
{
    public class SettingsTool : BaseTool
    {
        public override void Initialize()
        {
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "SettingsTool received an empty payloadJson.";
                return false;
            }

            JToken rootToken;

            try
            {
                rootToken = JToken.Parse(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "SettingsTool failed to parse payloadJson. Exception: " + exception.Message;
                return false;
            }

            var settingsToApply = new List<SettingsToolPayload>();

            if (rootToken.Type == JTokenType.Object)
            {
                SettingsToolPayload singlePayload;

                try
                {
                    singlePayload = rootToken.ToObject<SettingsToolPayload>();
                }
                catch (Exception exception)
                {
                    executionSummary = "SettingsTool failed to deserialize single payload object. Exception: " + exception.Message;
                    return false;
                }

                if (singlePayload == null)
                {
                    executionSummary = "SettingsTool single payload deserialized to null.";
                    return false;
                }

                settingsToApply.Add(singlePayload);
            }
            else if (rootToken.Type == JTokenType.Array)
            {
                var payloadArray = rootToken as JArray;

                if (payloadArray == null || payloadArray.Count == 0)
                {
                    executionSummary = "SettingsTool received an empty settings array.";
                    return false;
                }

                for (var i = 0; i < payloadArray.Count; i++)
                {
                    SettingsToolPayload arrayItemPayload;

                    try
                    {
                        arrayItemPayload = payloadArray[i].ToObject<SettingsToolPayload>();
                    }
                    catch (Exception exception)
                    {
                        executionSummary = "SettingsTool failed to deserialize settings array item at index " + i + ". Exception: " + exception.Message;
                        return false;
                    }

                    if (arrayItemPayload == null)
                    {
                        executionSummary = "SettingsTool settings array item at index " + i + " deserialized to null.";
                        return false;
                    }

                    settingsToApply.Add(arrayItemPayload);
                }
            }
            else
            {
                executionSummary = "SettingsTool payloadJson must be either an object or an array of objects.";
                return false;
            }

            var pendingSettingChanges = new List<PendingSettingChange>();

            for (var i = 0; i < settingsToApply.Count; i++)
            {
                var payload = settingsToApply[i];

                if (string.IsNullOrWhiteSpace(payload.settingName))
                {
                    executionSummary = "SettingsTool payload at index " + i + " did not include settingName.";
                    return false;
                }

                if (string.IsNullOrWhiteSpace(payload.value))
                {
                    executionSummary = "SettingsTool payload at index " + i + " did not include value.";
                    return false;
                }

                var normalizedSettingName = payload.settingName.Trim();
                var normalizedValue = payload.value.Trim();

                if (!TryBuildPendingSettingChange(normalizedSettingName, normalizedValue, out var pendingSettingChange, out var validationError))
                {
                    executionSummary = "SettingsTool payload at index " + i + " was invalid. " + validationError;
                    return false;
                }

                pendingSettingChanges.Add(pendingSettingChange);
            }

            var appliedChangeSummaries = new List<string>();

            for (var i = 0; i < pendingSettingChanges.Count; i++)
            {
                var pendingSettingChange = pendingSettingChanges[i];
                pendingSettingChange.Apply();
                appliedChangeSummaries.Add(pendingSettingChange.SuccessSummary);
            }

            executionSummary = string.Join(" ", appliedChangeSummaries);
            return true;
        }

        private bool TryBuildPendingSettingChange(
            string normalizedSettingName,
            string normalizedValue,
            out PendingSettingChange pendingSettingChange,
            out string validationError)
        {
            pendingSettingChange = null;
            validationError = null;

            if (string.Equals(normalizedSettingName, "Mode", StringComparison.OrdinalIgnoreCase))
            {
                return TryBuildModeChange(normalizedValue, out pendingSettingChange, out validationError);
            }

            if (string.Equals(normalizedSettingName, "AuditMode", StringComparison.OrdinalIgnoreCase))
            {
                return TryBuildBooleanSettingChange(
                    normalizedValue,
                    () => GlobalManager.I.State.AuditModeEnabled = true,
                    () => GlobalManager.I.State.AuditModeEnabled = false,
                    "AuditMode",
                    out pendingSettingChange,
                    out validationError);
            }

            if (string.Equals(normalizedSettingName, "QuietMode", StringComparison.OrdinalIgnoreCase))
            {
                return TryBuildBooleanSettingChange(
                    normalizedValue,
                    () => GlobalManager.I.State.QuietModeEnabled = true,
                    () => GlobalManager.I.State.QuietModeEnabled = false,
                    "QuietMode",
                    out pendingSettingChange,
                    out validationError);
            }

            if (string.Equals(normalizedSettingName, "RespondToName", StringComparison.OrdinalIgnoreCase))
            {
                return TryBuildBooleanSettingChange(
                    normalizedValue,
                    () => GlobalManager.I.State.RespondToNameEnabled = true,
                    () => GlobalManager.I.State.RespondToNameEnabled = false,
                    "RespondToName",
                    out pendingSettingChange,
                    out validationError);
            }

            validationError = "Unknown settingName: " + normalizedSettingName;
            return false;
        }

        private bool TryBuildModeChange(
            string value,
            out PendingSettingChange pendingSettingChange,
            out string validationError)
        {
            pendingSettingChange = null;
            validationError = null;

            if (string.Equals(value, "Chill", StringComparison.OrdinalIgnoreCase))
            {
                pendingSettingChange = new PendingSettingChange(
                    () => GlobalManager.I.State.CurrentMode = BehaviourMode.Chill,
                    "Changed Mode to Chill.");
                return true;
            }

            if (string.Equals(value, "ProductiveHobby", StringComparison.OrdinalIgnoreCase))
            {
                pendingSettingChange = new PendingSettingChange(
                    () => GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveHobby,
                    "Changed Mode to ProductiveHobby.");
                return true;
            }

            if (string.Equals(value, "ProductiveWork", StringComparison.OrdinalIgnoreCase))
            {
                pendingSettingChange = new PendingSettingChange(
                    () => GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveWork,
                    "Changed Mode to ProductiveWork.");
                return true;
            }

            if (string.Equals(value, "ProductiveDomestic", StringComparison.OrdinalIgnoreCase))
            {
                pendingSettingChange = new PendingSettingChange(
                    () => GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveDomestic,
                    "Changed Mode to ProductiveDomestic.");
                return true;
            }

            validationError = "Invalid Mode value: " + value;
            return false;
        }

        private bool TryBuildBooleanSettingChange(
            string value,
            Action applyOnAction,
            Action applyOffAction,
            string settingName,
            out PendingSettingChange pendingSettingChange,
            out string validationError)
        {
            pendingSettingChange = null;
            validationError = null;

            if (string.Equals(value, "On", StringComparison.OrdinalIgnoreCase))
            {
                pendingSettingChange = new PendingSettingChange(
                    applyOnAction,
                    "Changed " + settingName + " to On.");
                return true;
            }

            if (string.Equals(value, "Off", StringComparison.OrdinalIgnoreCase))
            {
                pendingSettingChange = new PendingSettingChange(
                    applyOffAction,
                    "Changed " + settingName + " to Off.");
                return true;
            }

            validationError = "Invalid " + settingName + " value: " + value;
            return false;
        }

        [Serializable]
        private class SettingsToolPayload
        {
            public string settingName;
            public string value;
        }

        private class PendingSettingChange
        {
            private readonly Action _applyAction;
            private readonly string _successSummary;

            public string SuccessSummary => _successSummary;

            public PendingSettingChange(Action applyAction, string successSummary)
            {
                _applyAction = applyAction;
                _successSummary = successSummary;
            }

            public void Apply()
            {
                _applyAction();
            }
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey