// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;
using UnityEngine;

namespace Runtime.Tooling
{
    public class TaskOrganizerTool : BaseTool
    {
        private bool _hasLoadedTaskStateFromFile;

        protected override void InitializeInternal()
        {
            TryLoadTaskStateFromFile();
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (!_hasLoadedTaskStateFromFile)
            {
                if (!TryLoadTaskStateFromFile())
                {
                    executionSummary = "TaskOrganizerTool could not load TaskState from file.";
                    return false;
                }
            }

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "TaskOrganizerTool received an empty payloadJson.";
                return false;
            }

            JToken rootToken;

            try
            {
                rootToken = JToken.Parse(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "TaskOrganizerTool failed to parse payloadJson. Exception: " + exception.Message;
                return false;
            }

            var payloads = new List<TaskToolPayload>();

            if (rootToken.Type == JTokenType.Object)
            {
                TaskToolPayload payload;

                try
                {
                    payload = rootToken.ToObject<TaskToolPayload>();
                }
                catch (Exception exception)
                {
                    executionSummary = "TaskOrganizerTool failed to deserialize single payload object. Exception: " + exception.Message;
                    return false;
                }

                if (payload == null)
                {
                    executionSummary = "TaskOrganizerTool payload deserialized to null.";
                    return false;
                }

                payloads.Add(payload);
            }
            else if (rootToken.Type == JTokenType.Array)
            {
                var payloadArray = rootToken as JArray;

                if (payloadArray == null || payloadArray.Count == 0)
                {
                    executionSummary = "TaskOrganizerTool received an empty payload array.";
                    return false;
                }

                for (var i = 0; i < payloadArray.Count; i++)
                {
                    TaskToolPayload payload;

                    try
                    {
                        payload = payloadArray[i].ToObject<TaskToolPayload>();
                    }
                    catch (Exception exception)
                    {
                        executionSummary = "TaskOrganizerTool failed to deserialize payload at index " + i + ". Exception: " + exception.Message;
                        return false;
                    }

                    if (payload == null)
                    {
                        executionSummary = "TaskOrganizerTool payload at index " + i + " deserialized to null.";
                        return false;
                    }

                    payloads.Add(payload);
                }
            }
            else
            {
                executionSummary = "TaskOrganizerTool payloadJson must be object or array.";
                return false;
            }

            var summaries = new List<string>();

            for (var i = 0; i < payloads.Count; i++)
            {
                var payload = payloads[i];

                if (string.IsNullOrWhiteSpace(payload.action))
                {
                    executionSummary = "TaskOrganizerTool payload at index " + i + " is missing action.";
                    return false;
                }

                if (!TryApplyAction(payload, out var actionSummary, out var error))
                {
                    executionSummary = "TaskOrganizerTool action failed at index " + i + ". " + error;
                    return false;
                }

                summaries.Add(actionSummary);
            }

            executionSummary = string.Join(" ", summaries);
            return true;
        }

        private bool TryApplyAction(TaskToolPayload payload, out string summary, out string error)
        {
            summary = null;
            error = null;

            var action = payload.action.Trim().ToLowerInvariant();

            if (action == "createtask")
            {
                if (string.IsNullOrWhiteSpace(payload.name))
                {
                    error = "createTask requires name.";
                    return false;
                }

                var trimmedName = payload.name.Trim();

                if (trimmedName.Length > 128)
                {
                    error = "createTask name exceeds 128 characters.";
                    return false;
                }

                var normalizedNotes = NormalizeNotes(payload.notes);

                if (normalizedNotes == null && !string.IsNullOrWhiteSpace(payload.notes))
                {
                    error = "createTask notes exceeds 256 characters.";
                    return false;
                }

                var category = ParseEnum(payload.category, TaskCategory.WORK);
                var priority = ParseEnum(payload.priority, TaskPriority.MEDIUM);
                var urgency = ParseEnum(payload.urgency, TaskUrgency.MEDIUM);
                var status = ParseEnum(payload.status, TaskStatus.PENDING);

                var task = new TaskData
                {
                    taskId = GlobalManager.I.TaskState.GetNextTaskId(),
                    name = trimmedName,
                    category = category,
                    priority = priority,
                    urgency = urgency,
                    status = status,
                    datetimeAdded = DateTime.UtcNow,
                    notes = normalizedNotes
                };

                GlobalManager.I.TaskState.Tasks.Add(task);

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Created task " + task.taskId + ": " + task.name + ".";
                return true;
            }

            if (action == "deletetask")
            {
                if (!GlobalManager.I.TaskState.RemoveTask(payload.taskId))
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Deleted task " + payload.taskId + ".";
                return true;
            }

            if (action == "rename")
            {
                var task = GlobalManager.I.TaskState.FindTask(payload.taskId);

                if (task == null)
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                if (string.IsNullOrWhiteSpace(payload.name))
                {
                    error = "rename requires name.";
                    return false;
                }

                var trimmedName = payload.name.Trim();

                if (trimmedName.Length > 128)
                {
                    error = "rename name exceeds 128 characters.";
                    return false;
                }

                task.name = trimmedName;

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Renamed task " + task.taskId + " to " + task.name + ".";
                return true;
            }

            if (action == "setcategory")
            {
                var task = GlobalManager.I.TaskState.FindTask(payload.taskId);

                if (task == null)
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                task.category = ParseEnum(payload.category, task.category);

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Task " + task.taskId + " category set to " + task.category + ".";
                return true;
            }

            if (action == "setpriority")
            {
                var task = GlobalManager.I.TaskState.FindTask(payload.taskId);

                if (task == null)
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                task.priority = ParseEnum(payload.priority, task.priority);

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Task " + task.taskId + " priority set to " + task.priority + ".";
                return true;
            }

            if (action == "seturgency")
            {
                var task = GlobalManager.I.TaskState.FindTask(payload.taskId);

                if (task == null)
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                task.urgency = ParseEnum(payload.urgency, task.urgency);

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Task " + task.taskId + " urgency set to " + task.urgency + ".";
                return true;
            }

            if (action == "setstatus")
            {
                var task = GlobalManager.I.TaskState.FindTask(payload.taskId);

                if (task == null)
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                task.status = ParseEnum(payload.status, task.status);

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Task " + task.taskId + " status set to " + task.status + ".";
                return true;
            }

            if (action == "setnotes")
            {
                var task = GlobalManager.I.TaskState.FindTask(payload.taskId);

                if (task == null)
                {
                    error = "Task not found: " + payload.taskId;
                    return false;
                }

                var normalizedNotes = NormalizeNotes(payload.notes);

                if (normalizedNotes == null && !string.IsNullOrWhiteSpace(payload.notes))
                {
                    error = "setNotes notes exceeds 256 characters.";
                    return false;
                }

                task.notes = normalizedNotes;

                if (!TrySaveTaskState(out error))
                {
                    return false;
                }

                summary = "Updated notes for task " + task.taskId + ".";
                return true;
            }

            error = "Unknown action: " + payload.action;
            return false;
        }

        private bool TryLoadTaskStateFromFile()
        {
            if (GlobalManager.I == null)
            {
                Debug.LogError("TaskOrganizerTool could not load TaskState because GlobalManager.I is null.");
                return false;
            }

            if (GlobalManager.I.TaskState == null)
            {
                GlobalManager.I.TaskState = new TaskState();
            }

            if (!GlobalManager.I.TaskState.LoadFromFile(out var errorMessage))
            {
                Debug.LogError("TaskOrganizerTool failed to load TaskState from file. " + errorMessage);
                return false;
            }

            _hasLoadedTaskStateFromFile = true;
            return true;
        }

        private bool TrySaveTaskState(out string error)
        {
            error = null;

            if (GlobalManager.I == null || GlobalManager.I.TaskState == null)
            {
                error = "TaskState is null.";
                return false;
            }

            if (!GlobalManager.I.TaskState.SaveToFile(out var errorMessage))
            {
                error = "Failed to save TaskState to file. " + errorMessage;
                return false;
            }

            return true;
        }

        private string NormalizeNotes(string notes)
        {
            if (string.IsNullOrWhiteSpace(notes))
            {
                return null;
            }

            var trimmedNotes = notes.Trim();

            if (trimmedNotes.Length > 256)
            {
                return null;
            }

            return trimmedNotes;
        }

        private T ParseEnum<T>(string value, T defaultValue) where T : struct
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return defaultValue;
            }

            if (Enum.TryParse(value, true, out T parsedValue))
            {
                return parsedValue;
            }

            return defaultValue;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey