// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;
using TMPro;
using UnityEngine;

namespace Runtime.Tooling
{
    public class ToDoListDisplayTool : BaseTool
    {
        private const float DEFAULT_SHOW_DURATION_MINUTES = 5f;

        [SerializeField]
        private GameObject _toDoListDisplayPrefab;

        [SerializeField]
        private TMP_Text _toDoListText;

        private DateTime _hideAtUtc = DateTime.MinValue;

        [Serializable]
        private class ToDoListDisplayToolPayload
        {
            public string option;
            public float? durationMinutes;
            public List<ToDoListDisplayItemPayload> items;
        }

        [Serializable]
        private class ToDoListDisplayItemPayload
        {
            public string status;
            public string item;
        }

        public override void Initialize()
        {
            _hideAtUtc = DateTime.UtcNow.AddMinutes(-1f);

            if (_toDoListDisplayPrefab != null)
            {
                _toDoListDisplayPrefab.SetActive(false);
            }
        }

        public void Update()
        {
            if (_toDoListDisplayPrefab == null)
            {
                return;
            }

            if (!_toDoListDisplayPrefab.activeSelf)
            {
                return;
            }

            if (ShouldHideToDoList())
            {
                HideToDoListDisplay();
            }
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "ToDoListDisplayTool received empty payloadJson.";
                return false;
            }

            ToDoListDisplayToolPayload payload;

            try
            {
                payload = JsonConvert.DeserializeObject<ToDoListDisplayToolPayload>(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "Failed to parse ToDoListDisplayTool payloadJson. Exception: " + exception.Message;
                return false;
            }

            if (payload == null)
            {
                executionSummary = "ToDoListDisplayTool payload deserialized to null.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payload.option))
            {
                executionSummary = "ToDoListDisplayTool payload missing option.";
                return false;
            }

            if (_toDoListDisplayPrefab == null)
            {
                executionSummary = "ToDoListDisplayTool is missing _toDoListDisplayPrefab reference.";
                return false;
            }

            if (_toDoListText == null)
            {
                executionSummary = "ToDoListDisplayTool is missing _toDoListText reference.";
                return false;
            }

            var normalizedOption = payload.option.Trim();

            if (string.Equals(normalizedOption, "hide", StringComparison.OrdinalIgnoreCase))
            {
                SetHideTimeToOneMinuteInPast();
                HideToDoListDisplay();
                executionSummary = "Hid to-do list display.";
                return true;
            }

            if (!string.Equals(normalizedOption, "show", StringComparison.OrdinalIgnoreCase))
            {
                executionSummary = "Invalid ToDoListDisplayTool option: " + payload.option;
                return false;
            }

            var formattedToDoListText = BuildFormattedToDoListText(payload.items);
            _toDoListText.text = formattedToDoListText;

            ShowToDoListDisplay();

            if (payload.durationMinutes.HasValue)
            {
                var requestedDurationMinutes = payload.durationMinutes.Value;

                if (requestedDurationMinutes <= 0f)
                {
                    executionSummary = "ToDoListDisplayTool durationMinutes must be greater than 0 when provided.";
                    return false;
                }

                _hideAtUtc = DateTime.UtcNow.AddMinutes(requestedDurationMinutes);
                executionSummary = "Showing to-do list for " + requestedDurationMinutes + " minutes.";
                return true;
            }

            _hideAtUtc = DateTime.MaxValue;
            executionSummary = "Showing to-do list indefinitely.";
            return true;
        }

        private bool ShouldHideToDoList()
        {
            return DateTime.UtcNow >= _hideAtUtc;
        }

        private void SetHideTimeToOneMinuteInPast()
        {
            _hideAtUtc = DateTime.UtcNow.AddMinutes(-1f);
        }

        private string BuildFormattedToDoListText(List<ToDoListDisplayItemPayload> items)
        {
            var inProgressItems = new List<string>();
            var pendingItems = new List<string>();
            var blockedItems = new List<string>();
            var finishedItems = new List<string>();

            if (items != null)
            {
                for (var i = 0; i < items.Count; i++)
                {
                    var currentItem = items[i];

                    if (currentItem == null)
                    {
                        continue;
                    }

                    if (string.IsNullOrWhiteSpace(currentItem.item))
                    {
                        continue;
                    }

                    var normalizedStatus = currentItem.status;

                    if (string.IsNullOrWhiteSpace(normalizedStatus))
                    {
                        normalizedStatus = "pending";
                    }

                    normalizedStatus = normalizedStatus.Trim();

                    var trimmedItemText = currentItem.item.Trim();

                    if (string.Equals(normalizedStatus, "in progress", StringComparison.OrdinalIgnoreCase))
                    {
                        inProgressItems.Add(trimmedItemText);
                        continue;
                    }

                    if (string.Equals(normalizedStatus, "pending", StringComparison.OrdinalIgnoreCase))
                    {
                        pendingItems.Add(trimmedItemText);
                        continue;
                    }

                    if (string.Equals(normalizedStatus, "blocked", StringComparison.OrdinalIgnoreCase))
                    {
                        blockedItems.Add(trimmedItemText);
                        continue;
                    }

                    if (string.Equals(normalizedStatus, "finished", StringComparison.OrdinalIgnoreCase))
                    {
                        finishedItems.Add(trimmedItemText);
                        continue;
                    }

                    pendingItems.Add(trimmedItemText);
                }
            }

            var stringBuilder = new StringBuilder(2048);

            AppendSectionIfAny(stringBuilder, "IN PROGRESS", inProgressItems);
            AppendSectionIfAny(stringBuilder, "PENDING", pendingItems);
            AppendSectionIfAny(stringBuilder, "BLOCKED", blockedItems);
            AppendSectionIfAny(stringBuilder, "FINISHED", finishedItems);

            if (stringBuilder.Length == 0)
            {
                stringBuilder.Append("No to-do items.");
            }

            return stringBuilder.ToString().TrimEnd();
        }

        private void AppendSectionIfAny(StringBuilder stringBuilder, string headerText, List<string> items)
        {
            if (items == null || items.Count == 0)
            {
                return;
            }

            if (stringBuilder.Length > 0)
            {
                stringBuilder.AppendLine();
                stringBuilder.AppendLine();
            }

            stringBuilder.AppendLine(headerText);

            for (var i = 0; i < items.Count; i++)
            {
                stringBuilder.Append("• ");
                stringBuilder.AppendLine(items[i]);
            }
        }

        private void ShowToDoListDisplay()
        {
            _toDoListDisplayPrefab.SetActive(true);
        }

        private void HideToDoListDisplay()
        {
            _toDoListDisplayPrefab.SetActive(false);
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey