// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;
using TMPro;
using UnityEngine;

namespace Runtime.Tooling
{
    public class ToDoListDisplayTool : BaseTool
    {
        [SerializeField]
        private GameObject _toDoListDisplayPrefab;

        [SerializeField]
        private TMP_Text _toDoListText;

        [SerializeField]
        private Color _importantTextColor = Color.red;

        [SerializeField]
        private Color _normalTextColor = Color.black;

        [SerializeField]
        private string _urgentPrefix = "[URGENT] ";

        [SerializeField]
        private string _highPriorityPrefix = "[HIGH PRIORITY] ";

        private DateTime _hideAtUtc = DateTime.MinValue;

        [Serializable]
        private class ToDoListDisplayToolPayload
        {
            public string option;
            public float? durationMinutes;
        }

        protected override void InitializeInternal()
        {
            _hideAtUtc = DateTime.UtcNow.AddMinutes(-1f);

            if (_toDoListDisplayPrefab != null)
            {
                _toDoListDisplayPrefab.SetActive(false);
            }
        }

        public void Update()
        {
            if (_toDoListDisplayPrefab == null)
            {
                return;
            }

            if (!_toDoListDisplayPrefab.activeSelf)
            {
                return;
            }

            if (ShouldHideToDoList())
            {
                HideToDoListDisplay();
            }
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                executionSummary = "ToDoListDisplayTool received empty payloadJson.";
                return false;
            }

            ToDoListDisplayToolPayload payload;

            try
            {
                payload = JsonConvert.DeserializeObject<ToDoListDisplayToolPayload>(payloadJson);
            }
            catch (Exception exception)
            {
                executionSummary = "Failed to parse ToDoListDisplayTool payloadJson. Exception: " + exception.Message;
                return false;
            }

            if (payload == null)
            {
                executionSummary = "ToDoListDisplayTool payload deserialized to null.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(payload.option))
            {
                executionSummary = "ToDoListDisplayTool payload missing option.";
                return false;
            }

            if (_toDoListDisplayPrefab == null)
            {
                executionSummary = "ToDoListDisplayTool is missing _toDoListDisplayPrefab reference.";
                return false;
            }

            if (_toDoListText == null)
            {
                executionSummary = "ToDoListDisplayTool is missing _toDoListText reference.";
                return false;
            }

            var normalizedOption = payload.option.Trim();

            if (string.Equals(normalizedOption, "hide", StringComparison.OrdinalIgnoreCase))
            {
                SetHideTimeToOneMinuteInPast();
                HideToDoListDisplay();
                executionSummary = "Hid to-do list display.";
                return true;
            }

            if (!string.Equals(normalizedOption, "show", StringComparison.OrdinalIgnoreCase))
            {
                executionSummary = "Invalid ToDoListDisplayTool option: " + payload.option;
                return false;
            }

            var formattedToDoListText = BuildFormattedToDoListTextFromTaskState();
            _toDoListText.text = formattedToDoListText;

            ShowToDoListDisplay();

            if (payload.durationMinutes.HasValue)
            {
                var requestedDurationMinutes = payload.durationMinutes.Value;

                if (requestedDurationMinutes <= 0f)
                {
                    executionSummary = "ToDoListDisplayTool durationMinutes must be greater than 0 when provided.";
                    return false;
                }

                _hideAtUtc = DateTime.UtcNow.AddMinutes(requestedDurationMinutes);
                executionSummary = "Showing to-do list for " + requestedDurationMinutes + " minutes.";
                return true;
            }

            _hideAtUtc = DateTime.MaxValue;
            executionSummary = "Showing to-do list indefinitely.";
            return true;
        }

        private bool ShouldHideToDoList()
        {
            return DateTime.UtcNow >= _hideAtUtc;
        }

        private void SetHideTimeToOneMinuteInPast()
        {
            _hideAtUtc = DateTime.UtcNow.AddMinutes(-1f);
        }

        private string BuildFormattedToDoListTextFromTaskState()
        {
            var inProgressImportantItems = new List<string>();
            var inProgressNormalItems = new List<string>();

            var pendingImportantItems = new List<string>();
            var pendingNormalItems = new List<string>();

            var blockedImportantItems = new List<string>();
            var blockedNormalItems = new List<string>();

            var finishedItems = new List<string>();

            var taskState = GlobalManager.I != null ? GlobalManager.I.TaskState : null;
            var tasks = taskState != null ? taskState.Tasks : null;

            if (tasks != null)
            {
                for (var taskIndex = 0; taskIndex < tasks.Count; taskIndex++)
                {
                    var currentTask = tasks[taskIndex];

                    if (currentTask == null)
                    {
                        continue;
                    }

                    if (string.IsNullOrWhiteSpace(currentTask.name))
                    {
                        continue;
                    }

                    if (ShouldHideTaskFromDisplay(currentTask))
                    {
                        continue;
                    }

                    var formattedTaskText = BuildFormattedTaskText(currentTask);
                    var isImportantTask = IsImportantTaskForDisplay(currentTask);
                    var normalizedStatus = currentTask.status.ToString();

                    if (string.Equals(normalizedStatus, "INPROGRESS", StringComparison.OrdinalIgnoreCase))
                    {
                        if (isImportantTask)
                        {
                            inProgressImportantItems.Add(formattedTaskText);
                        }
                        else
                        {
                            inProgressNormalItems.Add(formattedTaskText);
                        }

                        continue;
                    }

                    if (string.Equals(normalizedStatus, "PENDING", StringComparison.OrdinalIgnoreCase))
                    {
                        if (isImportantTask)
                        {
                            pendingImportantItems.Add(formattedTaskText);
                        }
                        else
                        {
                            pendingNormalItems.Add(formattedTaskText);
                        }

                        continue;
                    }

                    if (string.Equals(normalizedStatus, "BLOCKED", StringComparison.OrdinalIgnoreCase))
                    {
                        if (isImportantTask)
                        {
                            blockedImportantItems.Add(formattedTaskText);
                        }
                        else
                        {
                            blockedNormalItems.Add(formattedTaskText);
                        }

                        continue;
                    }

                    if (string.Equals(normalizedStatus, "DONE", StringComparison.OrdinalIgnoreCase))
                    {
                        finishedItems.Add(formattedTaskText);
                        continue;
                    }

                    if (isImportantTask)
                    {
                        pendingImportantItems.Add(formattedTaskText);
                    }
                    else
                    {
                        pendingNormalItems.Add(formattedTaskText);
                    }
                }
            }

            var stringBuilder = new StringBuilder(2048);

            AppendSectionIfAny(stringBuilder, "IN PROGRESS", inProgressImportantItems, inProgressNormalItems);
            AppendSectionIfAny(stringBuilder, "PENDING", pendingImportantItems, pendingNormalItems);
            AppendSectionIfAny(stringBuilder, "BLOCKED", blockedImportantItems, blockedNormalItems);
            AppendSectionIfAny(stringBuilder, "FINISHED", null, finishedItems);

            if (stringBuilder.Length == 0)
            {
                stringBuilder.Append("No to-do items.");
            }

            return stringBuilder.ToString().TrimEnd();
        }

        private bool ShouldHideTaskFromDisplay(TaskData taskData)
        {
            var normalizedStatus = taskData.status.ToString();

            if (string.Equals(normalizedStatus, "CANCELLED", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (string.Equals(normalizedStatus, "ARCHIVED", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            return false;
        }

        private bool IsFinishedLikeTask(TaskData taskData)
        {
            var normalizedStatus = taskData.status.ToString();

            if (string.Equals(normalizedStatus, "DONE", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (string.Equals(normalizedStatus, "CANCELLED", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            if (string.Equals(normalizedStatus, "ARCHIVED", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            return false;
        }

        private bool IsImportantTaskForDisplay(TaskData taskData)
        {
            if (IsFinishedLikeTask(taskData))
            {
                return false;
            }

            return taskData.priority == TaskPriority.HIGH ||
                   taskData.urgency == TaskUrgency.HIGH;
        }

        private string BuildFormattedTaskText(TaskData taskData)
        {
            var stringBuilder = new StringBuilder(256);
            var isImportantTask = IsImportantTaskForDisplay(taskData);

            if (isImportantTask)
            {
                if (taskData.urgency == TaskUrgency.HIGH && !string.IsNullOrWhiteSpace(_urgentPrefix))
                {
                    stringBuilder.Append(_urgentPrefix);
                }

                if (taskData.priority == TaskPriority.HIGH && !string.IsNullOrWhiteSpace(_highPriorityPrefix))
                {
                    stringBuilder.Append(_highPriorityPrefix);
                }
            }

            stringBuilder.Append(taskData.name.Trim());

            var escapedText = EscapeRichText(stringBuilder.ToString());
            var colorHex = isImportantTask
                ? ColorUtility.ToHtmlStringRGB(_importantTextColor)
                : ColorUtility.ToHtmlStringRGB(_normalTextColor);

            if (isImportantTask)
            {
                return "<b><color=#" + colorHex + ">" + escapedText + "</color></b>";
            }

            return "<color=#" + colorHex + ">" + escapedText + "</color>";
        }

        private string EscapeRichText(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return string.Empty;
            }

            return text
                .Replace("<", "&lt;")
                .Replace(">", "&gt;");
        }

        private void AppendSectionIfAny(
            StringBuilder stringBuilder,
            string headerText,
            List<string> importantItems,
            List<string> normalItems)
        {
            var hasImportantItems = importantItems != null && importantItems.Count > 0;
            var hasNormalItems = normalItems != null && normalItems.Count > 0;

            if (!hasImportantItems && !hasNormalItems)
            {
                return;
            }

            if (stringBuilder.Length > 0)
            {
                stringBuilder.AppendLine();
                stringBuilder.AppendLine();
            }

            stringBuilder.AppendLine(headerText);

            if (hasImportantItems)
            {
                for (var itemIndex = 0; itemIndex < importantItems.Count; itemIndex++)
                {
                    stringBuilder.Append("• ");
                    stringBuilder.AppendLine(importantItems[itemIndex]);
                }
            }

            if (hasNormalItems)
            {
                for (var itemIndex = 0; itemIndex < normalItems.Count; itemIndex++)
                {
                    stringBuilder.Append("• ");
                    stringBuilder.AppendLine(normalItems[itemIndex]);
                }
            }
        }

        private void ShowToDoListDisplay()
        {
            _toDoListDisplayPrefab.SetActive(true);
        }

        private void HideToDoListDisplay()
        {
            _toDoListDisplayPrefab.SetActive(false);
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey