// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Text;
using System.Collections.Generic;
using NaughtyAttributes;
using UnityEngine;

namespace Runtime.Tooling
{
    public class ToolRouter : PearlBehaviour
    {
        [SerializeField]
        private List<BaseTool> _tools;

        private string _cachedPromptForTools = null;

        public string PromptForTools
        {
            get
            {
                if (_cachedPromptForTools == null)
                {
                    return "No tools are currently available. If no tool is needed, set toolName to \"None\" and toolPayload to {}.";
                }

                return _cachedPromptForTools;
            }
        }

        public void Initialize()
        {
            BuildPromptForTools();
            foreach (var tool in _tools)
            {
                tool.Initialize();
            }
            SetInitialized();
        }

        [Button("Test Build and Log Prompt For Tools")]
        private void TestBuildAndLogPromptForTools()
        {
            Log("Testing building the prompt for tools...");
            BuildPromptForTools();
            Log("This is the prompt for tools\n\n"+PromptForTools);
        }

        private void BuildPromptForTools()
        {
            var stringBuilder = new StringBuilder(2048);

            stringBuilder.Append(GlobalManager.I.Configuration.GlobalPromptConfiguration.ToolingUsageInstructions);
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Available tool names:");

            if (_tools == null || _tools.Count == 0)
            {
                stringBuilder.AppendLine("- None");
                _cachedPromptForTools = stringBuilder.ToString().Trim();
                return;
            }

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(tool.ToolName))
                {
                    continue;
                }

                stringBuilder.AppendLine("- " + tool.ToolName);
            }

            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Tool details:");

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(tool.ToolName))
                {
                    continue;
                }

                stringBuilder.AppendLine("Tool: " + tool.ToolName);

                if (!string.IsNullOrWhiteSpace(tool.DescriptionForPrompt))
                {
                    stringBuilder.AppendLine("Purpose: " + tool.DescriptionForPrompt.Trim());
                }

                if (!string.IsNullOrWhiteSpace(tool.JsonPayloadExampleForPrompt))
                {
                    stringBuilder.AppendLine("Example toolPayload:");
                    stringBuilder.AppendLine(tool.JsonPayloadExampleForPrompt.Trim());
                }
                else
                {
                    stringBuilder.AppendLine("Example toolPayload:");
                    stringBuilder.AppendLine("{}");
                }

                stringBuilder.AppendLine();
            }

            stringBuilder.AppendLine("When no tool is needed, return:");
            stringBuilder.AppendLine("\"toolName\": \"None\"");
            stringBuilder.AppendLine("\"toolPayload\": {}");

            _cachedPromptForTools = stringBuilder.ToString().Trim();
        }
        
        public bool TryExecuteTool(string toolName, string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (string.IsNullOrWhiteSpace(toolName))
            {
                executionSummary = "Tool name was empty.";
                return false;
            }

            if (_tools == null || _tools.Count == 0)
            {
                executionSummary = "No tools are registered.";
                return false;
            }

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (!string.Equals(tool.ToolName, toolName, StringComparison.Ordinal))
                {
                    continue;
                }

                return tool.TryExecute(payloadJson, out executionSummary);
            }

            executionSummary = "No registered tool matched toolName: " + toolName;
            return false;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey