// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Text;
using NaughtyAttributes;
using UnityEngine;

namespace Runtime.Tooling
{
    public class ToolRouter : PearlBehaviour
    {
        [SerializeField]
        private List<BaseTool> _tools;

        private string _cachedPromptForTools = null;

        public string PromptForTools
        {
            get
            {
                if (_cachedPromptForTools == null)
                {
                    return "No tools are currently available. If no tools are needed, return \"toolCalls\": [].";
                }

                return _cachedPromptForTools;
            }
        }

        public void Initialize()
        {
            BuildPromptForTools();

            if (_tools != null)
            {
                for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
                {
                    var tool = _tools[toolIndex];

                    if (tool == null)
                    {
                        continue;
                    }

                    tool.Initialize();
                }
            }

            SetInitialized();
        }

        [Button("Test Build and Log Prompt For Tools")]
        private void TestBuildAndLogPromptForTools()
        {
            Log("Testing building the prompt for tools...");
            BuildPromptForTools();
            Log("This is the prompt for tools\n\n" + PromptForTools);
        }

        private void BuildPromptForTools()
        {
            var stringBuilder = new StringBuilder(4096);

            stringBuilder.Append(GlobalManager.I.Configuration.GlobalPromptConfiguration.ToolingUsageInstructions);
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Available tool names:");

            if (_tools == null || _tools.Count == 0)
            {
                stringBuilder.AppendLine("- None");
                _cachedPromptForTools = stringBuilder.ToString().Trim();
                return;
            }

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(tool.ToolName))
                {
                    continue;
                }

                stringBuilder.AppendLine("- " + tool.ToolName);
            }

            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Tool details:");

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(tool.ToolName))
                {
                    continue;
                }

                stringBuilder.AppendLine("Tool: " + tool.ToolName);
                stringBuilder.AppendLine("Priority: " + tool.ToolPriority);

                if (!string.IsNullOrWhiteSpace(tool.DescriptionForPrompt))
                {
                    stringBuilder.AppendLine("Purpose: " + tool.DescriptionForPrompt.Trim());
                }

                if (!string.IsNullOrWhiteSpace(tool.JsonPayloadExampleForPrompt))
                {
                    stringBuilder.AppendLine("Example toolPayload:");
                    stringBuilder.AppendLine(tool.JsonPayloadExampleForPrompt.Trim());
                }
                else
                {
                    stringBuilder.AppendLine("Example toolPayload:");
                    stringBuilder.AppendLine("{}");
                }

                stringBuilder.AppendLine();
            }

            stringBuilder.AppendLine("When no tools are needed, return:");
            stringBuilder.AppendLine("\"toolCalls\": []");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("When one tool is needed, return:");
            stringBuilder.AppendLine("\"toolCalls\": [");
            stringBuilder.AppendLine("  {");
            stringBuilder.AppendLine("    \"toolName\": \"SomeToolName\",");
            stringBuilder.AppendLine("    \"toolPayload\": {}");
            stringBuilder.AppendLine("  }");
            stringBuilder.AppendLine("]");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("When multiple tools are needed, return them in \"toolCalls\" as an array of tool call objects.");

            _cachedPromptForTools = stringBuilder.ToString().Trim();
        }

        public int GetToolPriorityOrMaxValue(string toolName)
        {
            if (string.IsNullOrWhiteSpace(toolName))
            {
                return int.MaxValue;
            }

            if (_tools == null || _tools.Count == 0)
            {
                return int.MaxValue;
            }

            var bestPriority = int.MaxValue;

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (!string.Equals(tool.ToolName, toolName, StringComparison.Ordinal))
                {
                    continue;
                }

                if (tool.ToolPriority < bestPriority)
                {
                    bestPriority = tool.ToolPriority;
                }
            }

            return bestPriority;
        }
        
        public bool TryExecuteTool(string toolName, string payloadJson, out string executionSummary)
        {
            executionSummary = null;

            if (string.IsNullOrWhiteSpace(toolName))
            {
                executionSummary = "Tool name was empty.";
                return false;
            }

            if (_tools == null || _tools.Count == 0)
            {
                executionSummary = "No tools are registered.";
                return false;
            }

            BaseTool bestMatchingTool = null;

            for (var toolIndex = 0; toolIndex < _tools.Count; toolIndex++)
            {
                var tool = _tools[toolIndex];

                if (tool == null)
                {
                    continue;
                }

                if (!string.Equals(tool.ToolName, toolName, StringComparison.Ordinal))
                {
                    continue;
                }

                if (bestMatchingTool == null || tool.ToolPriority < bestMatchingTool.ToolPriority)
                {
                    bestMatchingTool = tool;
                }
            }

            if (bestMatchingTool == null)
            {
                executionSummary = "No registered tool matched toolName: " + toolName;
                return false;
            }

            return bestMatchingTool.TryExecute(payloadJson, out executionSummary);
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey