// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System.Collections;
using System.Diagnostics;
using System.IO;
using TMPro;
using UnityEngine;
#if UNITY_EDITOR
using UnityEditor;
#endif

namespace Runtime.Tooling
{
    public class UpdateTool : BaseTool
    {
        [SerializeField]
        private GameObject _updateToolIndicatorPrefab;

        [SerializeField]
        private TMP_Text _updateToolIndicatorText;

        [SerializeField]
        [TextArea]
        private string _updateScriptAbsolutePath = "/Users/your-mac-username/UnityProjects/Ritsuko/UpdateService/UpdateRitsuko.sh";

        [SerializeField]
        private int _updateCountdownSeconds = 15;

        private bool _isUpdateInProgress;

        public override void Initialize()
        {
            if (_updateToolIndicatorPrefab != null)
            {
                _updateToolIndicatorPrefab.SetActive(false);
            }

            if (_updateToolIndicatorText != null)
            {
                _updateToolIndicatorText.text = string.Empty;
            }

#if UNITY_STANDALONE_OSX || UNITY_EDITOR_OSX
            if (string.IsNullOrWhiteSpace(_updateScriptAbsolutePath))
            {
                LogError("UpdateTool: Update script path is empty.");
            }
            else if (!File.Exists(_updateScriptAbsolutePath))
            {
                LogError($"UpdateTool: Update script does not exist at path: {_updateScriptAbsolutePath}");
            }
#endif
        }

        public override bool TryExecute(string payloadJson, out string executionSummary)
        {
            if (_isUpdateInProgress)
            {
                executionSummary = "Update already in progress.";
                return true;
            }

            StartUpdateCountdown();
            executionSummary = "Updating. See you soon!";
            return true;
        }

        private void StartUpdateCountdown()
        {
            StartCoroutine(UpdateCountdownCoroutine());
        }

        private IEnumerator UpdateCountdownCoroutine()
        {
            _isUpdateInProgress = true;

            if (_updateToolIndicatorPrefab != null)
            {
                _updateToolIndicatorPrefab.SetActive(true);
            }

            for (var remainingSeconds = _updateCountdownSeconds; remainingSeconds >= 0; remainingSeconds--)
            {
                if (_updateToolIndicatorText != null)
                {
                    _updateToolIndicatorText.text = $"Updating in {remainingSeconds} seconds...";
                }

                if (remainingSeconds == 5)
                {
                    TriggerExternalUpdateScriptOrSimulation();
                }

                if (remainingSeconds == 0)
                {
                    yield return new WaitForSeconds(1.0f);
                    QuitApplicationOrExitPlayMode();
                    yield break;
                }

                yield return new WaitForSeconds(1.0f);
            }
        }

        private void TriggerExternalUpdateScriptOrSimulation()
        {
#if UNITY_STANDALONE_WIN || UNITY_EDITOR_WIN
            LogError("UpdateTool: Simulating update script call on Windows.");
#elif UNITY_STANDALONE_OSX || UNITY_EDITOR_OSX
            TryLaunchMacUpdateScript();
#else
            LogError($"UpdateTool: Unsupported platform for update flow: {Application.platform}");
#endif
        }

        private void TryLaunchMacUpdateScript()
        {
            if (string.IsNullOrWhiteSpace(_updateScriptAbsolutePath))
            {
                LogError("UpdateTool: Cannot launch update script because the path is empty.");
                return;
            }

            if (!File.Exists(_updateScriptAbsolutePath))
            {
                LogError($"UpdateTool: Cannot launch update script because it does not exist: {_updateScriptAbsolutePath}");
                return;
            }

            try
            {
                var processStartInfo = new ProcessStartInfo
                {
                    FileName = "open",
                    Arguments = $"-a Terminal \"{_updateScriptAbsolutePath}\"",
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                Process.Start(processStartInfo);
                Log("UpdateTool: Requested Terminal to open update script.");
            }
            catch (System.Exception exception)
            {
                LogError($"UpdateTool: Failed to launch update script in Terminal. Exception: {exception}");
            }
        }

        private void QuitApplicationOrExitPlayMode()
        {
#if UNITY_EDITOR
            EditorApplication.isPlaying = false;
#else
            Application.Quit();
#endif
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey
//doop