// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using NaughtyAttributes;
using UnityEngine;
namespace Runtime.Inputs.SpeechToText
{
    public class MicrophoneInputController : PearlBehaviour
    {
        public enum SpeechActivityState
        {
            Inactive,
            TalkingNow,
            WaitingForEndTimeout
        }


        public int MicrophoneLoopLengthSeconds => GlobalManager.I.Configuration.MicrophoneLoopLengthSeconds;

        public int RecordingSampleRate => GlobalManager.I.Configuration.RecordingSampleRate;

        public float SpeechAmplitudeThreshold => GlobalManager.I.Configuration.SpeechAmplitudeThreshold;

        public float SpeechEndTimeoutSeconds => GlobalManager.I.Configuration.SpeechEndDetectionSeconds;
        public int AmplitudeSampleWindowSizePerChannel => GlobalManager.I.Configuration.AmplitudeSampleWindowSizePerChannel;


        private bool _autoStartOnAwake = true;

        [Header("Runtime Debug")]
        [SerializeField] [ReadOnly] private bool _isMicrophoneRunning;

        [SerializeField] [ReadOnly] private string _activeMicrophoneDeviceName;
        [SerializeField] [ReadOnly] private int _currentSamplePositionPerChannel;
        [SerializeField] [ReadOnly] private long _totalSamplesCapturedPerChannel;
        [SerializeField] [ReadOnly] private float _currentRmsAmplitude;
        [SerializeField] [ReadOnly] private float _currentPeakAmplitude;
        [SerializeField] [ReadOnly] private bool _isTalkingNow;
        [SerializeField] [ReadOnly] private bool _isWaitingForEndTimeout;
        [SerializeField] [ReadOnly] private float _secondsSinceLastDetectedSpeech;
        [SerializeField] [ReadOnly] private SpeechActivityState _currentSpeechActivityState = SpeechActivityState.Inactive;

        private string[] _availableMicrophoneDeviceNames = Array.Empty<string>();
        private AudioClip _microphoneAudioClip;
        private float[] _microphoneSampleRingBuffer = Array.Empty<float>();
        private int _ringBufferWriteIndex;
        private long _totalSampleValuesWritten;
        private int _lastObservedSamplePositionPerChannel = -1;
        private float _lastDetectedSpeechTimeSeconds = -9999.0f;

        public bool IsMicrophoneRunning => _isMicrophoneRunning;
        public string ActiveMicrophoneDeviceName => _activeMicrophoneDeviceName;
        public int ChannelCount => _microphoneAudioClip != null ? _microphoneAudioClip.channels : 1;
        public int CurrentSamplePositionPerChannel => _currentSamplePositionPerChannel;
        public long TotalSamplesCapturedPerChannel => _totalSamplesCapturedPerChannel;
        public long TotalSampleValuesCaptured => _totalSampleValuesWritten;
        public float CurrentRmsAmplitude => _currentRmsAmplitude;
        public float CurrentPeakAmplitude => _currentPeakAmplitude;
        public bool IsTalkingNow => _isTalkingNow;
        public bool IsWaitingForEndTimeout => _isWaitingForEndTimeout;
        public float SecondsSinceLastDetectedSpeech => _secondsSinceLastDetectedSpeech;
        public SpeechActivityState CurrentSpeechActivityState => _currentSpeechActivityState;
        public int RingBufferSampleValueCapacity => _microphoneSampleRingBuffer != null ? _microphoneSampleRingBuffer.Length : 0;


        [Button("Start Continuous Microphone")]
        public bool StartContinuousMicrophone()
        {
            if (_isMicrophoneRunning)
            {
                LogWarning("[MicrophoneInputController] Microphone is already running.");
                return true;
            }
            
            _activeMicrophoneDeviceName = Microphone.devices[0];
            
            if(_activeMicrophoneDeviceName == null)
            {
                LogError("[MicrophoneInputController] No microphone devices found.");
                return false;
            }

            _microphoneAudioClip = Microphone.Start(_activeMicrophoneDeviceName, true, MicrophoneLoopLengthSeconds, RecordingSampleRate);

            if (_microphoneAudioClip == null)
            {
                LogError("[MicrophoneInputController] Failed to start continuous microphone recording.");
                CleanupMicrophoneState();
                return false;
            }

            var channelCount = _microphoneAudioClip.channels;
            var ringBufferSampleValueCapacity = MicrophoneLoopLengthSeconds * RecordingSampleRate * channelCount;
            _microphoneSampleRingBuffer = new float[ringBufferSampleValueCapacity];
            _ringBufferWriteIndex = 0;
            _totalSampleValuesWritten = 0;
            _lastObservedSamplePositionPerChannel = 0;
            _currentSamplePositionPerChannel = 0;
            _totalSamplesCapturedPerChannel = 0;
            _currentRmsAmplitude = 0.0f;
            _currentPeakAmplitude = 0.0f;
            _isTalkingNow = false;
            _isWaitingForEndTimeout = false;
            _secondsSinceLastDetectedSpeech = 9999.0f;
            _currentSpeechActivityState = SpeechActivityState.Inactive;
            _lastDetectedSpeechTimeSeconds = -9999.0f;
            _isMicrophoneRunning = true;


            var microphoneLabel = string.IsNullOrWhiteSpace(_activeMicrophoneDeviceName) ? "<default microphone>" : _activeMicrophoneDeviceName;
            Log("[MicrophoneInputController] Started continuous microphone recording on: " + microphoneLabel);


            return true;
        }

        [Button("Stop Continuous Microphone")]
        public void StopContinuousMicrophone()
        {
            if (!_isMicrophoneRunning)
            {
                LogWarning("[MicrophoneInputController] Microphone is not running.");
                return;
            }

            Microphone.End(_activeMicrophoneDeviceName);


            Log("[MicrophoneInputController] Stopped continuous microphone recording.");


            CleanupMicrophoneState();
        }

        public bool TryGetMostRecentSampleValues(int requestedSampleValueCount, out float[] sampleValues)
        {
            sampleValues = null;

            if (!_isMicrophoneRunning)
            {
                return false;
            }

            if (requestedSampleValueCount <= 0)
            {
                return false;
            }

            var availableSampleValueCount = (int)Mathf.Min(_totalSampleValuesWritten, _microphoneSampleRingBuffer.Length);

            if (availableSampleValueCount <= 0)
            {
                return false;
            }

            var clampedRequestedSampleValueCount = Mathf.Min(requestedSampleValueCount, availableSampleValueCount);
            sampleValues = new float[clampedRequestedSampleValueCount];

            var startIndex = _ringBufferWriteIndex - clampedRequestedSampleValueCount;

            if (startIndex < 0)
            {
                startIndex += _microphoneSampleRingBuffer.Length;
            }

            for (var sampleIndex = 0; sampleIndex < clampedRequestedSampleValueCount; sampleIndex++)
            {
                var sourceIndex = (startIndex + sampleIndex) % _microphoneSampleRingBuffer.Length;
                sampleValues[sampleIndex] = _microphoneSampleRingBuffer[sourceIndex];
            }

            return true;
        }

        public void SetSpeechActivityStateToActive()
        {
            _lastDetectedSpeechTimeSeconds = Time.unscaledTime;
            _isWaitingForEndTimeout = false;
            _currentSpeechActivityState = SpeechActivityState.TalkingNow;
        }

        public bool TryGetLatestAudioClip(float durationSeconds, string clipName, out AudioClip audioClip)
        {
            audioClip = null;

            if (!_isMicrophoneRunning)
            {
                return false;
            }

            if (_microphoneAudioClip == null)
            {
                return false;
            }

            if (durationSeconds <= 0.0f)
            {
                return false;
            }

            var channelCount = _microphoneAudioClip.channels;
            var requestedSamplesPerChannel = Mathf.CeilToInt(durationSeconds * RecordingSampleRate);
            var requestedSampleValueCount = requestedSamplesPerChannel * channelCount;

            if (!TryGetMostRecentSampleValues(requestedSampleValueCount, out var sampleValues))
            {
                return false;
            }

            var actualSamplesPerChannel = sampleValues.Length / channelCount;

            if (actualSamplesPerChannel <= 0)
            {
                return false;
            }

            audioClip = AudioClip.Create(clipName, actualSamplesPerChannel, channelCount, RecordingSampleRate, false);
            audioClip.SetData(sampleValues, 0);
            return true;
        }

        public AudioClip CreateAudioClipFromRecentSampleValues(long startSampleValueIndexInclusive, long endSampleValueIndexExclusive, string clipName)
        {
            if (!_isMicrophoneRunning)
            {
                return null;
            }

            if (_microphoneAudioClip == null)
            {
                return null;
            }

            if (endSampleValueIndexExclusive <= startSampleValueIndexInclusive)
            {
                return null;
            }

            var earliestAvailableSampleValueIndex = Math.Max(0, _totalSampleValuesWritten - _microphoneSampleRingBuffer.Length);
            var clampedStartSampleValueIndex = Math.Max(startSampleValueIndexInclusive, earliestAvailableSampleValueIndex);
            var clampedEndSampleValueIndex = Math.Min(endSampleValueIndexExclusive, _totalSampleValuesWritten);

            if (clampedEndSampleValueIndex <= clampedStartSampleValueIndex)
            {
                return null;
            }

            var sampleValueCount = (int)(clampedEndSampleValueIndex - clampedStartSampleValueIndex);
            var sampleValues = new float[sampleValueCount];

            for (var sampleIndex = 0; sampleIndex < sampleValueCount; sampleIndex++)
            {
                var absoluteSampleValueIndex = clampedStartSampleValueIndex + sampleIndex;
                var ringIndex = (int)(absoluteSampleValueIndex % _microphoneSampleRingBuffer.Length);
                sampleValues[sampleIndex] = _microphoneSampleRingBuffer[ringIndex];
            }

            var channelCount = _microphoneAudioClip.channels;
            var samplesPerChannel = sampleValueCount / channelCount;

            if (samplesPerChannel <= 0)
            {
                return null;
            }

            var audioClip = AudioClip.Create(clipName, samplesPerChannel, channelCount, RecordingSampleRate, false);
            audioClip.SetData(sampleValues, 0);
            return audioClip;
        }

        public void Initialize()
        {
            if (_autoStartOnAwake)
            {
                StartContinuousMicrophone();
            }

            SetInitialized();
        }

        private void Update()
        {
            if (!_isMicrophoneRunning)
            {
                _currentRmsAmplitude = 0.0f;
                _currentPeakAmplitude = 0.0f;
                _currentSamplePositionPerChannel = 0;
                _isTalkingNow = false;
                _isWaitingForEndTimeout = false;
                _secondsSinceLastDetectedSpeech = 9999.0f;
                _currentSpeechActivityState = SpeechActivityState.Inactive;
                return;
            }

            PumpNewMicrophoneSamplesIntoRingBuffer();
            UpdateSpeechDetectionState();
        }

        private void PumpNewMicrophoneSamplesIntoRingBuffer()
        {
            if (_microphoneAudioClip == null)
            {
                return;
            }

            var currentSamplePositionPerChannel = Microphone.GetPosition(_activeMicrophoneDeviceName);

            if (currentSamplePositionPerChannel < 0)
            {
                return;
            }

            _currentSamplePositionPerChannel = currentSamplePositionPerChannel;

            if (_lastObservedSamplePositionPerChannel < 0)
            {
                _lastObservedSamplePositionPerChannel = currentSamplePositionPerChannel;
                return;
            }

            if (currentSamplePositionPerChannel == _lastObservedSamplePositionPerChannel)
            {
                return;
            }

            var channelCount = _microphoneAudioClip.channels;
            var totalNewSamplesPerChannel = 0;

            if (currentSamplePositionPerChannel > _lastObservedSamplePositionPerChannel)
            {
                totalNewSamplesPerChannel = currentSamplePositionPerChannel - _lastObservedSamplePositionPerChannel;
                CopyMicrophoneClipRangeIntoRingBuffer(_lastObservedSamplePositionPerChannel, totalNewSamplesPerChannel, channelCount);
            }
            else
            {
                var samplesUntilLoopEndPerChannel = _microphoneAudioClip.samples - _lastObservedSamplePositionPerChannel;

                if (samplesUntilLoopEndPerChannel > 0)
                {
                    CopyMicrophoneClipRangeIntoRingBuffer(_lastObservedSamplePositionPerChannel, samplesUntilLoopEndPerChannel, channelCount);
                }

                if (currentSamplePositionPerChannel > 0)
                {
                    CopyMicrophoneClipRangeIntoRingBuffer(0, currentSamplePositionPerChannel, channelCount);
                }

                totalNewSamplesPerChannel = samplesUntilLoopEndPerChannel + currentSamplePositionPerChannel;
            }

            _lastObservedSamplePositionPerChannel = currentSamplePositionPerChannel;
            _totalSamplesCapturedPerChannel += totalNewSamplesPerChannel;
        }

        private void CopyMicrophoneClipRangeIntoRingBuffer(int startSamplePerChannel, int sampleCountPerChannel, int channelCount)
        {
            if (sampleCountPerChannel <= 0)
            {
                return;
            }

            var sampleValueCount = sampleCountPerChannel * channelCount;
            var sampleValues = new float[sampleValueCount];
            _microphoneAudioClip.GetData(sampleValues, startSamplePerChannel);

            for (var sampleIndex = 0; sampleIndex < sampleValues.Length; sampleIndex++)
            {
                _microphoneSampleRingBuffer[_ringBufferWriteIndex] = sampleValues[sampleIndex];
                _ringBufferWriteIndex = (_ringBufferWriteIndex + 1) % _microphoneSampleRingBuffer.Length;
                _totalSampleValuesWritten++;
            }
        }

        private void UpdateSpeechDetectionState()
        {
            var channelCount = ChannelCount;
            var amplitudeSampleValueCount = AmplitudeSampleWindowSizePerChannel * channelCount;

            if (!TryGetMostRecentSampleValues(amplitudeSampleValueCount, out var recentSampleValues))
            {
                _currentRmsAmplitude = 0.0f;
                _currentPeakAmplitude = 0.0f;
                _isTalkingNow = false;
                _isWaitingForEndTimeout = false;
                _secondsSinceLastDetectedSpeech = 9999.0f;
                _currentSpeechActivityState = SpeechActivityState.Inactive;
                return;
            }

            _currentRmsAmplitude = CalculateRmsAmplitude(recentSampleValues);
            _currentPeakAmplitude = CalculatePeakAmplitude(recentSampleValues);
            _isTalkingNow = _currentRmsAmplitude >= SpeechAmplitudeThreshold;

            if (_isTalkingNow)
            {
                _lastDetectedSpeechTimeSeconds = Time.unscaledTime;
            }

            _secondsSinceLastDetectedSpeech = Time.unscaledTime - _lastDetectedSpeechTimeSeconds;

            if (_isTalkingNow)
            {
                _isWaitingForEndTimeout = false;
                _currentSpeechActivityState = SpeechActivityState.TalkingNow;
                return;
            }

            if (_secondsSinceLastDetectedSpeech <= SpeechEndTimeoutSeconds)
            {
                _isWaitingForEndTimeout = true;
                _currentSpeechActivityState = SpeechActivityState.WaitingForEndTimeout;
                return;
            }

            _isWaitingForEndTimeout = false;
            _currentSpeechActivityState = SpeechActivityState.Inactive;
        }

        private float CalculateRmsAmplitude(float[] sampleValues)
        {
            if (sampleValues == null || sampleValues.Length == 0)
            {
                return 0.0f;
            }

            var sumOfSquares = 0.0f;

            for (var sampleIndex = 0; sampleIndex < sampleValues.Length; sampleIndex++)
            {
                var sampleValue = sampleValues[sampleIndex];
                sumOfSquares += sampleValue * sampleValue;
            }

            return Mathf.Sqrt(sumOfSquares / sampleValues.Length);
        }

        private float CalculatePeakAmplitude(float[] sampleValues)
        {
            if (sampleValues == null || sampleValues.Length == 0)
            {
                return 0.0f;
            }

            var peakAmplitude = 0.0f;

            for (var sampleIndex = 0; sampleIndex < sampleValues.Length; sampleIndex++)
            {
                var absoluteAmplitude = Mathf.Abs(sampleValues[sampleIndex]);

                if (absoluteAmplitude > peakAmplitude)
                {
                    peakAmplitude = absoluteAmplitude;
                }
            }

            return peakAmplitude;
        }

        private void CleanupMicrophoneState()
        {
            _microphoneAudioClip = null;
            _microphoneSampleRingBuffer = Array.Empty<float>();
            _ringBufferWriteIndex = 0;
            _totalSampleValuesWritten = 0;
            _lastObservedSamplePositionPerChannel = -1;
            _activeMicrophoneDeviceName = null;
            _isMicrophoneRunning = false;
            _currentSamplePositionPerChannel = 0;
            _totalSamplesCapturedPerChannel = 0;
            _currentRmsAmplitude = 0.0f;
            _currentPeakAmplitude = 0.0f;
            _isTalkingNow = false;
            _isWaitingForEndTimeout = false;
            _secondsSinceLastDetectedSpeech = 9999.0f;
            _currentSpeechActivityState = SpeechActivityState.Inactive;
            _lastDetectedSpeechTimeSeconds = -9999.0f;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey