// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using NaughtyAttributes;
using Runtime.Reasoning.DataTypes;
using UnityEngine;
using UnityEngine.Networking;
namespace Runtime.Inputs.SpeechToText
{
    public class OpenAISpeechToText : PearlBehaviour
    {

        private string OpenAIApiKey => Secrets.OpenAIApiKey;

        private string TranscriptionModelName => GlobalManager.I.Configuration.SttModelName;

        [Header("Listening")]
        [SerializeField] private GameObject _isListeningIndicator;

        private float PreRollSeconds => GlobalManager.I.Configuration.SttPrerollSeconds;

        [Header("Debug")]
        [SerializeField] [ReadOnly] private bool _isListening;

        [SerializeField] [ReadOnly] private bool _isTranscriptionInProgress;
        [SerializeField] [ReadOnly] private long _captureStartSampleValueIndex;
        [SerializeField] [ReadOnly] private long _captureEndSampleValueIndex;

        private MicrophoneInputController MicrophoneInputController => GlobalManager.I.MicrophoneInputController;

        private void Start()
        {
            _isListeningIndicator?.SetActive(false);
            SetInitialized();
        }

        [Button("StartListening")]
        public void StartListening()
        {
            if (_isListening)
            {
                LogWarning("[OpenAISpeechToText] Already listening.");
                return;
            }

            if (_isTranscriptionInProgress)
            {
                LogWarning("[OpenAISpeechToText] Cannot start listening while transcription is in progress.");
                return;
            }

            if (MicrophoneInputController == null)
            {
                LogError("[OpenAISpeechToText] MicrophoneInputController reference is missing.");
                return;
            }

            if (!MicrophoneInputController.IsMicrophoneRunning)
            {
                LogError("[OpenAISpeechToText] MicrophoneInputController is not running.");
                return;
            }

            var preRollSampleValueCount = Mathf.RoundToInt(PreRollSeconds * MicrophoneInputController.RecordingSampleRate * MicrophoneInputController.ChannelCount);
            _captureStartSampleValueIndex = Math.Max(0, MicrophoneInputController.TotalSampleValuesCaptured - preRollSampleValueCount);
            _captureEndSampleValueIndex = _captureStartSampleValueIndex;
            _isListening = true;

            _isListeningIndicator?.SetActive(true);

            Log("[OpenAISpeechToText] Listening started.");
        }

        public void Update()
        {
            if (_isListening && MicrophoneInputController.CurrentSpeechActivityState == MicrophoneInputController.SpeechActivityState.Inactive)
            {
                StopListeningAndSend();
            }
        }

        [Button("StopListeningAndSend")]
        public void StopListeningAndSend()
        {
            if (!_isListening)
            {
                LogWarning("[OpenAISpeechToText] Not currently listening.");
                return;
            }

            if (MicrophoneInputController == null)
            {
                LogError("[OpenAISpeechToText] MicrophoneInputController reference is missing.");
                CleanupListeningState();
                return;
            }

            _captureEndSampleValueIndex = MicrophoneInputController.TotalSampleValuesCaptured;
            var trimmedAudioClip = MicrophoneInputController.CreateAudioClipFromRecentSampleValues(
                _captureStartSampleValueIndex,
                _captureEndSampleValueIndex,
                "microphone_recording");

            CleanupListeningState();

            if (trimmedAudioClip == null)
            {
                LogWarning("[OpenAISpeechToText] No trimmed audio clip was created.");
                return;
            }

            StartCoroutine(TranscribeAudioClipCoroutine(trimmedAudioClip, "microphone_recording.wav"));
        }

        private IEnumerator TranscribeAudioClipCoroutine(AudioClip audioClip, string fileName)
        {
            if (_isTranscriptionInProgress)
            {
                LogWarning("[OpenAISpeechToText] Transcription is already in progress.");
                yield break;
            }

            _isTranscriptionInProgress = true;

            if (string.IsNullOrWhiteSpace(OpenAIApiKey))
            {
                LogError("[OpenAISpeechToText] OpenAI API key is missing.");
                _isTranscriptionInProgress = false;
                yield break;
            }

            if (audioClip == null)
            {
                LogError("[OpenAISpeechToText] AudioClip is null.");
                _isTranscriptionInProgress = false;
                yield break;
            }

            var wavBytes = ConvertAudioClipToWavBytes(audioClip);

            if (wavBytes == null || wavBytes.Length == 0)
            {
                LogError("[OpenAISpeechToText] WAV conversion failed.");
                _isTranscriptionInProgress = false;
                yield break;
            }

            var formSections = new List<IMultipartFormSection>();
            formSections.Add(new MultipartFormFileSection("file", wavBytes, fileName, "audio/wav"));
            formSections.Add(new MultipartFormDataSection("model", TranscriptionModelName));

            using (var unityWebRequest = UnityWebRequest.Post("https://api.openai.com/v1/audio/transcriptions", formSections))
            {
                unityWebRequest.SetRequestHeader("Authorization", "Bearer " + OpenAIApiKey);

                yield return unityWebRequest.SendWebRequest();

                if (unityWebRequest.result != UnityWebRequest.Result.Success)
                {
                    LogError("[OpenAISpeechToText] Transcription request failed: " + unityWebRequest.error);
                    LogError("[OpenAISpeechToText] Response body: " + unityWebRequest.downloadHandler.text);
                    _isTranscriptionInProgress = false;
                    yield break;
                }

                var rawResponseText = unityWebRequest.downloadHandler.text;


                Log("[OpenAISpeechToText] Raw transcription response: " + rawResponseText);


                var transcriptionResponse = JsonUtility.FromJson<OpenAITranscriptionResponse>(rawResponseText);

                if (transcriptionResponse == null)
                {
                    LogError("[OpenAISpeechToText] Failed to parse transcription response.");
                    _isTranscriptionInProgress = false;
                    yield break;
                }
                else
                {
                    GlobalManager.I.QueryHandler.HandleNewMessage(transcriptionResponse.text, QuerySource.Speech);
                }

                Log("[OpenAISpeechToText] Transcript: " + transcriptionResponse.text);
            }

            _isTranscriptionInProgress = false;
        }

        private byte[] ConvertAudioClipToWavBytes(AudioClip audioClip)
        {
            var sampleCount = audioClip.samples * audioClip.channels;
            var sampleData = new float[sampleCount];
            audioClip.GetData(sampleData, 0);

            var pcm16Bytes = ConvertFloatSamplesToPcm16Bytes(sampleData);

            using (var memoryStream = new MemoryStream())
            using (var binaryWriter = new BinaryWriter(memoryStream))
            {
                var channelCount = audioClip.channels;
                var sampleRate = audioClip.frequency;
                var bitsPerSample = 16;
                var byteRate = sampleRate * channelCount * bitsPerSample / 8;
                var blockAlign = channelCount * bitsPerSample / 8;
                var subChunkTwoSize = pcm16Bytes.Length;
                var chunkSize = 36 + subChunkTwoSize;

                binaryWriter.Write(new[]
                {
                    'R',
                    'I',
                    'F',
                    'F'
                });
                binaryWriter.Write(chunkSize);
                binaryWriter.Write(new[]
                {
                    'W',
                    'A',
                    'V',
                    'E'
                });

                binaryWriter.Write(new[]
                {
                    'f',
                    'm',
                    't',
                    ' '
                });
                binaryWriter.Write(16);
                binaryWriter.Write((short)1);
                binaryWriter.Write((short)channelCount);
                binaryWriter.Write(sampleRate);
                binaryWriter.Write(byteRate);
                binaryWriter.Write((short)blockAlign);
                binaryWriter.Write((short)bitsPerSample);

                binaryWriter.Write(new[]
                {
                    'd',
                    'a',
                    't',
                    'a'
                });
                binaryWriter.Write(subChunkTwoSize);
                binaryWriter.Write(pcm16Bytes);

                binaryWriter.Flush();
                return memoryStream.ToArray();
            }
        }

        private byte[] ConvertFloatSamplesToPcm16Bytes(float[] sampleData)
        {
            var pcm16Bytes = new byte[sampleData.Length * 2];
            var pcm16ByteIndex = 0;

            for (var sampleIndex = 0; sampleIndex < sampleData.Length; sampleIndex++)
            {
                var clampedSample = Mathf.Clamp(sampleData[sampleIndex], -1.0f, 1.0f);
                var pcm16Sample = (short)(clampedSample * short.MaxValue);

                var sampleBytes = BitConverter.GetBytes(pcm16Sample);
                pcm16Bytes[pcm16ByteIndex] = sampleBytes[0];
                pcm16Bytes[pcm16ByteIndex + 1] = sampleBytes[1];
                pcm16ByteIndex += 2;
            }

            return pcm16Bytes;
        }

        private void CleanupListeningState()
        {
            _isListening = false;
            _captureStartSampleValueIndex = 0;
            _captureEndSampleValueIndex = 0;
            _isListeningIndicator?.SetActive(false);
        }

        [Serializable]
        private class OpenAITranscriptionResponse
        {
            public string text;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey