// Generated by ChatGPT and Riko Balakit / Pearl Grey

using System.Collections;
using System.Text;
using UnityEngine;
using UnityEngine.Networking;
using NaughtyAttributes;

public class AzureTtsUnityPlayer : MonoBehaviour
{
    [Header("Azure Settings")]
    [SerializeField] private string _azureRegion = "eastus";

    [Header("Speech")]
    [TextArea(3, 10)]
    [SerializeField] private string _textToSpeak = "What's on your to-do list today?";

    [Header("Audio")]
    [SerializeField] private AudioSource _audioSource;

    private Coroutine _speakCoroutine;
    
    [Button("Generate and Play")]
    private void GenerateAndPlay()
    {
        if (_audioSource == null)
        {
            Debug.LogError("AudioSource is not assigned.");
            return;
        }

        StartCoroutine(GenerateAndPlayCoroutine(_textToSpeak));
    }

    public void GenerateAndPlay(string textToSpeak)
    {
        if (_speakCoroutine != null)
        {
            return;
        }
        
        _speakCoroutine = StartCoroutine(GenerateAndPlayCoroutine(textToSpeak));
    }
    
    private IEnumerator GenerateAndPlayCoroutine(string textToSpeak)
    {
        var url = $"https://{_azureRegion}.tts.speech.microsoft.com/cognitiveservices/v1";

        var ssml = BuildSsml(textToSpeak);
        var ssmlBytes = Encoding.UTF8.GetBytes(ssml);

        using var request = new UnityWebRequest(url, "POST");
        request.uploadHandler = new UploadHandlerRaw(ssmlBytes);
        request.downloadHandler = new DownloadHandlerAudioClip(url, AudioType.MPEG);

        request.SetRequestHeader("Ocp-Apim-Subscription-Key", Secrets.AZURE_TTS_API_KEY);
        request.SetRequestHeader("Content-Type", "application/ssml+xml");
        request.SetRequestHeader("X-Microsoft-OutputFormat", "audio-24khz-48kbitrate-mono-mp3");
        request.SetRequestHeader("User-Agent", "RitsukoUnity");

        yield return request.SendWebRequest();

        if (request.result != UnityWebRequest.Result.Success)
        {
            Debug.LogError($"Azure TTS Error: {request.error}");
            yield break;
        }

        var clip = DownloadHandlerAudioClip.GetContent(request);

        _audioSource.loop = false;
        _audioSource.clip = clip;
        _audioSource.Play();

        while (_audioSource.isPlaying)
        {
            yield return null;
        }

        _speakCoroutine = null;
    }

    private string BuildSsml(string text)
    {
        return
$@"<speak version=""1.0"" xml:lang=""en-US""
xmlns=""http://www.w3.org/2001/10/synthesis""
xmlns:mstts=""http://www.w3.org/2001/mstts"">
  <voice name=""en-US-PhoebeMultilingualNeural"">
    {text}
  </voice>
</speak>";
    }
}

// Generated by ChatGPT and Riko Balakit / Pearl Grey