// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Text;
using DefaultNamespace;
using NaughtyAttributes;
using UnityEngine;
using UnityEngine.Networking;
using TMPro;
using UnityEngine.Serialization;

public class DiscordClient : MonoBehaviour
{
    private const string BaseUrl = "http://127.0.0.1:5099";

    [FormerlySerializedAs("_inputRouter")]
    [Header("Dependencies")]
    [SerializeField] private QueryHandler _queryHandler;

    [Header("Testing UI")]
    [SerializeField] private string _testMessageInputField;

    [Header("Polling")]
    [SerializeField] private float _pollIntervalSeconds = 1f;

    [Header("Heartbeat")]
    [SerializeField] private float _heartbeatIntervalSeconds = 5f;

    private void Start()
    {
        Debug.Log("[DiscordClient] Starting client.");

        StartCoroutine(PollIncomingMessagesCoroutine());
        StartCoroutine(HeartbeatCoroutine());
    }

    // =========================
    // HEARTBEAT
    // =========================

    private IEnumerator HeartbeatCoroutine()
    {
        while (true)
        {
            using (var request = new UnityWebRequest(BaseUrl + "/heartbeat", "POST"))
            {
                request.uploadHandler = new UploadHandlerRaw(Array.Empty<byte>());
                request.downloadHandler = new DownloadHandlerBuffer();
                request.SetRequestHeader("Content-Type", "application/json");

                yield return request.SendWebRequest();

                if (request.result != UnityWebRequest.Result.Success)
                {
                    Debug.LogWarning("[DiscordClient] Heartbeat failed: " + request.error);
                }
            }

            yield return new WaitForSeconds(_heartbeatIntervalSeconds);
        }
    }

    // =========================
    // POLL INCOMING MESSAGES
    // =========================

    private IEnumerator PollIncomingMessagesCoroutine()
    {
        while (true)
        {
            using (var request = UnityWebRequest.Get(BaseUrl + "/poll-incoming"))
            {
                yield return request.SendWebRequest();

                if (request.result != UnityWebRequest.Result.Success)
                {
                    Debug.LogWarning("[DiscordClient] Poll failed: " + request.error);
                }
                else
                {
                    HandleIncomingMessages(request.downloadHandler.text);
                }
            }

            yield return new WaitForSeconds(_pollIntervalSeconds);
        }
    }

    private void HandleIncomingMessages(string json)
    {
        if (string.IsNullOrWhiteSpace(json) || json == "[]")
        {
            return;
        }

        var wrappedJson = "{\"Messages\":" + json + "}";

        try
        {
            var response = JsonUtility.FromJson<IncomingDiscordMessageListWrapper>(wrappedJson);

            if (response?.Messages == null)
            {
                return;
            }

            foreach (var message in response.Messages)
            {
                Debug.Log($"[DiscordClient] DM from {message.username}: {message.messageText}");

                if (_queryHandler != null)
                {
                    _queryHandler.HandleNewMessage(message.messageText);
                }
                else
                {
                    Debug.LogWarning("[DiscordClient] No InputRouter assigned.");
                }
            }
        }
        catch (Exception exception)
        {
            Debug.LogError("[DiscordClient] JSON parse error: " + exception);
            Debug.LogError("[DiscordClient] Raw JSON: " + json);
        }
    }

    // =========================
    // SEND DM
    // =========================

    [Button("Send Test Message")]
    public void SendTestMessageFromInput()
    {
        if (_testMessageInputField == null)
        {
            Debug.LogWarning("[DiscordClient] No input field assigned.");
            return;
        }

        var message = _testMessageInputField;

        if (string.IsNullOrWhiteSpace(message))
        {
            Debug.LogWarning("[DiscordClient] Refusing to send empty message.");
            return;
        }

        SendDirectMessage(message);
    }

    public void SendDirectMessage(string messageText)
    {
        StartCoroutine(SendDirectMessageCoroutine(messageText));
    }

    private IEnumerator SendDirectMessageCoroutine(string messageText)
    {
        var requestBody = new SendDirectMessageRequest
        {
            userId = Secrets.USER_ID_PEARLGREY,
            messageText = messageText
        };

        var json = JsonUtility.ToJson(requestBody);
        var bodyRaw = Encoding.UTF8.GetBytes(json);

        using (var request = new UnityWebRequest(BaseUrl + "/send-dm", "POST"))
        {
            request.uploadHandler = new UploadHandlerRaw(bodyRaw);
            request.downloadHandler = new DownloadHandlerBuffer();

            request.SetRequestHeader("Content-Type", "application/json");

            yield return request.SendWebRequest();

            if (request.result != UnityWebRequest.Result.Success)
            {
                Debug.LogWarning("[DiscordClient] Send DM failed: " + request.error);
            }
            else
            {
                Debug.Log("[DiscordClient] DM sent successfully.");
            }
        }
    }

    // =========================
    // DATA STRUCTURES
    // =========================

    [Serializable]
    private class IncomingDiscordMessage
    {
        [FormerlySerializedAs("UserId")]
        public ulong userId;
        [FormerlySerializedAs("Username")]
        public string username;
        [FormerlySerializedAs("MessageText")]
        public string messageText;
        [FormerlySerializedAs("ReceivedUtcIso8601")]
        public string receivedUtcIso8601;
    }

    [Serializable]
    private class IncomingDiscordMessageListWrapper
    {
        public IncomingDiscordMessage[] Messages;
    }

    [Serializable]
    private class SendDirectMessageRequest
    {
        [FormerlySerializedAs("UserId")]
        public ulong userId;
        [FormerlySerializedAs("MessageText")]
        public string messageText;
    }
}

// End Generated by ChatGPT and Riko Balakit/Pearl Grey