// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using DefaultNamespace;
using Discord;
using Discord.WebSocket;
using UnityEngine;

public class DiscordClient : MonoBehaviour
{
    private DiscordSocketClient _client;
    private readonly ConcurrentQueue<SocketMessage> _incomingDirectMessages = new ConcurrentQueue<SocketMessage>();
    private bool _isConnected;

    [SerializeField]
    private InputRouter _inputRouter;
    
    [SerializeField]
    private bool _logMessagesFromPearl = false;

    private async void Start()
    {
        await StartDiscordClient();
    }

    private async Task StartDiscordClient()
    {
        _client = new DiscordSocketClient();

        _client.Log += OnDiscordLog;
        _client.MessageReceived += OnMessageReceived;
        _client.Connected += OnConnected;
        _client.Disconnected += OnDisconnected;

        await _client.LoginAsync(TokenType.Bot, Secrets.DISCORD_BOT_API_KEY);
        await _client.StartAsync();
    }

    private void Update()
    {
        while (_incomingDirectMessages.TryDequeue(out var message))
        {
            if (message.Author.Id != Secrets.USER_ID_PEARLGREY)
            {
                Debug.LogError($"[Discord] DM from {message.Author.Username} ({message.Author.Id}): {message.Content}");
            }
            else
            {
                if (_logMessagesFromPearl)
                {
                    Debug.Log($"[Discord] DM from Pearl: {message.Content}");
                }
                if (_inputRouter != null)
                {
                    _inputRouter.HandleNewMessage(message.Content);
                }
                else
                {
                    Debug.LogWarning("[Discord] No InputRouter assigned to handle incoming messages.");
                }
            }
        }
    }

    private async void OnDestroy()
    {
        await StopDiscordClient();
    }

    private async Task StopDiscordClient()
    {
        if (_client == null)
        {
            return;
        }

        try
        {
            _client.Log -= OnDiscordLog;
            _client.MessageReceived -= OnMessageReceived;
            _client.Connected -= OnConnected;
            _client.Disconnected -= OnDisconnected;

            if (_isConnected)
            {
                await _client.StopAsync();
                await _client.LogoutAsync();
            }
        }
        catch (Exception exception)
        {
            Debug.LogWarning("[Discord] Exception while stopping client: " + exception);
        }
        finally
        {
            _client.Dispose();
            _client = null;
            _isConnected = false;
        }
    }

    private Task OnDiscordLog(LogMessage logMessage)
    {
        Debug.Log("[Discord] " + logMessage.Severity + " | " + logMessage.Source + " | " + logMessage.Message);

        if (logMessage.Exception != null)
        {
            Debug.LogError("[Discord] Exception: " + logMessage.Exception);
        }

        return Task.CompletedTask;
    }

    private Task OnConnected()
    {
        _isConnected = true;
        Debug.Log("[Discord] Connected.");
        return Task.CompletedTask;
    }

    private Task OnDisconnected(Exception exception)
    {
        _isConnected = false;

        if (exception != null)
        {
            Debug.LogWarning("[Discord] Disconnected with exception: " + exception);
        }
        else
        {
            Debug.Log("[Discord] Disconnected.");
        }

        return Task.CompletedTask;
    }

    private Task OnMessageReceived(SocketMessage message)
    {
        if (message == null)
        {
            return Task.CompletedTask;
        }

        if (message.Author == null || message.Author.IsBot)
        {
            return Task.CompletedTask;
        }

        if (message.Channel is IDMChannel)
        {
            _incomingDirectMessages.Enqueue(message);
        }

        return Task.CompletedTask;
    }

    public async Task SendDirectMessageAsync(ulong userId, string messageText)
    {
        if (!_isConnected)
        {
            Debug.LogWarning("[Discord] Cannot send DM because client is not connected.");
            return;
        }

        if (string.IsNullOrWhiteSpace(messageText))
        {
            Debug.LogWarning("[Discord] Refusing to send empty DM.");
            return;
        }

        IUser user = _client.GetUser(userId);

        if (user == null)
        {
            user = await _client.Rest.GetUserAsync(userId);
        }

        if (user == null)
        {
            Debug.LogWarning("[Discord] Could not find user with ID " + userId);
            return;
        }

        await user.SendMessageAsync(messageText);
        Debug.Log($"[Discord] Sent DM to {user.Username} ({user.Id}): {messageText}");
    }
}

// End Generated by ChatGPT and Riko Balakit/Pearl Grey