// Generated by ChatGPT and Riko Balakit / Pearl Grey

using System;
using System.Collections;
using System.Text;
using UnityEngine;
using UnityEngine.Networking;
using Newtonsoft.Json;

public class ElevenLabsTtsUnityPlayer : BaseTtsUnityPlayer
{
    [Header("ElevenLabs Settings")]
    [SerializeField] private string _voiceId = "EXAVITQu4vr4xnSDxMaL"; // default example voice

    [Header("Voice Options")]
    [SerializeField] private string _modelId = "eleven_flash_v2";

    protected override IEnumerator GenerateAudioClipCoroutine(
        string textToSpeak,
        Action<AudioClip> onSuccess)
    {
        var url = $"https://api.elevenlabs.io/v1/text-to-speech/{_voiceId}/stream";

        var payload = new ElevenLabsRequest
        {
            text = textToSpeak,
            model_id = _modelId
        };

        var json = JsonConvert.SerializeObject(payload);
        var jsonBytes = Encoding.UTF8.GetBytes(json);

        using var request = new UnityWebRequest(url, UnityWebRequest.kHttpVerbPOST);

        request.uploadHandler = new UploadHandlerRaw(jsonBytes);
        request.downloadHandler = new DownloadHandlerAudioClip(url, AudioType.MPEG);

        request.SetRequestHeader("Content-Type", "application/json");
        request.SetRequestHeader("xi-api-key", Secrets.ELEVENLABS_API_KEY);

        yield return request.SendWebRequest();

        if (request.result != UnityWebRequest.Result.Success)
        {
            Debug.LogError($"ElevenLabs TTS Error: {request.error}");
            onSuccess?.Invoke(null);
            yield break;
        }

        var clip = DownloadHandlerAudioClip.GetContent(request);

        if (clip == null)
        {
            Debug.LogError("ElevenLabs returned null AudioClip.");
            onSuccess?.Invoke(null);
            yield break;
        }

        onSuccess?.Invoke(clip);
    }

    private class ElevenLabsRequest
    {
        public string text;
        public string model_id;
    }
}

// Generated by ChatGPT and Riko Balakit / Pearl Grey