// Generated by ChatGPT and Riko Balakit/Pearl Grey

using UnityEngine;
using UnityEngine.SceneManagement;

public class EscapeKeyController : MonoBehaviour
{
    [SerializeField] private float _quitHoldDurationSeconds = 3f;

    private float _escapeKeyHeldTimeSeconds;
    private bool _escapeKeyIsHeld;

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            _escapeKeyIsHeld = true;
            _escapeKeyHeldTimeSeconds = 0f;
        }

        if (_escapeKeyIsHeld)
        {
            _escapeKeyHeldTimeSeconds += Time.deltaTime;

            if (_escapeKeyHeldTimeSeconds >= _quitHoldDurationSeconds)
            {
                QuitApplication();
            }
        }

        if (Input.GetKeyUp(KeyCode.Escape))
        {
            if (_escapeKeyHeldTimeSeconds < _quitHoldDurationSeconds)
            {
                ReloadScene();
            }

            _escapeKeyIsHeld = false;
        }
    }

    private void ReloadScene()
    {
        var currentScene = SceneManager.GetActiveScene();
        SceneManager.LoadScene(currentScene.name);
    }

    private void QuitApplication()
    {
#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey