// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using NaughtyAttributes;
using UnityEngine;

public class MicrophoneInputController : MonoBehaviour
{
    public enum SpeechActivityState
    {
        Inactive,
        TalkingNow,
        WaitingForEndTimeout
    }

    [Header("Microphone Device")]
    [SerializeField] private bool _useDefaultMicrophoneDevice = true;

    [ShowIf(nameof(ShouldShowSelectedMicrophoneDropdown))]
    [Dropdown(nameof(GetAvailableMicrophoneDeviceDropdown))]
    [SerializeField] private string _selectedMicrophoneDeviceName;

    [Header("Continuous Capture Settings")]
    [SerializeField] private int _microphoneLoopLengthSeconds = 300;
    [SerializeField] private int _recordingSampleRate = 16000;

    [Header("Speech Detection")]
    [SerializeField] private float _speechAmplitudeThreshold = 0.01f;
    [SerializeField] private float _speechEndTimeoutSeconds = 5.0f;
    [SerializeField] private int _amplitudeSampleWindowSizePerChannel = 1024;

    [Header("Debug")]
    [SerializeField] private bool _logMicrophoneEvents = true;
    [SerializeField] private bool _autoStartOnAwake = true;

    [Header("Runtime Debug")]
    [SerializeField] [ReadOnly] private bool _isMicrophoneRunning;
    [SerializeField] [ReadOnly] private string _activeMicrophoneDeviceName;
    [SerializeField] [ReadOnly] private int _currentSamplePositionPerChannel;
    [SerializeField] [ReadOnly] private long _totalSamplesCapturedPerChannel;
    [SerializeField] [ReadOnly] private float _currentRmsAmplitude;
    [SerializeField] [ReadOnly] private float _currentPeakAmplitude;
    [SerializeField] [ReadOnly] private bool _isTalkingNow;
    [SerializeField] [ReadOnly] private bool _isWaitingForEndTimeout;
    [SerializeField] [ReadOnly] private float _secondsSinceLastDetectedSpeech;
    [SerializeField] [ReadOnly] private SpeechActivityState _currentSpeechActivityState = SpeechActivityState.Inactive;

    private string[] _availableMicrophoneDeviceNames = Array.Empty<string>();
    private AudioClip _microphoneAudioClip;
    private float[] _microphoneSampleRingBuffer = Array.Empty<float>();
    private int _ringBufferWriteIndex;
    private long _totalSampleValuesWritten;
    private int _lastObservedSamplePositionPerChannel = -1;
    private float _lastDetectedSpeechTimeSeconds = -9999.0f;

    public bool IsMicrophoneRunning => _isMicrophoneRunning;
    public string ActiveMicrophoneDeviceName => _activeMicrophoneDeviceName;
    public int RecordingSampleRate => _recordingSampleRate;
    public int ChannelCount => _microphoneAudioClip != null ? _microphoneAudioClip.channels : 1;
    public int CurrentSamplePositionPerChannel => _currentSamplePositionPerChannel;
    public long TotalSamplesCapturedPerChannel => _totalSamplesCapturedPerChannel;
    public long TotalSampleValuesCaptured => _totalSampleValuesWritten;
    public float CurrentRmsAmplitude => _currentRmsAmplitude;
    public float CurrentPeakAmplitude => _currentPeakAmplitude;
    public bool IsTalkingNow => _isTalkingNow;
    public bool IsWaitingForEndTimeout => _isWaitingForEndTimeout;
    public float SecondsSinceLastDetectedSpeech => _secondsSinceLastDetectedSpeech;
    public SpeechActivityState CurrentSpeechActivityState => _currentSpeechActivityState;
    public int RingBufferSampleValueCapacity => _microphoneSampleRingBuffer != null ? _microphoneSampleRingBuffer.Length : 0;

    [Button("Refresh Microphone List")]
    public void RefreshMicrophoneList()
    {
        CacheAvailableMicrophoneDeviceNames();

        if (_logMicrophoneEvents)
        {
            Debug.Log("[MicrophoneInputController] Refreshed microphone list. Found " + _availableMicrophoneDeviceNames.Length + " microphone(s).");

            for (var microphoneIndex = 0; microphoneIndex < _availableMicrophoneDeviceNames.Length; microphoneIndex++)
            {
                Debug.Log("[MicrophoneInputController] Microphone " + microphoneIndex + ": " + _availableMicrophoneDeviceNames[microphoneIndex]);
            }
        }
    }

    [Button("Start Continuous Microphone")]
    public bool StartContinuousMicrophone()
    {
        if (_isMicrophoneRunning)
        {
            Debug.LogWarning("[MicrophoneInputController] Microphone is already running.");
            return true;
        }

        CacheAvailableMicrophoneDeviceNames();

        if (!HasAnyMicrophoneDevices())
        {
            Debug.LogError("[MicrophoneInputController] No microphone devices were found.");
            return false;
        }

        var microphoneDeviceNameToUse = GetMicrophoneDeviceNameToUse();

        if (!_useDefaultMicrophoneDevice && string.IsNullOrWhiteSpace(microphoneDeviceNameToUse))
        {
            Debug.LogError("[MicrophoneInputController] No microphone selected.");
            return false;
        }

        _activeMicrophoneDeviceName = microphoneDeviceNameToUse;
        _microphoneAudioClip = Microphone.Start(_activeMicrophoneDeviceName, true, _microphoneLoopLengthSeconds, _recordingSampleRate);

        if (_microphoneAudioClip == null)
        {
            Debug.LogError("[MicrophoneInputController] Failed to start continuous microphone recording.");
            CleanupMicrophoneState();
            return false;
        }

        var channelCount = _microphoneAudioClip.channels;
        var ringBufferSampleValueCapacity = _microphoneLoopLengthSeconds * _recordingSampleRate * channelCount;
        _microphoneSampleRingBuffer = new float[ringBufferSampleValueCapacity];
        _ringBufferWriteIndex = 0;
        _totalSampleValuesWritten = 0;
        _lastObservedSamplePositionPerChannel = 0;
        _currentSamplePositionPerChannel = 0;
        _totalSamplesCapturedPerChannel = 0;
        _currentRmsAmplitude = 0.0f;
        _currentPeakAmplitude = 0.0f;
        _isTalkingNow = false;
        _isWaitingForEndTimeout = false;
        _secondsSinceLastDetectedSpeech = 9999.0f;
        _currentSpeechActivityState = SpeechActivityState.Inactive;
        _lastDetectedSpeechTimeSeconds = -9999.0f;
        _isMicrophoneRunning = true;

        if (_logMicrophoneEvents)
        {
            var microphoneLabel = string.IsNullOrWhiteSpace(_activeMicrophoneDeviceName) ? "<default microphone>" : _activeMicrophoneDeviceName;
            Debug.Log("[MicrophoneInputController] Started continuous microphone recording on: " + microphoneLabel);
        }

        return true;
    }

    [Button("Stop Continuous Microphone")]
    public void StopContinuousMicrophone()
    {
        if (!_isMicrophoneRunning)
        {
            Debug.LogWarning("[MicrophoneInputController] Microphone is not running.");
            return;
        }

        Microphone.End(_activeMicrophoneDeviceName);

        if (_logMicrophoneEvents)
        {
            Debug.Log("[MicrophoneInputController] Stopped continuous microphone recording.");
        }

        CleanupMicrophoneState();
    }

    public bool TryGetMostRecentSampleValues(int requestedSampleValueCount, out float[] sampleValues)
    {
        sampleValues = null;

        if (!_isMicrophoneRunning)
        {
            return false;
        }

        if (requestedSampleValueCount <= 0)
        {
            return false;
        }

        var availableSampleValueCount = (int)Mathf.Min(_totalSampleValuesWritten, _microphoneSampleRingBuffer.Length);

        if (availableSampleValueCount <= 0)
        {
            return false;
        }

        var clampedRequestedSampleValueCount = Mathf.Min(requestedSampleValueCount, availableSampleValueCount);
        sampleValues = new float[clampedRequestedSampleValueCount];

        var startIndex = _ringBufferWriteIndex - clampedRequestedSampleValueCount;

        if (startIndex < 0)
        {
            startIndex += _microphoneSampleRingBuffer.Length;
        }

        for (var sampleIndex = 0; sampleIndex < clampedRequestedSampleValueCount; sampleIndex++)
        {
            var sourceIndex = (startIndex + sampleIndex) % _microphoneSampleRingBuffer.Length;
            sampleValues[sampleIndex] = _microphoneSampleRingBuffer[sourceIndex];
        }

        return true;
    }
    
    public void SetSpeechActivityStateToActive()
    {
        _lastDetectedSpeechTimeSeconds = Time.unscaledTime;
        _isWaitingForEndTimeout = false;
        _currentSpeechActivityState = SpeechActivityState.TalkingNow;
    }

    public bool TryGetLatestAudioClip(float durationSeconds, string clipName, out AudioClip audioClip)
    {
        audioClip = null;

        if (!_isMicrophoneRunning)
        {
            return false;
        }

        if (_microphoneAudioClip == null)
        {
            return false;
        }

        if (durationSeconds <= 0.0f)
        {
            return false;
        }

        var channelCount = _microphoneAudioClip.channels;
        var requestedSamplesPerChannel = Mathf.CeilToInt(durationSeconds * _recordingSampleRate);
        var requestedSampleValueCount = requestedSamplesPerChannel * channelCount;

        if (!TryGetMostRecentSampleValues(requestedSampleValueCount, out var sampleValues))
        {
            return false;
        }

        var actualSamplesPerChannel = sampleValues.Length / channelCount;

        if (actualSamplesPerChannel <= 0)
        {
            return false;
        }

        audioClip = AudioClip.Create(clipName, actualSamplesPerChannel, channelCount, _recordingSampleRate, false);
        audioClip.SetData(sampleValues, 0);
        return true;
    }

    public AudioClip CreateAudioClipFromRecentSampleValues(long startSampleValueIndexInclusive, long endSampleValueIndexExclusive, string clipName)
    {
        if (!_isMicrophoneRunning)
        {
            return null;
        }

        if (_microphoneAudioClip == null)
        {
            return null;
        }

        if (endSampleValueIndexExclusive <= startSampleValueIndexInclusive)
        {
            return null;
        }

        var earliestAvailableSampleValueIndex = Math.Max(0, _totalSampleValuesWritten - _microphoneSampleRingBuffer.Length);
        var clampedStartSampleValueIndex = Math.Max(startSampleValueIndexInclusive, earliestAvailableSampleValueIndex);
        var clampedEndSampleValueIndex = Math.Min(endSampleValueIndexExclusive, _totalSampleValuesWritten);

        if (clampedEndSampleValueIndex <= clampedStartSampleValueIndex)
        {
            return null;
        }

        var sampleValueCount = (int)(clampedEndSampleValueIndex - clampedStartSampleValueIndex);
        var sampleValues = new float[sampleValueCount];

        for (var sampleIndex = 0; sampleIndex < sampleValueCount; sampleIndex++)
        {
            var absoluteSampleValueIndex = clampedStartSampleValueIndex + sampleIndex;
            var ringIndex = (int)(absoluteSampleValueIndex % _microphoneSampleRingBuffer.Length);
            sampleValues[sampleIndex] = _microphoneSampleRingBuffer[ringIndex];
        }

        var channelCount = _microphoneAudioClip.channels;
        var samplesPerChannel = sampleValueCount / channelCount;

        if (samplesPerChannel <= 0)
        {
            return null;
        }

        var audioClip = AudioClip.Create(clipName, samplesPerChannel, channelCount, _recordingSampleRate, false);
        audioClip.SetData(sampleValues, 0);
        return audioClip;
    }

    private void Awake()
    {
        CacheAvailableMicrophoneDeviceNames();

        if (_autoStartOnAwake)
        {
            StartContinuousMicrophone();
        }
    }

    private void OnValidate()
    {
        CacheAvailableMicrophoneDeviceNames();

        if (_microphoneLoopLengthSeconds < 1)
        {
            _microphoneLoopLengthSeconds = 1;
        }

        if (_recordingSampleRate < 8000)
        {
            _recordingSampleRate = 8000;
        }

        if (_amplitudeSampleWindowSizePerChannel < 64)
        {
            _amplitudeSampleWindowSizePerChannel = 64;
        }

        if (_speechEndTimeoutSeconds < 0.0f)
        {
            _speechEndTimeoutSeconds = 0.0f;
        }

        if (_speechAmplitudeThreshold < 0.0f)
        {
            _speechAmplitudeThreshold = 0.0f;
        }
    }

    private void Update()
    {
        if (!_isMicrophoneRunning)
        {
            _currentRmsAmplitude = 0.0f;
            _currentPeakAmplitude = 0.0f;
            _currentSamplePositionPerChannel = 0;
            _isTalkingNow = false;
            _isWaitingForEndTimeout = false;
            _secondsSinceLastDetectedSpeech = 9999.0f;
            _currentSpeechActivityState = SpeechActivityState.Inactive;
            return;
        }

        PumpNewMicrophoneSamplesIntoRingBuffer();
        UpdateSpeechDetectionState();
    }

    private void PumpNewMicrophoneSamplesIntoRingBuffer()
    {
        if (_microphoneAudioClip == null)
        {
            return;
        }

        var currentSamplePositionPerChannel = Microphone.GetPosition(_activeMicrophoneDeviceName);

        if (currentSamplePositionPerChannel < 0)
        {
            return;
        }

        _currentSamplePositionPerChannel = currentSamplePositionPerChannel;

        if (_lastObservedSamplePositionPerChannel < 0)
        {
            _lastObservedSamplePositionPerChannel = currentSamplePositionPerChannel;
            return;
        }

        if (currentSamplePositionPerChannel == _lastObservedSamplePositionPerChannel)
        {
            return;
        }

        var channelCount = _microphoneAudioClip.channels;
        var totalNewSamplesPerChannel = 0;

        if (currentSamplePositionPerChannel > _lastObservedSamplePositionPerChannel)
        {
            totalNewSamplesPerChannel = currentSamplePositionPerChannel - _lastObservedSamplePositionPerChannel;
            CopyMicrophoneClipRangeIntoRingBuffer(_lastObservedSamplePositionPerChannel, totalNewSamplesPerChannel, channelCount);
        }
        else
        {
            var samplesUntilLoopEndPerChannel = _microphoneAudioClip.samples - _lastObservedSamplePositionPerChannel;

            if (samplesUntilLoopEndPerChannel > 0)
            {
                CopyMicrophoneClipRangeIntoRingBuffer(_lastObservedSamplePositionPerChannel, samplesUntilLoopEndPerChannel, channelCount);
            }

            if (currentSamplePositionPerChannel > 0)
            {
                CopyMicrophoneClipRangeIntoRingBuffer(0, currentSamplePositionPerChannel, channelCount);
            }

            totalNewSamplesPerChannel = samplesUntilLoopEndPerChannel + currentSamplePositionPerChannel;
        }

        _lastObservedSamplePositionPerChannel = currentSamplePositionPerChannel;
        _totalSamplesCapturedPerChannel += totalNewSamplesPerChannel;
    }

    private void CopyMicrophoneClipRangeIntoRingBuffer(int startSamplePerChannel, int sampleCountPerChannel, int channelCount)
    {
        if (sampleCountPerChannel <= 0)
        {
            return;
        }

        var sampleValueCount = sampleCountPerChannel * channelCount;
        var sampleValues = new float[sampleValueCount];
        _microphoneAudioClip.GetData(sampleValues, startSamplePerChannel);

        for (var sampleIndex = 0; sampleIndex < sampleValues.Length; sampleIndex++)
        {
            _microphoneSampleRingBuffer[_ringBufferWriteIndex] = sampleValues[sampleIndex];
            _ringBufferWriteIndex = (_ringBufferWriteIndex + 1) % _microphoneSampleRingBuffer.Length;
            _totalSampleValuesWritten++;
        }
    }

    private void UpdateSpeechDetectionState()
    {
        var channelCount = ChannelCount;
        var amplitudeSampleValueCount = _amplitudeSampleWindowSizePerChannel * channelCount;

        if (!TryGetMostRecentSampleValues(amplitudeSampleValueCount, out var recentSampleValues))
        {
            _currentRmsAmplitude = 0.0f;
            _currentPeakAmplitude = 0.0f;
            _isTalkingNow = false;
            _isWaitingForEndTimeout = false;
            _secondsSinceLastDetectedSpeech = 9999.0f;
            _currentSpeechActivityState = SpeechActivityState.Inactive;
            return;
        }

        _currentRmsAmplitude = CalculateRmsAmplitude(recentSampleValues);
        _currentPeakAmplitude = CalculatePeakAmplitude(recentSampleValues);
        _isTalkingNow = _currentRmsAmplitude >= _speechAmplitudeThreshold;

        if (_isTalkingNow)
        {
            _lastDetectedSpeechTimeSeconds = Time.unscaledTime;
        }

        _secondsSinceLastDetectedSpeech = Time.unscaledTime - _lastDetectedSpeechTimeSeconds;

        if (_isTalkingNow)
        {
            _isWaitingForEndTimeout = false;
            _currentSpeechActivityState = SpeechActivityState.TalkingNow;
            return;
        }

        if (_secondsSinceLastDetectedSpeech <= _speechEndTimeoutSeconds)
        {
            _isWaitingForEndTimeout = true;
            _currentSpeechActivityState = SpeechActivityState.WaitingForEndTimeout;
            return;
        }

        _isWaitingForEndTimeout = false;
        _currentSpeechActivityState = SpeechActivityState.Inactive;
    }

    private float CalculateRmsAmplitude(float[] sampleValues)
    {
        if (sampleValues == null || sampleValues.Length == 0)
        {
            return 0.0f;
        }

        var sumOfSquares = 0.0f;

        for (var sampleIndex = 0; sampleIndex < sampleValues.Length; sampleIndex++)
        {
            var sampleValue = sampleValues[sampleIndex];
            sumOfSquares += sampleValue * sampleValue;
        }

        return Mathf.Sqrt(sumOfSquares / sampleValues.Length);
    }

    private float CalculatePeakAmplitude(float[] sampleValues)
    {
        if (sampleValues == null || sampleValues.Length == 0)
        {
            return 0.0f;
        }

        var peakAmplitude = 0.0f;

        for (var sampleIndex = 0; sampleIndex < sampleValues.Length; sampleIndex++)
        {
            var absoluteAmplitude = Mathf.Abs(sampleValues[sampleIndex]);

            if (absoluteAmplitude > peakAmplitude)
            {
                peakAmplitude = absoluteAmplitude;
            }
        }

        return peakAmplitude;
    }

    private bool ShouldShowSelectedMicrophoneDropdown()
    {
        return !_useDefaultMicrophoneDevice;
    }

    private DropdownList<string> GetAvailableMicrophoneDeviceDropdown()
    {
        CacheAvailableMicrophoneDeviceNames();

        var dropdown = new DropdownList<string>();

        if (_availableMicrophoneDeviceNames == null || _availableMicrophoneDeviceNames.Length == 0)
        {
            dropdown.Add("<No microphones found>", "");
            return dropdown;
        }

        for (var microphoneIndex = 0; microphoneIndex < _availableMicrophoneDeviceNames.Length; microphoneIndex++)
        {
            var microphoneDeviceName = _availableMicrophoneDeviceNames[microphoneIndex];
            dropdown.Add(microphoneDeviceName, microphoneDeviceName);
        }

        return dropdown;
    }

    private void CacheAvailableMicrophoneDeviceNames()
    {
        _availableMicrophoneDeviceNames = Microphone.devices ?? Array.Empty<string>();

        if (string.IsNullOrWhiteSpace(_selectedMicrophoneDeviceName) && _availableMicrophoneDeviceNames.Length > 0)
        {
            _selectedMicrophoneDeviceName = _availableMicrophoneDeviceNames[0];
        }

        if (!string.IsNullOrWhiteSpace(_selectedMicrophoneDeviceName) && Array.IndexOf(_availableMicrophoneDeviceNames, _selectedMicrophoneDeviceName) < 0)
        {
            _selectedMicrophoneDeviceName = _availableMicrophoneDeviceNames.Length > 0 ? _availableMicrophoneDeviceNames[0] : "";
        }
    }

    private bool HasAnyMicrophoneDevices()
    {
        return _availableMicrophoneDeviceNames != null && _availableMicrophoneDeviceNames.Length > 0;
    }

    private string GetMicrophoneDeviceNameToUse()
    {
        if (_useDefaultMicrophoneDevice)
        {
            return null;
        }

        return _selectedMicrophoneDeviceName;
    }

    private void CleanupMicrophoneState()
    {
        _microphoneAudioClip = null;
        _microphoneSampleRingBuffer = Array.Empty<float>();
        _ringBufferWriteIndex = 0;
        _totalSampleValuesWritten = 0;
        _lastObservedSamplePositionPerChannel = -1;
        _activeMicrophoneDeviceName = null;
        _isMicrophoneRunning = false;
        _currentSamplePositionPerChannel = 0;
        _totalSamplesCapturedPerChannel = 0;
        _currentRmsAmplitude = 0.0f;
        _currentPeakAmplitude = 0.0f;
        _isTalkingNow = false;
        _isWaitingForEndTimeout = false;
        _secondsSinceLastDetectedSpeech = 9999.0f;
        _currentSpeechActivityState = SpeechActivityState.Inactive;
        _lastDetectedSpeechTimeSeconds = -9999.0f;
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey