// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using NaughtyAttributes;
using UnityEngine;
using UnityEngine.Networking;

public class OpenAISpeechToText : MonoBehaviour
{
    [Header("OpenAI")]
    private string _openAIApiKey => Secrets.OpenAIApiKey;
    [SerializeField] private string _transcriptionModelName = "gpt-4o-transcribe";

    [Header("Microphone")]
    [SerializeField] private bool _useDefaultMicrophoneDevice = true;

    [ShowIf(nameof(ShouldShowSelectedMicrophoneDropdown))]
    [Dropdown(nameof(GetAvailableMicrophoneDeviceDropdown))]
    [SerializeField] private string _selectedMicrophoneDeviceName;

    [SerializeField] private int _recordingLengthSeconds = 120;
    [SerializeField] private int _recordingSampleRate = 16000;

    [Header("Debug")]
    [SerializeField] private bool _logVerboseResponse = true;
    [SerializeField] private GameObject _isListeningIndicator;
    
    private AudioClip _activeRecordingAudioClip;
    private string[] _availableMicrophoneDeviceNames = Array.Empty<string>();
    private string _activeMicrophoneDeviceName;
    private bool _isListening;

    [Button("Refresh Microphone List")]
    private void RefreshMicrophoneList()
    {
        CacheAvailableMicrophoneDeviceNames();
        Debug.Log("[OpenAIMicrophoneTranscriptionTester] Refreshed microphone list. Found " + _availableMicrophoneDeviceNames.Length + " microphone(s).");

        for (var microphoneIndex = 0; microphoneIndex < _availableMicrophoneDeviceNames.Length; microphoneIndex++)
        {
            Debug.Log("[OpenAIMicrophoneTranscriptionTester] Microphone " + microphoneIndex + ": " + _availableMicrophoneDeviceNames[microphoneIndex]);
        }
    }

    [Button("StartListening")]
    public void StartListening()
    {
        if (_isListening)
        {
            Debug.LogWarning("[OpenAIMicrophoneTranscriptionTester] Already listening.");
            return;
        }

        CacheAvailableMicrophoneDeviceNames();

        var microphoneDeviceNameToUse = GetMicrophoneDeviceNameToUse();

        if (!HasAnyMicrophoneDevices())
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] No microphone devices were found.");
            return;
        }

        if (!_useDefaultMicrophoneDevice && string.IsNullOrWhiteSpace(microphoneDeviceNameToUse))
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] No microphone selected.");
            return;
        }

        _activeMicrophoneDeviceName = microphoneDeviceNameToUse;
        _activeRecordingAudioClip = Microphone.Start(_activeMicrophoneDeviceName, false, _recordingLengthSeconds, _recordingSampleRate);

        if (_activeRecordingAudioClip == null)
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Failed to start microphone recording.");
            return;
        }

        _isListening = true;
        
        _isListeningIndicator?.SetActive(true);

        var microphoneLabel = string.IsNullOrWhiteSpace(_activeMicrophoneDeviceName) ? "<default microphone>" : _activeMicrophoneDeviceName;
        Debug.Log("[OpenAIMicrophoneTranscriptionTester] Started listening on microphone: " + microphoneLabel);
    }

    [Button("StopListeningAndSend")]
    public void StopListeningAndSend()
    {
        if (!_isListening)
        {
            Debug.LogWarning("[OpenAIMicrophoneTranscriptionTester] Not currently listening.");
            return;
        }

        if (_activeRecordingAudioClip == null)
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Active recording clip is null.");
            CleanupListeningState();
            return;
        }

        var currentSamplePosition = Microphone.GetPosition(_activeMicrophoneDeviceName);

        if (currentSamplePosition < 0)
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Failed to get microphone position.");
            CleanupListeningState();
            return;
        }

        Microphone.End(_activeMicrophoneDeviceName);
        _isListening = false;
        
        _isListeningIndicator?.SetActive(false);


        if (currentSamplePosition == 0)
        {
            Debug.LogWarning("[OpenAIMicrophoneTranscriptionTester] Recording contained 0 samples.");
            CleanupListeningState();
            return;
        }

        var trimmedAudioClip = CreateTrimmedAudioClip(_activeRecordingAudioClip, currentSamplePosition);

        if (trimmedAudioClip == null)
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Failed to trim recorded audio clip.");
            CleanupListeningState();
            return;
        }

        StartCoroutine(TranscribeAudioClipCoroutine(trimmedAudioClip, "microphone_recording.wav"));
        CleanupListeningState();
    }

    private void Awake()
    {
        CacheAvailableMicrophoneDeviceNames();
    }

    private void OnValidate()
    {
        CacheAvailableMicrophoneDeviceNames();
    }

    private bool ShouldShowSelectedMicrophoneDropdown()
    {
        return !_useDefaultMicrophoneDevice;
    }

    private DropdownList<string> GetAvailableMicrophoneDeviceDropdown()
    {
        CacheAvailableMicrophoneDeviceNames();

        var dropdown = new DropdownList<string>();

        if (_availableMicrophoneDeviceNames == null || _availableMicrophoneDeviceNames.Length == 0)
        {
            dropdown.Add("<No microphones found>", "");
            return dropdown;
        }

        for (var microphoneIndex = 0; microphoneIndex < _availableMicrophoneDeviceNames.Length; microphoneIndex++)
        {
            var microphoneDeviceName = _availableMicrophoneDeviceNames[microphoneIndex];
            dropdown.Add(microphoneDeviceName, microphoneDeviceName);
        }

        return dropdown;
    }

    private void CacheAvailableMicrophoneDeviceNames()
    {
        _availableMicrophoneDeviceNames = Microphone.devices ?? Array.Empty<string>();

        if (string.IsNullOrWhiteSpace(_selectedMicrophoneDeviceName) && _availableMicrophoneDeviceNames.Length > 0)
        {
            _selectedMicrophoneDeviceName = _availableMicrophoneDeviceNames[0];
        }

        if (!string.IsNullOrWhiteSpace(_selectedMicrophoneDeviceName) && Array.IndexOf(_availableMicrophoneDeviceNames, _selectedMicrophoneDeviceName) < 0)
        {
            _selectedMicrophoneDeviceName = _availableMicrophoneDeviceNames.Length > 0 ? _availableMicrophoneDeviceNames[0] : "";
        }
    }

    private bool HasAnyMicrophoneDevices()
    {
        return _availableMicrophoneDeviceNames != null && _availableMicrophoneDeviceNames.Length > 0;
    }

    private string GetMicrophoneDeviceNameToUse()
    {
        if (_useDefaultMicrophoneDevice)
        {
            return null;
        }

        return _selectedMicrophoneDeviceName;
    }

    private AudioClip CreateTrimmedAudioClip(AudioClip sourceAudioClip, int recordedSampleCountPerChannel)
    {
        if (sourceAudioClip == null)
        {
            return null;
        }

        var channelCount = sourceAudioClip.channels;
        var frequency = sourceAudioClip.frequency;
        var totalRecordedSampleValueCount = recordedSampleCountPerChannel * channelCount;

        var sourceSampleData = new float[sourceAudioClip.samples * channelCount];
        sourceAudioClip.GetData(sourceSampleData, 0);

        var trimmedSampleData = new float[totalRecordedSampleValueCount];
        Array.Copy(sourceSampleData, trimmedSampleData, totalRecordedSampleValueCount);

        var trimmedAudioClip = AudioClip.Create(
            sourceAudioClip.name + "_Trimmed",
            recordedSampleCountPerChannel,
            channelCount,
            frequency,
            false);

        trimmedAudioClip.SetData(trimmedSampleData, 0);
        return trimmedAudioClip;
    }

    private IEnumerator TranscribeAudioClipCoroutine(AudioClip audioClip, string fileName)
    {
        if (string.IsNullOrWhiteSpace(_openAIApiKey))
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] OpenAI API key is missing.");
            yield break;
        }

        if (audioClip == null)
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] AudioClip is null.");
            yield break;
        }

        var wavBytes = ConvertAudioClipToWavBytes(audioClip);

        if (wavBytes == null || wavBytes.Length == 0)
        {
            Debug.LogError("[OpenAIMicrophoneTranscriptionTester] WAV conversion failed.");
            yield break;
        }

        var formSections = new List<IMultipartFormSection>();
        formSections.Add(new MultipartFormFileSection("file", wavBytes, fileName, "audio/wav"));
        formSections.Add(new MultipartFormDataSection("model", _transcriptionModelName));

        using (var unityWebRequest = UnityWebRequest.Post("https://api.openai.com/v1/audio/transcriptions", formSections))
        {
            unityWebRequest.SetRequestHeader("Authorization", "Bearer " + _openAIApiKey);

            yield return unityWebRequest.SendWebRequest();

            if (unityWebRequest.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Transcription request failed: " + unityWebRequest.error);
                Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Response body: " + unityWebRequest.downloadHandler.text);
                yield break;
            }

            var rawResponseText = unityWebRequest.downloadHandler.text;

            if (_logVerboseResponse)
            {
                Debug.Log("[OpenAIMicrophoneTranscriptionTester] Raw transcription response: " + rawResponseText);
            }

            var transcriptionResponse = JsonUtility.FromJson<OpenAITranscriptionResponse>(rawResponseText);

            if (transcriptionResponse == null)
            {
                Debug.LogError("[OpenAIMicrophoneTranscriptionTester] Failed to parse transcription response.");
                yield break;
            }

            Debug.Log("[OpenAIMicrophoneTranscriptionTester] Transcript: " + transcriptionResponse.text);
        }
    }

    private byte[] ConvertAudioClipToWavBytes(AudioClip audioClip)
    {
        var sampleCount = audioClip.samples * audioClip.channels;
        var sampleData = new float[sampleCount];
        audioClip.GetData(sampleData, 0);

        var pcm16Bytes = ConvertFloatSamplesToPcm16Bytes(sampleData);

        using (var memoryStream = new MemoryStream())
        using (var binaryWriter = new BinaryWriter(memoryStream))
        {
            var channelCount = audioClip.channels;
            var sampleRate = audioClip.frequency;
            var bitsPerSample = 16;
            var byteRate = sampleRate * channelCount * bitsPerSample / 8;
            var blockAlign = channelCount * bitsPerSample / 8;
            var subChunkTwoSize = pcm16Bytes.Length;
            var chunkSize = 36 + subChunkTwoSize;

            binaryWriter.Write(new[] { 'R', 'I', 'F', 'F' });
            binaryWriter.Write(chunkSize);
            binaryWriter.Write(new[] { 'W', 'A', 'V', 'E' });

            binaryWriter.Write(new[] { 'f', 'm', 't', ' ' });
            binaryWriter.Write(16);
            binaryWriter.Write((short)1);
            binaryWriter.Write((short)channelCount);
            binaryWriter.Write(sampleRate);
            binaryWriter.Write(byteRate);
            binaryWriter.Write((short)blockAlign);
            binaryWriter.Write((short)bitsPerSample);

            binaryWriter.Write(new[] { 'd', 'a', 't', 'a' });
            binaryWriter.Write(subChunkTwoSize);
            binaryWriter.Write(pcm16Bytes);

            binaryWriter.Flush();
            return memoryStream.ToArray();
        }
    }

    private byte[] ConvertFloatSamplesToPcm16Bytes(float[] sampleData)
    {
        var pcm16Bytes = new byte[sampleData.Length * 2];
        var pcm16ByteIndex = 0;

        for (var sampleIndex = 0; sampleIndex < sampleData.Length; sampleIndex++)
        {
            var clampedSample = Mathf.Clamp(sampleData[sampleIndex], -1.0f, 1.0f);
            var pcm16Sample = (short)(clampedSample * short.MaxValue);

            var sampleBytes = BitConverter.GetBytes(pcm16Sample);
            pcm16Bytes[pcm16ByteIndex] = sampleBytes[0];
            pcm16Bytes[pcm16ByteIndex + 1] = sampleBytes[1];
            pcm16ByteIndex += 2;
        }

        return pcm16Bytes;
    }

    private void CleanupListeningState()
    {
        _activeRecordingAudioClip = null;
        _activeMicrophoneDeviceName = null;
        _isListening = false;
    }

    [Serializable]
    private class OpenAITranscriptionResponse
    {
        public string text;
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey