// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System.Threading.Tasks;
using NaughtyAttributes;
using UnityEngine;

public class OpenRouterInspectorChat : MonoBehaviour
{
    [Header("Client")]
    [SerializeField] private OpenRouterChatClient _client;

    [Header("Model Override (optional)")]
    [SerializeField] private bool _overrideModel;
    [SerializeField, ShowIf(nameof(_overrideModel))] private string _model = "openai/gpt-4o-mini";

    [Header("Prompt")]
    [TextArea(6, 20)]
    [SerializeField] private string _prompt;

    [Header("Reply")]
    [ReadOnly]
    [TextArea(6, 20)]
    [SerializeField] private string _reply;

    [Header("State")]
    [ReadOnly]
    [SerializeField] private bool _isWaiting;

    [Button("Send And Wait For Answer")]
    private void SendAndWaitForAnswer()
    {
        if (_isWaiting)
        {
            Debug.LogWarning("Already waiting for response.");
            return;
        }

        if (_client == null)
        {
            Debug.LogError("No OpenRouterChatClient assigned.");
            return;
        }

        _ = SendRoutine();
    }

    private async Task SendRoutine()
    {
        _isWaiting = true;
        _reply = "...waiting...";
        MarkDirty();

        try
        {
            if (_overrideModel)
            {
                _client.Model = _model;
            }

            var result = await _client.SendPromptAsync(_prompt);
            _reply = result;
        }
        catch (System.Exception e)
        {
            _reply = "ERROR:\n" + e.Message;
        }

        _isWaiting = false;
        MarkDirty();
    }

#if UNITY_EDITOR
    private void MarkDirty()
    {
        UnityEditor.EditorUtility.SetDirty(this);
    }
#else
    private void MarkDirty() {}
#endif
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey