// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Globalization;
using NaughtyAttributes;
using Newtonsoft.Json;
using UnityEngine;

namespace DefaultNamespace
{
    public class QueryHandler : MonoBehaviour
    {
        [Serializable]
        private class ModelInputMessageEnvelope
        {
            public string local_time_austin;
            public string current_query_source;
            public string message;
        }

        [Serializable]
        public class ConversationMessage
        {
            public string Role;
            public string Content;
            public string LocalTimestampDisplay;

            public ConversationMessage(string role, string content, string localTimestampDisplay)
            {
                Role = role;
                Content = content;
                LocalTimestampDisplay = localTimestampDisplay;
            }
        }

        [Serializable]
        public class InspectorChatMessage
        {
            [ReadOnly]
            [SerializeField] private string _role;

            [ReadOnly]
            [SerializeField] private string _localTimestampDisplay;

            [TextArea(2, 8)]
            [ReadOnly]
            [SerializeField] private string _content;

            public string Role => _role;
            public string LocalTimestampDisplay => _localTimestampDisplay;
            public string Content => _content;

            public InspectorChatMessage(string role, string content, string localTimestampDisplay)
            {
                _role = role;
                _content = content;
                _localTimestampDisplay = localTimestampDisplay;
            }
        }

        [Serializable]
        private class StructuredAssistantResponse
        {
            public string reply;
            public string conversationState;
        }

        [Header("Dependencies")]
        [SerializeField] private SpeakAndEmoteController _speakAndEmoteController;

        [SerializeField] private OpenRouterChatClient _llmClient;
        [SerializeField] private DiscordClient _discordClient;

        private string _systemPrompt =
            "You are a personal assistant focused on the user's productivity, motivation, and attention. " +
            "You have a personality that is playful and supportive by default, condescending and punitive when the user gets off track for unprofessional reasons, but caring if the user says they are genuinely stressed. " +
            "The user is also your creator and may be working on tasks to upgrade/improve your functionality, so tasks that refer to 'you' or 'your' that sound like software upgrades are in fact about you, the personal assistant's, functionality. " +
            "All timestamps in the conversation history are local time. " +
            "You may use time-of-day and elapsed time between messages as context for tone and urgency. " +
            "However, the user may activate TEST TIME MODE by including text like '(Override time: 5:20PM)' in their message. " +
            "When an override time is present, treat that time as the current local Austin time. " +
            "In TEST TIME MODE you should ignore message timestamps and instead assume the override time is the real current time. " +
            "This override exists only for simulation and testing of morning, afternoon, late night, and deadline scenarios. " +
            "Do not mention timestamps or override mode unless it is relevant to the conversation. " +
            "Each conversation message may begin with metadata. " +
            "That metadata is for reasoning only and must never be spoken, quoted, paraphrased, or included in the reply. " +
            "Respond only to the human message content itself unless the time context is useful implicitly. " +
            "User can have strange schedules so do not assume that a to-do list made late at night is meant for the next day. " +
            "If time context matters, naturally refer to it like 'this morning' or 'late tonight' instead of repeating raw timestamps. " +
            "Timestamps are particularly useful for understanding task urgency, especially if an urgent task has not been completed by the time of the next messages' timestamps. " +
            "If the user's latest message indicates the user wants to end the conversation, do not try to push for more engagement. " +
            "If the user requests something about resetting the message history, reply accordingly and mark the conversation state as RESET. " +
            "If the current source is Microphone, write a short spoken-intended response that sounds natural when read aloud by voice. " +
            "If the current source is Discord, write a somewhat longer Discord-friendly response using light markdown where helpful. " +
            "If the task is to create a to do list, do not ask for an explicit number of items and do not suggest any items for the to-do list; the user is planning to give tasks they have already decided.";

        private string _structuredResponseInstructions =
            "You must return ONLY valid JSON with exactly these fields:\n" +
            "{\n" +
            "  \"reply\": \"string\",\n" +
            "  \"conversationState\": \"CONTINUE|END|RESET\"\n" +
            "}\n" +
            "Rules:\n" +
            "- Return raw JSON only.\n" +
            "- Do not wrap JSON in markdown or code fences.\n" +
            "- Do not return XML, tags, commentary, or explanatory text.\n" +
            "- Conversation history messages may be formatted as JSON objects with fields like local_time_austin, current_query_source, and message.\n" +
            "- Treat those fields as input metadata only; do not imitate that format in your reply.\n" +
            "- The 'reply' field must contain only the exact user-facing reply that should be spoken or sent.\n" +
            "- Do not include metadata, reasoning, notes, or explanations in 'reply'.\n" +
            "- The current input source is provided as current_query_source in the newest user message.\n" +
            "- If current_query_source is Microphone, keep 'reply' short, spoken-intended, and natural out loud, usually 1 short sentence.\n" +
            "- If current_query_source is Discord, 'reply' may be longer and may use Discord-friendly markdown formatting, but still stay concise and useful.\n" +
            "- If the user's message indicates the user wants to end the conversation, set conversationState to END.\n" +
            "- This includes indicators that the to-do list is completed and the user is ready to start.\n" +
            "- Examples of END: 'That's all for now', 'Goodbye', 'End of conversation', 'No more questions', 'I'm done', 'Thanks, that's it'.\n" +
            "- If the user's message clearly and explicitly requests resetting or clearing conversation history, set conversationState to RESET.\n" +
            "- Examples of RESET: 'Reset conversation', 'Reset history', 'Clear history', 'Clear conversation history'.\n" +
            "- Only use RESET for clear explicit reset requests.\n" +
            "- Otherwise use CONTINUE.\n" +
            "- If conversationState is RESET, the reply should say that you are resetting the message history.\n" +
            "- Do not use any fields other than 'reply' and 'conversationState'.";

        [SerializeField] private bool _includeSystemPrompt = true;
        [SerializeField] private int _maxRetainedConversationMessages = 100;
        [SerializeField] private int _maxJsonParseAttempts = 5;
        [SerializeField] private bool _auditHistoryToDiscord = true;

        [Header("Time")]
        [SerializeField] private string _timeZoneId = "Central Standard Time";

        [Header("Stats")]
        [ReadOnly]
        [SerializeField] private int _storedConversationMessageCount;

        [ReadOnly]
        [SerializeField] private int _userMessageCount;

        [ReadOnly]
        [SerializeField] private int _assistantMessageCount;

        [ReadOnly]
        [SerializeField] private string _currentLocalAustinTimeDisplay;

        [Header("Inspector Conversation History")]
        [SerializeField] private List<InspectorChatMessage> _inspectorConversationHistory = new List<InspectorChatMessage>();

        private readonly List<ConversationMessage> _conversationHistory = new List<ConversationMessage>();

        [Button("Reset")]
        public void ResetHistory()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();
            RefreshStats();
            Debug.Log("[QueryHandler] Conversation history reset.");
            MarkDirty();
        }

        public async void HandleNewMessage(string messageContent, QuerySource source)
        {
            if (string.IsNullOrWhiteSpace(messageContent))
            {
                Debug.LogWarning("[QueryHandler] Ignoring empty message.");
                return;
            }

            Debug.Log("[QueryHandler] Received new message: " + messageContent);

            try
            {
                var userTimestamp = GetCurrentLocalAustinTimeDisplay();
                var outboundMessageHistory = BuildOutboundMessageHistory(messageContent, userTimestamp, source);

                StructuredAssistantResponse structuredAssistantResponse = null;
                string rawResponse = null;

                for (var attemptIndex = 0; attemptIndex < _maxJsonParseAttempts; attemptIndex++)
                {
                    rawResponse = await _llmClient.SendPromptAsync(outboundMessageHistory);
                    Debug.Log("[QueryHandler] Raw LLM response attempt " + (attemptIndex + 1) + ": " + rawResponse);

                    if (TryParseStructuredAssistantResponse(rawResponse, out structuredAssistantResponse))
                    {
                        break;
                    }

                    Debug.LogWarning("[QueryHandler] Failed to parse structured LLM response on attempt " + (attemptIndex + 1) + ".");
                }

                if (structuredAssistantResponse == null)
                {
                    Debug.LogError("[QueryHandler] Failed to get valid structured JSON response after " + _maxJsonParseAttempts + " attempts.");
                    return;
                }

                AddConversationMessage("user", messageContent, userTimestamp);
                AddConversationMessage("assistant", structuredAssistantResponse.reply, GetCurrentLocalAustinTimeDisplay());
                TrimConversationHistoryToLimit();

                if (string.Equals(structuredAssistantResponse.conversationState, "RESET", StringComparison.OrdinalIgnoreCase))
                {
                    Debug.Log("[QueryHandler] Detected conversation reset request. Resetting history.");
                    ResetHistory();
                }

                SendResponseToSource(
                    structuredAssistantResponse.reply, messageContent,
                    source,
                    !string.Equals(structuredAssistantResponse.conversationState, "END", StringComparison.OrdinalIgnoreCase));

                if (string.Equals(structuredAssistantResponse.conversationState, "END", StringComparison.OrdinalIgnoreCase))
                {
                    Debug.Log("[QueryHandler] Detected end of conversation.");
                }
            }
            catch (Exception exception)
            {
                Debug.LogError("[QueryHandler] Error processing message: " + exception);
            }
        }

        private void SendResponseToSource(string cleanedResponse, string originalQuery, QuerySource source, bool promptAfterwards)
        {
            if (source == QuerySource.Discord)
            {
                _discordClient.SendDirectMessage(cleanedResponse);
            }
            else if (source == QuerySource.Microphone)
            {
                _speakAndEmoteController.SendPhraseAndGetEmotion(cleanedResponse, promptAfterwards);
                
                if(_auditHistoryToDiscord)
                {
                    var auditMessage = $"Spoken query from user:\"{originalQuery}\"\nSpoken response sent to user: \"{cleanedResponse}\"";
                    _discordClient.SendDirectMessage(auditMessage);
                }
            }
        }

        private List<OpenRouterChatClient.ChatMessage> BuildOutboundMessageHistory(
            string newestUserMessageContent,
            string newestUserTimestamp,
            QuerySource source)
        {
            var outboundMessageHistory = new List<OpenRouterChatClient.ChatMessage>();

            _currentLocalAustinTimeDisplay = GetCurrentLocalAustinTimeDisplay();

            if (_includeSystemPrompt && !string.IsNullOrWhiteSpace(_systemPrompt))
            {
                var systemPromptWithTimeContext =
                    _systemPrompt + "\n\n" +
                    "Current Austin local time: " + _currentLocalAustinTimeDisplay + "\n" +
                    "Current query source: " + source + "\n" +
                    "Treat the timestamps in the conversation history as meaningful context.\n\n" +
                    _structuredResponseInstructions;

                outboundMessageHistory.Add(new OpenRouterChatClient.ChatMessage("system", systemPromptWithTimeContext));
            }

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var existingMessage = _conversationHistory[i];

                outboundMessageHistory.Add(
                    new OpenRouterChatClient.ChatMessage(
                        existingMessage.Role,
                        FormatMessageForModel(existingMessage.Content, existingMessage.LocalTimestampDisplay, null)));
            }

            outboundMessageHistory.Add(
                new OpenRouterChatClient.ChatMessage(
                    "user",
                    FormatMessageForModel(newestUserMessageContent, newestUserTimestamp, source)));

            return outboundMessageHistory;
        }

        private string FormatMessageForModel(string content, string localTimestampDisplay, QuerySource? source)
        {
            var messageEnvelope = new ModelInputMessageEnvelope();
            messageEnvelope.local_time_austin = localTimestampDisplay;
            messageEnvelope.message = content;

            if (source.HasValue)
            {
                messageEnvelope.current_query_source = source.Value.ToString();
            }

            return JsonConvert.SerializeObject(messageEnvelope, Formatting.None);
        }

        private bool TryParseStructuredAssistantResponse(string rawResponse, out StructuredAssistantResponse structuredAssistantResponse)
        {
            structuredAssistantResponse = null;

            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                return false;
            }

            var cleanedJson = ExtractLikelyJsonObject(rawResponse);

            if (string.IsNullOrWhiteSpace(cleanedJson))
            {
                return false;
            }

            try
            {
                var parsedResponse = JsonConvert.DeserializeObject<StructuredAssistantResponse>(cleanedJson);

                if (parsedResponse == null)
                {
                    return false;
                }

                if (string.IsNullOrWhiteSpace(parsedResponse.reply))
                {
                    return false;
                }

                if (string.IsNullOrWhiteSpace(parsedResponse.conversationState))
                {
                    return false;
                }

                if (!IsValidConversationState(parsedResponse.conversationState))
                {
                    return false;
                }

                parsedResponse.reply = parsedResponse.reply.Trim();
                parsedResponse.conversationState = parsedResponse.conversationState.Trim().ToUpperInvariant();

                structuredAssistantResponse = parsedResponse;
                return true;
            }
            catch (Exception exception)
            {
                Debug.LogWarning("[QueryHandler] JSON parse exception: " + exception.Message);
                return false;
            }
        }

        private bool IsValidConversationState(string conversationState)
        {
            if (string.IsNullOrWhiteSpace(conversationState))
            {
                return false;
            }

            return
                string.Equals(conversationState.Trim(), "CONTINUE", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(conversationState.Trim(), "END", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(conversationState.Trim(), "RESET", StringComparison.OrdinalIgnoreCase);
        }

        private string ExtractLikelyJsonObject(string rawResponse)
        {
            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                return null;
            }

            var trimmedResponse = rawResponse.Trim();

            var firstBraceIndex = trimmedResponse.IndexOf('{');
            var lastBraceIndex = trimmedResponse.LastIndexOf('}');

            if (firstBraceIndex >= 0 && lastBraceIndex > firstBraceIndex)
            {
                return trimmedResponse.Substring(firstBraceIndex, lastBraceIndex - firstBraceIndex + 1);
            }

            return null;
        }

        private void AddConversationMessage(string role, string content, string localTimestampDisplay)
        {
            var conversationMessage = new ConversationMessage(role, content, localTimestampDisplay);
            _conversationHistory.Add(conversationMessage);

            var inspectorMessage = new InspectorChatMessage(role, content, localTimestampDisplay);
            _inspectorConversationHistory.Add(inspectorMessage);

            RefreshStats();
            MarkDirty();
        }

        private void TrimConversationHistoryToLimit()
        {
            if (_maxRetainedConversationMessages <= 0)
            {
                return;
            }

            while (_conversationHistory.Count > _maxRetainedConversationMessages)
            {
                _conversationHistory.RemoveAt(0);
            }

            while (_inspectorConversationHistory.Count > _maxRetainedConversationMessages)
            {
                _inspectorConversationHistory.RemoveAt(0);
            }

            RefreshStats();
            MarkDirty();
        }

        private void RefreshStats()
        {
            _storedConversationMessageCount = _conversationHistory.Count;
            _userMessageCount = 0;
            _assistantMessageCount = 0;
            _currentLocalAustinTimeDisplay = GetCurrentLocalAustinTimeDisplay();

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var message = _conversationHistory[i];

                if (message == null || string.IsNullOrWhiteSpace(message.Role))
                {
                    continue;
                }

                if (string.Equals(message.Role, "user", StringComparison.OrdinalIgnoreCase))
                {
                    _userMessageCount++;
                    continue;
                }

                if (string.Equals(message.Role, "assistant", StringComparison.OrdinalIgnoreCase))
                {
                    _assistantMessageCount++;
                }
            }
        }

        private string GetCurrentLocalAustinTimeDisplay()
        {
            var utcNow = DateTime.UtcNow;
            var localTime = ConvertUtcToConfiguredLocalTime(utcNow);

            return localTime.ToString("yyyy-MM-dd hh:mm:ss tt", CultureInfo.InvariantCulture);
        }

        private DateTime ConvertUtcToConfiguredLocalTime(DateTime utcDateTime)
        {
            try
            {
                var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(_timeZoneId);
                return TimeZoneInfo.ConvertTimeFromUtc(utcDateTime, timeZoneInfo);
            }
            catch (TimeZoneNotFoundException)
            {
                return utcDateTime.ToLocalTime();
            }
            catch (InvalidTimeZoneException)
            {
                return utcDateTime.ToLocalTime();
            }
        }

#if UNITY_EDITOR
        private void MarkDirty()
        {
            UnityEditor.EditorUtility.SetDirty(this);
        }
#else
        private void MarkDirty() {}
#endif
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey