// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Text;
using NaughtyAttributes;
using Runtime.Reasoning.DataTypes;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.Serialization;

namespace Runtime.Inputs.DirectText
{
    public class DiscordClient : PearlBehaviour
    {
        private const int REQUEST_TIMEOUT_SECONDS = 5;
        private const float COROUTINE_RESTART_DELAY_SECONDS = 1.0f;

        private string DiscordSidecarBaseUrl => GlobalManager.I.Configuration.DiscordSidecarBaseUrlAndPort;

        private float _pollIntervalSeconds => GlobalManager.I.Configuration.DiscordPollIntervalSeconds;

        private float _heartbeatIntervalSeconds => GlobalManager.I.Configuration.HeartbeatIntervalSeconds;

        private void Start()
        {
            LogThreadUnsafe("[DiscordClient] Starting client.");

            StartCoroutine(RunProtectedRepeatingCoroutine(
                HeartbeatCoroutine(),
                nameof(HeartbeatCoroutine)));

            StartCoroutine(RunProtectedRepeatingCoroutine(
                PollIncomingMessagesCoroutine(),
                nameof(PollIncomingMessagesCoroutine)));

            SetInitialized();
        }

        private IEnumerator RunProtectedRepeatingCoroutine(IEnumerator repeatingCoroutine, string coroutineName)
        {
            while (true)
            {
                yield return StartCoroutine(RunCoroutineWithRestartProtection(repeatingCoroutine, coroutineName));

                LogThreadUnsafeWarning(
                    $"[DiscordClient] Repeating coroutine ended unexpectedly: {coroutineName}. Restarting in {COROUTINE_RESTART_DELAY_SECONDS} seconds.");

                yield return new WaitForSeconds(COROUTINE_RESTART_DELAY_SECONDS);

                if (coroutineName == nameof(HeartbeatCoroutine))
                {
                    repeatingCoroutine = HeartbeatCoroutine();
                }
                else if (coroutineName == nameof(PollIncomingMessagesCoroutine))
                {
                    repeatingCoroutine = PollIncomingMessagesCoroutine();
                }
                else
                {
                    LogThreadUnsafeError($"[DiscordClient] Unknown repeating coroutine name: {coroutineName}");
                    yield break;
                }
            }
        }

        private IEnumerator RunCoroutineWithRestartProtection(IEnumerator coroutineToRun, string coroutineName)
        {
            while (true)
            {
                object currentYieldInstruction = null;

                try
                {
                    if (coroutineToRun.MoveNext() == false)
                    {
                        yield break;
                    }

                    currentYieldInstruction = coroutineToRun.Current;
                }
                catch (Exception exception)
                {
                    LogThreadUnsafeError($"[DiscordClient] Coroutine crashed: {coroutineName}. Exception: {exception}");
                    yield break;
                }

                yield return currentYieldInstruction;
            }
        }

        // =========================
        // HEARTBEAT
        // =========================

        private IEnumerator HeartbeatCoroutine()
        {
            while (true)
            {
                using (var request = new UnityWebRequest(DiscordSidecarBaseUrl + "/heartbeat", "POST"))
                {
                    request.uploadHandler = new UploadHandlerRaw(Array.Empty<byte>());
                    request.downloadHandler = new DownloadHandlerBuffer();
                    request.timeout = REQUEST_TIMEOUT_SECONDS;
                    request.SetRequestHeader("Content-Type", "application/json");

                    yield return request.SendWebRequest();

                    if (request.result != UnityWebRequest.Result.Success)
                    {
                        LogThreadUnsafeWarning("[DiscordClient] Heartbeat failed: " + request.error);
                    }
                }

                yield return new WaitForSeconds(_heartbeatIntervalSeconds);
            }
        }

        // =========================
        // POLL INCOMING MESSAGES
        // =========================

        private IEnumerator PollIncomingMessagesCoroutine()
        {
            while (true)
            {
                using (var request = UnityWebRequest.Get(DiscordSidecarBaseUrl + "/poll-incoming"))
                {
                    request.timeout = REQUEST_TIMEOUT_SECONDS;

                    yield return request.SendWebRequest();

                    if (request.result != UnityWebRequest.Result.Success)
                    {
                        LogThreadUnsafeWarning("[DiscordClient] Poll failed: " + request.error);
                    }
                    else
                    {
                        HandleIncomingMessages(request.downloadHandler.text);
                    }
                }

                yield return new WaitForSeconds(_pollIntervalSeconds);
            }
        }

        private void HandleIncomingMessages(string json)
        {
            if (string.IsNullOrWhiteSpace(json) || json == "[]")
            {
                return;
            }

            var wrappedJson = "{\"Messages\":" + json + "}";

            try
            {
                var response = JsonUtility.FromJson<IncomingDiscordMessageListWrapper>(wrappedJson);

                if (response?.Messages == null)
                {
                    return;
                }

                foreach (var message in response.Messages)
                {
                    LogThreadUnsafe($"[DiscordClient] DM from {message.username}: {message.messageText}");

                    if (GlobalManager.I.QueryHandler != null)
                    {
                        GlobalManager.I.QueryHandler.HandleNewMessage(message.messageText, QuerySource.Discord);
                    }
                    else
                    {
                        LogThreadUnsafeWarning("[DiscordClient] No InputRouter assigned.");
                    }
                }
            }
            catch (Exception exception)
            {
                LogThreadUnsafeError("[DiscordClient] JSON parse error: " + exception);
                LogThreadUnsafeError("[DiscordClient] Raw JSON: " + json);
            }
        }

        // =========================
        // SEND DM
        // =========================

        public void SendDirectMessage(string messageText)
        {
            StartCoroutine(SendDirectMessageCoroutine(messageText));
        }

        private IEnumerator SendDirectMessageCoroutine(string messageText)
        {
            var requestBody = new SendDirectMessageRequest
            {
                userId = Secrets.USER_ID_PEARLGREY,
                messageText = messageText
            };

            var json = JsonUtility.ToJson(requestBody);
            var bodyRaw = Encoding.UTF8.GetBytes(json);

            using (var request = new UnityWebRequest(DiscordSidecarBaseUrl + "/send-dm", "POST"))
            {
                request.uploadHandler = new UploadHandlerRaw(bodyRaw);
                request.downloadHandler = new DownloadHandlerBuffer();
                request.timeout = REQUEST_TIMEOUT_SECONDS;

                request.SetRequestHeader("Content-Type", "application/json");

                yield return request.SendWebRequest();

                if (request.result != UnityWebRequest.Result.Success)
                {
                    LogThreadUnsafeWarning("[DiscordClient] Send DM failed: " + request.error);
                }
                else
                {
                    LogThreadUnsafe("[DiscordClient] DM sent successfully.");
                }
            }
        }

        // =========================
        // DATA STRUCTURES
        // =========================

        [Serializable]
        private class IncomingDiscordMessage
        {
            [FormerlySerializedAs("UserId")]
            public ulong userId;

            [FormerlySerializedAs("Username")]
            public string username;

            [FormerlySerializedAs("MessageText")]
            public string messageText;

            [FormerlySerializedAs("ReceivedUtcIso8601")]
            public string receivedUtcIso8601;
        }

        [Serializable]
        private class IncomingDiscordMessageListWrapper
        {
            public IncomingDiscordMessage[] Messages;
        }

        [Serializable]
        private class SendDirectMessageRequest
        {
            [FormerlySerializedAs("UserId")]
            public ulong userId;

            [FormerlySerializedAs("MessageText")]
            public string messageText;
        }
    }
}

// End Generated by ChatGPT and Riko Balakit/Pearl Grey