// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Text;
using NaughtyAttributes;
using Runtime.Reasoning.DataTypes;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.Serialization;
namespace Runtime.Inputs.DirectText
{
    public class DiscordClient : PearlBehaviour
    {
        private string DiscordSidecarBaseUrl => GlobalManager.I.Configuration.DiscordSidecarBaseUrlAndPort;

        private float _pollIntervalSeconds => GlobalManager.I.Configuration.DiscordPollIntervalSeconds;

        private float _heartbeatIntervalSeconds => GlobalManager.I.Configuration.HeartbeatIntervalSeconds;

        private void Start()
        {
            LogThreadUnsafe("[DiscordClient] Starting client.");

            StartCoroutine(PollIncomingMessagesCoroutine());
            StartCoroutine(HeartbeatCoroutine());

            SetInitialized();
        }

        // =========================
        // HEARTBEAT
        // =========================

        private IEnumerator HeartbeatCoroutine()
        {
            while (true)
            {
                using (var request = new UnityWebRequest(DiscordSidecarBaseUrl + "/heartbeat", "POST"))
                {
                    request.uploadHandler = new UploadHandlerRaw(Array.Empty<byte>());
                    request.downloadHandler = new DownloadHandlerBuffer();
                    request.SetRequestHeader("Content-Type", "application/json");

                    yield return request.SendWebRequest();

                    if (request.result != UnityWebRequest.Result.Success)
                    {
                        LogThreadUnsafeWarning("[DiscordClient] Heartbeat failed: " + request.error);
                    }
                }

                yield return new WaitForSeconds(_heartbeatIntervalSeconds);
            }
        }

        // =========================
        // POLL INCOMING MESSAGES
        // =========================

        private IEnumerator PollIncomingMessagesCoroutine()
        {
            while (true)
            {
                using (var request = UnityWebRequest.Get(DiscordSidecarBaseUrl + "/poll-incoming"))
                {
                    yield return request.SendWebRequest();

                    if (request.result != UnityWebRequest.Result.Success)
                    {
                        LogThreadUnsafeWarning("[DiscordClient] Poll failed: " + request.error);
                    }
                    else
                    {
                        HandleIncomingMessages(request.downloadHandler.text);
                    }
                }

                yield return new WaitForSeconds(_pollIntervalSeconds);
            }
        }

        private void HandleIncomingMessages(string json)
        {
            if (string.IsNullOrWhiteSpace(json) || json == "[]")
            {
                return;
            }

            var wrappedJson = "{\"Messages\":" + json + "}";

            try
            {
                var response = JsonUtility.FromJson<IncomingDiscordMessageListWrapper>(wrappedJson);

                if (response?.Messages == null)
                {
                    return;
                }

                foreach (var message in response.Messages)
                {
                    LogThreadUnsafe($"[DiscordClient] DM from {message.username}: {message.messageText}");

                    if (GlobalManager.I.QueryHandler != null)
                    {
                        GlobalManager.I.QueryHandler.HandleNewMessage(message.messageText, QuerySource.Discord);
                    }
                    else
                    {
                        LogThreadUnsafeWarning("[DiscordClient] No InputRouter assigned.");
                    }
                }
            }
            catch (Exception exception)
            {
                LogThreadUnsafeError("[DiscordClient] JSON parse error: " + exception);
                LogThreadUnsafeError("[DiscordClient] Raw JSON: " + json);
            }
        }

        // =========================
        // SEND DM
        // =========================


        public void SendDirectMessage(string messageText)
        {
            StartCoroutine(SendDirectMessageCoroutine(messageText));
        }

        private IEnumerator SendDirectMessageCoroutine(string messageText)
        {
            var requestBody = new SendDirectMessageRequest
            {
                userId = Secrets.USER_ID_PEARLGREY,
                messageText = messageText
            };

            var json = JsonUtility.ToJson(requestBody);
            var bodyRaw = Encoding.UTF8.GetBytes(json);

            using (var request = new UnityWebRequest(DiscordSidecarBaseUrl + "/send-dm", "POST"))
            {
                request.uploadHandler = new UploadHandlerRaw(bodyRaw);
                request.downloadHandler = new DownloadHandlerBuffer();

                request.SetRequestHeader("Content-Type", "application/json");

                yield return request.SendWebRequest();

                if (request.result != UnityWebRequest.Result.Success)
                {
                    LogThreadUnsafeWarning("[DiscordClient] Send DM failed: " + request.error);
                }
                else
                {
                    LogThreadUnsafe("[DiscordClient] DM sent successfully.");
                }
            }
        }

        // =========================
        // DATA STRUCTURES
        // =========================

        [Serializable]
        private class IncomingDiscordMessage
        {
            [FormerlySerializedAs("UserId")]
            public ulong userId;

            [FormerlySerializedAs("Username")]
            public string username;

            [FormerlySerializedAs("MessageText")]
            public string messageText;

            [FormerlySerializedAs("ReceivedUtcIso8601")]
            public string receivedUtcIso8601;
        }

        [Serializable]
        private class IncomingDiscordMessageListWrapper
        {
            public IncomingDiscordMessage[] Messages;
        }

        [Serializable]
        private class SendDirectMessageRequest
        {
            [FormerlySerializedAs("UserId")]
            public ulong userId;

            [FormerlySerializedAs("MessageText")]
            public string messageText;
        }
    }
}

// End Generated by ChatGPT and Riko Balakit/Pearl Grey