// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using Configuration;
using Runtime.Inputs.Presence;
using UnityEngine;

namespace Runtime
{
    [Serializable]
    public class GlobalState
    {
        private Action _onChanged;

        public void Initialize(Action onChanged)
        {
            _onChanged = onChanged;
        }

        private BehaviourMode _currentMode = BehaviourMode.ProductiveWork;

        public BehaviourMode CurrentMode
        {
            get => _currentMode;
            set
            {
                if (_currentMode == value)
                {
                    return;
                }

                _currentMode = value;
                _onChanged?.Invoke();
            }
        }

        private bool _auditModeEnabled = true;

        public bool AuditModeEnabled
        {
            get => _auditModeEnabled;
            set
            {
                if (_auditModeEnabled == value)
                {
                    return;
                }

                _auditModeEnabled = value;
                _onChanged?.Invoke();
            }
        }

        private bool _quietModeEnabled = false;

        public bool QuietModeEnabled
        {
            get => _quietModeEnabled;
            set
            {
                if (_quietModeEnabled == value)
                {
                    return;
                }

                _quietModeEnabled = value;
                _onChanged?.Invoke();
            }
        }

        private bool _respondToNameEnabled = true;

        public bool RespondToNameEnabled
        {
            get => _respondToNameEnabled;
            set
            {
                if (_respondToNameEnabled == value)
                {
                    return;
                }

                _respondToNameEnabled = value;
                _onChanged?.Invoke();
            }
        }

        private PresenceState _presenceState = PresenceState.Unknown;

        public PresenceState PresenceState
        {
            get => _presenceState;
            set
            {
                if (_presenceState == value)
                {
                    return;
                }

                _presenceState = value;
                _onChanged?.Invoke();
            }
        }
        
        private DateTime _lastTimeUserInteracted = DateTime.MinValue;

        public void SetLastTimeUserInteractedToNow()
        {
            LastTimeUserInteracted = DateTime.UtcNow;
        }
        
        public float MinutesSinceLastUserInteraction => (float)(DateTime.UtcNow - _lastTimeUserInteracted).TotalMinutes;
        public DateTime LastTimeUserInteracted
        {
            get => _lastTimeUserInteracted;
            set
            {
                if (_lastTimeUserInteracted == value)
                {
                    return;
                }

                _lastTimeUserInteracted = value;
                _onChanged?.Invoke();
            }
        }

        private List<MonoBehaviour> _longRunningTaskOwners = new List<MonoBehaviour>();
        
        public void AddLongRunningTaskOwner(MonoBehaviour owner)
        {
            if (_longRunningTaskOwners.Contains(owner))
            {
                return;
            }

            _longRunningTaskOwners.Add(owner);
            _onChanged?.Invoke();
        }
        
        public void RemoveLongRunningTaskOwner(MonoBehaviour owner)
        {
            if (!_longRunningTaskOwners.Contains(owner))
            {
                return;
            }

            _longRunningTaskOwners.Remove(owner);
            _onChanged?.Invoke();
        }
        
        public bool IsRunningLongRunningTask => _longRunningTaskOwners.Count > 0;
    }
}