// Generated by ChatGPT and Riko Balakit/Pearl Grey

using Newtonsoft.Json;
using Runtime.Avatar;
using Runtime.Behaviour;
using Runtime.Inputs.DirectText;
using Runtime.Inputs.Presence;
using Runtime.Inputs.SpeechToText;
using Runtime.Reasoning;
using Runtime.TextToSpeech;
using Runtime.Tooling;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Serialization;

namespace Runtime
{
    public class GlobalManager : PearlBehaviour
    {
        private static GlobalManager _instance;
        public static GlobalManager I => _instance;

        private const string GLOBAL_STATE_PLAYER_PREFS_KEY = "GlobalState";

        [SerializeField] private float _quitHoldDurationSeconds = 3f;

        [SerializeField] private OpenRouterChatClient _llmClient;
        public OpenRouterChatClient LlmClient => _llmClient;

        [SerializeField] private DiscordClient _discordClient;
        public DiscordClient DiscordClient => _discordClient;

        [SerializeField] private InteractiveAvatarController _avatarController;
        public InteractiveAvatarController AvatarController => _avatarController;

        [SerializeField] private SpeakAndEmoteController _speakAndEmoteController;
        public SpeakAndEmoteController SpeakAndEmoteController => _speakAndEmoteController;

        [SerializeField] private MicrophoneInputController _microphoneInputController;
        public MicrophoneInputController MicrophoneInputController => _microphoneInputController;

        [SerializeField] private BaseTtsUnityPlayer _ttsPlayer;
        public BaseTtsUnityPlayer TtsPlayer => _ttsPlayer;

        [SerializeField] private QueryHandler _queryHandler;
        public QueryHandler QueryHandler => _queryHandler;

        [SerializeField] private WakeWordSidecarClient _wakeWordSidecarClient;
        public WakeWordSidecarClient WakeWordSidecarClient => _wakeWordSidecarClient;
        
        [SerializeField] private CvPresenceTracker _cvPresenceTracker;
        public CvPresenceTracker CvPresenceTracker => _cvPresenceTracker;
        
        [SerializeField]
        private ProactiveAgencyController _proactiveAgencyController;
        
        public ProactiveAgencyController ProactiveAgencyController => _proactiveAgencyController;
        
        [SerializeField]
        private ToolRouter _toolRouter;
        
        public ToolRouter ToolRouter => _toolRouter;

        [FormerlySerializedAs("_config")]
        [FormerlySerializedAs("_constants")]
        [SerializeField]
        private Configuration.Configuration _configuration;

        public Configuration.Configuration Configuration => _configuration;

        private PromptBuilder _promptBuilder;
        public PromptBuilder PromptBuilder => _promptBuilder;
        
        

        private float _escapeKeyHeldTimeSeconds;
        private bool _escapeKeyIsHeld;
        private bool _stateIsDirty;

        public GlobalState State { get; private set; } = new GlobalState();
        public TaskState TaskState;

        private void Start()
        {
            if (_instance != null)
            {
                LogError("Multiple instances of GlobalManager detected. There should only be one GlobalManager in the scene.");
                Destroy(gameObject);
                return;
            }

            _instance = this;

            InitializeCursor();
            InitializePromptBuilder();
            LoadOrCreateGlobalState();
            CvPresenceTracker.Initialize();
            ToolRouter.Initialize();
            PromptBuilder.Initialize();
            QueryHandler.Initialize();
            ProactiveAgencyController.Initialize();
            MicrophoneInputController.Initialize();

            SetInitialized();
        }

        private void InitializePromptBuilder()
        {
            _promptBuilder = gameObject.AddComponent<PromptBuilder>();
        }

        private void InitializeCursor()
        {
#if UNITY_EDITOR
#else
            Cursor.visible = false;
            Cursor.lockState = CursorLockMode.Locked;
#endif
        }

        private void LoadOrCreateGlobalState()
        {
            if (PlayerPrefs.HasKey(GLOBAL_STATE_PLAYER_PREFS_KEY))
            {
                var json = PlayerPrefs.GetString(GLOBAL_STATE_PLAYER_PREFS_KEY);
                var loadedState = JsonConvert.DeserializeObject<GlobalState>(json);

                State = loadedState ?? new GlobalState();
                State.Initialize(MarkStateDirty);
                _stateIsDirty = false;
            }
            else
            {
                State = new GlobalState();
                State.Initialize(MarkStateDirty);
                SaveGlobalState();
            }
        }

        private void MarkStateDirty()
        {
            _stateIsDirty = true;
        }

        private void SaveGlobalState()
        {
            var json = JsonConvert.SerializeObject(State);
            PlayerPrefs.SetString(GLOBAL_STATE_PLAYER_PREFS_KEY, json);
            PlayerPrefs.Save();
            _stateIsDirty = false;
        }

        private void Update()
        {
            HandleEscapeKey();

            if (_stateIsDirty)
            {
                SaveGlobalState();
            }
        }

        private void HandleEscapeKey()
        {
            if (Input.GetKeyDown(KeyCode.Escape))
            {
                _escapeKeyIsHeld = true;
                _escapeKeyHeldTimeSeconds = 0f;
            }

            if (_escapeKeyIsHeld)
            {
                _escapeKeyHeldTimeSeconds += Time.deltaTime;

                if (_escapeKeyHeldTimeSeconds >= _quitHoldDurationSeconds)
                {
                    QuitApplication();
                }
            }

            if (Input.GetKeyUp(KeyCode.Escape))
            {
                if (_escapeKeyHeldTimeSeconds < _quitHoldDurationSeconds)
                {
                    ReloadScene();
                }

                _escapeKeyIsHeld = false;
            }
        }

        private void ReloadScene()
        {
            var currentScene = SceneManager.GetActiveScene();
            SceneManager.LoadScene(currentScene.name);
        }

        private void QuitApplication()
        {
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#else
            Application.Quit();
#endif
        }
    }
}