// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using Configuration;

namespace Runtime
{
    [Serializable]
    public class GlobalState
    {
        private Action _onChanged;

        public void Initialize(Action onChanged)
        {
            _onChanged = onChanged;
        }

        private BehaviourMode _currentMode = BehaviourMode.ProductiveWork;
        public BehaviourMode CurrentMode
        {
            get => _currentMode;
            set
            {
                if(_currentMode == value)
                {
                    return;
                }

                _currentMode = value;
                _onChanged?.Invoke();
            }
        }

        private bool _auditModeEnabled = true;
        public bool AuditModeEnabled
        {
            get => _auditModeEnabled;
            set
            {
                if(_auditModeEnabled == value)
                {
                    return;
                }

                _auditModeEnabled = value;
                _onChanged?.Invoke();
            }
        }

        private bool _quietModeEnabled = false;
        public bool QuietModeEnabled
        {
            get => _quietModeEnabled;
            set
            {
                if(_quietModeEnabled == value)
                {
                    return;
                }

                _quietModeEnabled = value;
                _onChanged?.Invoke();
            }
        }

        private bool _respondToNameEnabled = true;
        public bool RespondToNameEnabled
        {
            get => _respondToNameEnabled;
            set
            {
                if(_respondToNameEnabled == value)
                {
                    return;
                }

                _respondToNameEnabled = value;
                _onChanged?.Invoke();
            }
        }
    }
}