// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.IO.Ports;
using UnityEngine;

public class ArduinoSerialBridge : MonoBehaviour
{
    [SerializeField] private string _portName = "COM8";
    [SerializeField] private int _baudRate = 115200;
    
    [Range(0,180)]
    [SerializeField] private int _testServo1Angle = 90;
    [SerializeField] private bool _testServo1 = false;

    [Range(0,180)]
    [SerializeField] private int _testServo1AngleMin = 85;
    
    [Range(0,180)]
    [SerializeField] private int _testServo1AngleMax = 180;
    
    private SerialPort _serialPort;

    [SerializeField] public int LatestDistanceCm;
    
    [SerializeField] private AzureTtsUnityPlayer _azureTtsUnityPlayer;

    [SerializeField] private int _deltaDistanceChangeToAssumeUserPresenceCm = 5;
    
    private int _previousDistanceCm;
    private DateTime _lastTimeUserMoved;

    [SerializeField] private float _secondsUserHasntMovedToAssumeAway = 10;

    [SerializeField] private bool _userIsHere;

    [SerializeField] private string[] _userWentAwayLines;

    [SerializeField] private string[] _userCameBackLines;

    private void Start()
    {
        _serialPort = new SerialPort(_portName, _baudRate);
        _serialPort.NewLine = "\n";
        _serialPort.ReadTimeout = 1; // Non-blocking-ish

        _serialPort.Open();
    }

    private void Update()
    {
        if (_serialPort == null || !_serialPort.IsOpen)
        {
            return;
        }

        try
        {
            while (_serialPort.BytesToRead > 0)
            {
                var line = _serialPort.ReadLine();
                HandleLine(line);
            }

            if (_testServo1)
            {
                SendServoAngle(_testServo1Angle);
            }
        }
        catch (TimeoutException)
        {
            // Normal. Ignore.
        }
        
        UpdateUserDistance();
    }

    private void UpdateUserDistance()
    {
        if (Mathf.Abs(_previousDistanceCm - LatestDistanceCm) > _deltaDistanceChangeToAssumeUserPresenceCm)
        {
            _lastTimeUserMoved = DateTime.Now;
            Debug.Log("Delta tripped");
        }

        var userWasHere = _userIsHere;
        
        if ((DateTime.Now - _lastTimeUserMoved).Seconds > _secondsUserHasntMovedToAssumeAway)
        {
            _userIsHere = false;
        }
        else
        {
            _userIsHere = true;
        }

        if (userWasHere != _userIsHere)
        {
            if (_userIsHere)
            {
                Debug.Log("user is here now");
                var randomLine = _userCameBackLines[UnityEngine.Random.Range(0, _userCameBackLines.Length)];
                _azureTtsUnityPlayer.GenerateAndPlay(randomLine);
                SendServoAngle(_testServo1AngleMax);
            }
            else
            {
                var randomLine = _userWentAwayLines[UnityEngine.Random.Range(0, _userWentAwayLines.Length)];
                _azureTtsUnityPlayer.GenerateAndPlay(randomLine);
                
                SendServoAngle(_testServo1AngleMin);
            }
        }
    }

    private void HandleLine(string line)
    {
        if (string.IsNullOrEmpty(line))
        {
            return;
        }

        if (!line.StartsWith("D:"))
        {
            return;
        }

        var valueString = line.Substring(2);

        _previousDistanceCm = LatestDistanceCm;
        if (int.TryParse(valueString, out var parsedDistanceCm))
        {
            LatestDistanceCm = Mathf.Clamp(parsedDistanceCm, 5, 100);
        }
    }

    public void SendServoAngle(int angleDegrees)
    {
        if (_serialPort == null || !_serialPort.IsOpen)
        {
            return;
        }

        angleDegrees = Mathf.Clamp(angleDegrees, Mathf.Max(0, _testServo1AngleMin), Mathf.Min(_testServo1AngleMax));

        _serialPort.WriteLine($"A1:{angleDegrees}");
    }

    private void OnDestroy()
    {
        if (_serialPort != null && _serialPort.IsOpen)
        {
            _serialPort.Close();
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey