// Generated by ChatGPT and Riko Balakit / Pearl Grey

using System.Collections;
using DefaultNamespace;
using UnityEngine;
using NaughtyAttributes;

public abstract class BaseTtsUnityPlayer : MonoBehaviour
{
    [Header("Speech")]
    [TextArea(3, 10)]
    [SerializeField] private string _textToSpeak = "What's on your to-do list today?";

    [Header("Audio")]
    [SerializeField] private AudioSource _audioSource;
    
    private Coroutine _speakCoroutine;
    private AudioClip _currentAudioClip;

    public bool IsSpeaking => _speakCoroutine != null;
    public AudioSource AudioSource => _audioSource;
    public AudioClip CurrentAudioClip => _currentAudioClip;

    [Button("Generate and Play")]
    private void GenerateAndPlayFromInspector()
    {
        GenerateAndPlay(_textToSpeak);
    }

    public void GenerateAndPlay(string textToSpeak, bool promptAfterwards = false)
    {
        if (_audioSource == null)
        {
            Debug.LogError($"{GetType().Name}: AudioSource is not assigned.");
            return;
        }

        if (_speakCoroutine != null)
        {
            StopSpeaking();
        }

        _speakCoroutine = StartCoroutine(GenerateAndPlayCoroutine(textToSpeak, promptAfterwards));
    }

    public void StopSpeaking()
    {
        if (_speakCoroutine != null)
        {
            StopCoroutine(_speakCoroutine);
            _speakCoroutine = null;
        }

        if (_audioSource != null)
        {
            _audioSource.Stop();
        }
    }

    public void SetTextToSpeakInstantly(string textToSpeak)
    {
        _textToSpeak = textToSpeak;
    }

    public void SetAudioClipInstantly(AudioClip audioClip, bool stopPlayback = true)
    {
        _currentAudioClip = audioClip;

        if (_audioSource == null)
        {
            return;
        }

        if (stopPlayback == true)
        {
            _audioSource.Stop();
        }

        _audioSource.clip = audioClip;
    }

    protected virtual void OnDestroy()
    {
        StopSpeaking();
    }

    private IEnumerator GenerateAndPlayCoroutine(string textToSpeak, bool promptAfterwards)
    {
        yield return GenerateAudioClipCoroutine(
            textToSpeak,
            onSuccess: generatedAudioClip =>
            {
                _currentAudioClip = generatedAudioClip;

                _audioSource.loop = false;
                _audioSource.clip = generatedAudioClip;
                _audioSource.Play();
            });

        if (_audioSource.clip != null && _audioSource.isPlaying == true)
        {
            while (_audioSource.isPlaying == true)
            {
                yield return null;
            }
        }
        
        
        float PERIOD_TO_WAIT_BEFORE_LISTENING_FOR_RESPONSE_SECONDS = 0.5f;
        yield return new WaitForSeconds(PERIOD_TO_WAIT_BEFORE_LISTENING_FOR_RESPONSE_SECONDS);

        if (promptAfterwards)
        {
            GlobalManager.I.WakeWordSidecarClient.OnWakeWordTriggered();
        }

        _speakCoroutine = null;
    }

    protected abstract IEnumerator GenerateAudioClipCoroutine(
        string textToSpeak,
        System.Action<AudioClip> onSuccess);
}

// Generated by ChatGPT and Riko Balakit / Pearl Grey