# Generated by ChatGPT and Riko Balakit/Pearl Grey

import json
import socket
import struct
import threading
import time
from typing import Optional

import pvporcupine
import pyaudio

ACCESS_KEY = "4Ykv74uINKWCoLMpwvmb+2I+kUsBK6LtNBQETT2hH5y/w1JyhUTzhw=="

HOST = "127.0.0.1"
PORT = 17777
KEYWORD_PATHS = ["reet-sue-koh.ppn"]
DETECTION_COOLDOWN_SECONDS = 1.0


class WakeWordSidecar:
    def __init__(self) -> None:
        self._server_socket: Optional[socket.socket] = None
        self._client_socket: Optional[socket.socket] = None
        self._client_socket_lock = threading.Lock()
        self._is_running = False
        self._last_detection_time_seconds = 0.0

    def Run(self) -> None:
        self._is_running = True

        server_thread = threading.Thread(target=self._RunSocketServerThread, daemon=True)
        server_thread.start()

        porcupine = pvporcupine.create(
            access_key=ACCESS_KEY,
            keyword_paths=KEYWORD_PATHS
        )

        pa = pyaudio.PyAudio()

        stream = pa.open(
            rate=porcupine.sample_rate,
            channels=1,
            format=pyaudio.paInt16,
            input=True,
            frames_per_buffer=porcupine.frame_length
        )

        print(f"[WakeWordSidecar] Listening for wake word on {HOST}:{PORT}...")

        try:
            while self._is_running:
                pcm = stream.read(porcupine.frame_length, exception_on_overflow=False)
                pcm = struct.unpack_from("h" * porcupine.frame_length, pcm)

                keyword_index = porcupine.process(pcm)

                if keyword_index >= 0:
                    current_time_seconds = time.time()

                    if current_time_seconds - self._last_detection_time_seconds >= DETECTION_COOLDOWN_SECONDS:
                        self._last_detection_time_seconds = current_time_seconds
                        print("[WakeWordSidecar] Wake word detected!")
                        self._SendWakeWordDetectedEvent(current_time_seconds)
        except KeyboardInterrupt:
            print("[WakeWordSidecar] Stopping from keyboard interrupt.")
        finally:
            self._is_running = False

            try:
                stream.stop_stream()
            except Exception:
                pass

            try:
                stream.close()
            except Exception:
                pass

            try:
                pa.terminate()
            except Exception:
                pass

            try:
                porcupine.delete()
            except Exception:
                pass

            self._CloseClientSocket()
            self._CloseServerSocket()

    def _RunSocketServerThread(self) -> None:
        self._server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._server_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._server_socket.bind((HOST, PORT))
        self._server_socket.listen(1)

        while self._is_running:
            try:
                client_socket, client_address = self._server_socket.accept()
                client_socket.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)

                with self._client_socket_lock:
                    if self._client_socket is not None:
                        try:
                            self._client_socket.close()
                        except Exception:
                            pass

                    self._client_socket = client_socket

                print(f"[WakeWordSidecar] Unity connected from {client_address}.")
            except OSError:
                break
            except Exception as exception:
                print(f"[WakeWordSidecar] Socket server error: {exception}")
                time.sleep(0.1)

    def _SendWakeWordDetectedEvent(self, detected_time_seconds: float) -> None:
        payload = {
            "type": "wake_word_detected",
            "timestampUnixSeconds": detected_time_seconds
        }

        message = json.dumps(payload) + "\n"
        encoded_message = message.encode("utf-8")

        with self._client_socket_lock:
            if self._client_socket is None:
                print("[WakeWordSidecar] No Unity client connected. Dropping event.")
                return

            try:
                self._client_socket.sendall(encoded_message)
            except Exception as exception:
                print(f"[WakeWordSidecar] Failed to send event to Unity: {exception}")
                try:
                    self._client_socket.close()
                except Exception:
                    pass
                self._client_socket = None

    def _CloseClientSocket(self) -> None:
        with self._client_socket_lock:
            if self._client_socket is not None:
                try:
                    self._client_socket.close()
                except Exception:
                    pass

                self._client_socket = None

    def _CloseServerSocket(self) -> None:
        if self._server_socket is not None:
            try:
                self._server_socket.close()
            except Exception:
                pass

            self._server_socket = None


if __name__ == "__main__":
    WakeWordSidecar().Run()

# Generated by ChatGPT and Riko Balakit/Pearl Grey