// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using UnityEngine;

namespace Runtime.Tooling
{
    public class TaskState
    {
        private const int MaxTaskId = 9999;
        private const string DefaultFileName = "taskState.json";

        private int _nextTaskId = 0;

        public List<TaskData> Tasks = new List<TaskData>();

        public int GetNextTaskId()
        {
            var startingTaskId = _nextTaskId;

            for (var i = 0; i <= MaxTaskId; i++)
            {
                var candidateTaskId = (_nextTaskId + i) % (MaxTaskId + 1);

                if (FindTask(candidateTaskId) == null)
                {
                    _nextTaskId = (candidateTaskId + 1) % (MaxTaskId + 1);
                    return candidateTaskId;
                }
            }

            throw new InvalidOperationException("TaskState is full. No available task IDs remain.");
        }

        public TaskData FindTask(int taskId)
        {
            for (var i = 0; i < Tasks.Count; i++)
            {
                if (Tasks[i].taskId == taskId)
                {
                    return Tasks[i];
                }
            }

            return null;
        }

        public bool RemoveTask(int taskId)
        {
            for (var i = 0; i < Tasks.Count; i++)
            {
                if (Tasks[i].taskId == taskId)
                {
                    Tasks.RemoveAt(i);
                    RecalculateNextTaskId();
                    return true;
                }
            }

            return false;
        }

        public string SerializeToJsonString()
        {
            var serializedData = new SerializedTaskState
            {
                tasks = Tasks
            };

            return JsonConvert.SerializeObject(serializedData, Formatting.Indented);
        }

        public bool SaveToFile(out string errorMessage, string fileName = DefaultFileName)
        {
            errorMessage = null;

            try
            {
                var fullFilePath = GetFullFilePath(fileName);
                var directoryPath = Path.GetDirectoryName(fullFilePath);

                if (!string.IsNullOrWhiteSpace(directoryPath) && !Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                var json = SerializeToJsonString();
                File.WriteAllText(fullFilePath, json);

                return true;
            }
            catch (Exception exception)
            {
                errorMessage = "TaskState failed to save file. Exception: " + exception.Message;
                return false;
            }
        }

        public bool LoadFromFile(out string errorMessage, string fileName = DefaultFileName)
        {
            errorMessage = null;

            try
            {
                var fullFilePath = GetFullFilePath(fileName);

                if (!File.Exists(fullFilePath))
                {
                    Tasks = new List<TaskData>();
                    _nextTaskId = 0;
                    return true;
                }

                var json = File.ReadAllText(fullFilePath);

                if (string.IsNullOrWhiteSpace(json))
                {
                    Tasks = new List<TaskData>();
                    _nextTaskId = 0;
                    return true;
                }

                var deserializedData = JsonConvert.DeserializeObject<SerializedTaskState>(json);

                if (deserializedData == null)
                {
                    Tasks = new List<TaskData>();
                    _nextTaskId = 0;
                    return true;
                }

                Tasks = deserializedData.tasks ?? new List<TaskData>();
                RecalculateNextTaskId();

                return true;
            }
            catch (Exception exception)
            {
                errorMessage = "TaskState failed to load file. Exception: " + exception.Message;
                return false;
            }
        }

        private void RecalculateNextTaskId()
        {
            if (Tasks == null || Tasks.Count == 0)
            {
                _nextTaskId = 0;
                return;
            }

            var highestTaskId = -1;

            for (var i = 0; i < Tasks.Count; i++)
            {
                if (Tasks[i] != null && Tasks[i].taskId > highestTaskId)
                {
                    highestTaskId = Tasks[i].taskId;
                }
            }

            _nextTaskId = (highestTaskId + 1) % (MaxTaskId + 1);
        }

        private string GetFullFilePath(string fileName)
        {
            return Path.Combine(Application.persistentDataPath, fileName);
        }

        [Serializable]
        private class SerializedTaskState
        {
            public List<TaskData> tasks;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey