// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;

namespace Runtime.Tooling
{
    public enum TaskCategory
    {
        UNDEFINED,
        WORK,
        PERSONAL,
        HOBBY,
        DOMESTIC,
        RITSUKO
    }

    public enum TaskPriority
    {
        UNDEFINED,
        LOW,
        MEDIUM,
        HIGH
    }

    public enum TaskUrgency
    {
        UNDEFINED,
        LOW,
        MEDIUM,
        HIGH
    }

    public enum TaskStatus
    {
        PENDING,
        INPROGRESS,
        BLOCKED,
        DONE,
        CANCELLED,
        ARCHIVED
    }

    [Serializable]
    public class TaskData
    {
        public int taskId;

        public string name;

        public TaskCategory category;

        public TaskPriority priority;

        public TaskUrgency urgency;

        public TaskStatus status;

        public DateTime datetimeAdded;

        public string notes;
    }

    [Serializable]
    public class TaskToolPayload
    {
        public string action;

        public int taskId;

        public string name;

        public string category;

        public string priority;

        public string urgency;

        public string status;

        public string notes;
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey