// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Text;
using Runtime.Reasoning.DataTypes;
using UnityEngine;

namespace Runtime.Reasoning
{
    public class ConversationHistorySummarizer : PearlBehaviour
    {
        private ConversationHistoryStore _conversationHistoryStore;

        public void Initialize(ConversationHistoryStore conversationHistoryStore)
        {
            _conversationHistoryStore = conversationHistoryStore;
        }

        public async System.Threading.Tasks.Task<List<ConversationMessage>> SummarizeHistoryIfNeededAsync(
            List<ConversationMessage> conversationHistory,
            int maxRetainedConversationMessages,
            float fractionMessagesToTruncateWhenLimitHit,
            int summarySizeLimitSentences,
            string summaryPrefix,
            string assistantRole)
        {
            var summarizedConversationHistory = new List<ConversationMessage>(conversationHistory);

            Log("[ConversationHistorySummarizer] SummarizeHistoryIfNeededAsync called. " +
                "Current count: " + summarizedConversationHistory.Count +
                ", Max retained: " + maxRetainedConversationMessages +
                ", Fraction to truncate: " + fractionMessagesToTruncateWhenLimitHit);

            if (maxRetainedConversationMessages <= 0)
            {
                LogWarning("[ConversationHistorySummarizer] Max retained conversation messages was <= 0. Skipping summarization.");
                return summarizedConversationHistory;
            }

            if (summarizedConversationHistory.Count <= maxRetainedConversationMessages)
            {
                Log("[ConversationHistorySummarizer] History is within limit. No summarization needed.");
                return summarizedConversationHistory;
            }

            if (_conversationHistoryStore == null)
            {
                LogError("[ConversationHistorySummarizer] ConversationHistoryStore was not initialized.");
                return summarizedConversationHistory;
            }

            var nonSummaryMessagesToRollUpCount = Mathf.Clamp(
                Mathf.RoundToInt(maxRetainedConversationMessages * fractionMessagesToTruncateWhenLimitHit),
                1,
                maxRetainedConversationMessages);

            Log("[ConversationHistorySummarizer] History exceeded limit. Will roll up " +
                nonSummaryMessagesToRollUpCount + " non-summary messages per pass.");

            while (summarizedConversationHistory.Count > maxRetainedConversationMessages)
            {
                var existingSummaryMessage = GetExistingSummaryMessage(summarizedConversationHistory, summaryPrefix);
                var oldestNonSummaryMessages = GetOldestNonSummaryMessages(
                    summarizedConversationHistory,
                    nonSummaryMessagesToRollUpCount,
                    summaryPrefix);

                Log("[ConversationHistorySummarizer] Existing summary present: " + (existingSummaryMessage != null) +
                    ". Oldest non-summary messages selected: " + oldestNonSummaryMessages.Count);

                if (oldestNonSummaryMessages.Count == 0)
                {
                    LogWarning("[ConversationHistorySummarizer] No non-summary messages were available to summarize.");
                    break;
                }

                var messagesToSummarize = new List<ConversationMessage>();

                if (existingSummaryMessage != null)
                {
                    messagesToSummarize.Add(existingSummaryMessage);
                }

                messagesToSummarize.AddRange(oldestNonSummaryMessages);

                Log("[ConversationHistorySummarizer] Total messages being summarized this pass: " + messagesToSummarize.Count);

                var rolledUpSummaryBody = await BuildSummaryFromMessagesAsync(
                    messagesToSummarize,
                    summarySizeLimitSentences,
                    summaryPrefix);

                if (existingSummaryMessage != null)
                {
                    summarizedConversationHistory.Remove(existingSummaryMessage);
                }

                for (var i = 0; i < oldestNonSummaryMessages.Count; i++)
                {
                    summarizedConversationHistory.Remove(oldestNonSummaryMessages[i]);
                }

                var summaryConversationMessage = _conversationHistoryStore.CreateSummaryConversationMessage(
                    summaryPrefix,
                    rolledUpSummaryBody,
                    assistantRole);

                summarizedConversationHistory.Insert(0, summaryConversationMessage);

                Log("[ConversationHistorySummarizer] Summary inserted at index 0. New conversation count: " + summarizedConversationHistory.Count);
            }

            return summarizedConversationHistory;
        }

        private ConversationMessage GetExistingSummaryMessage(
            List<ConversationMessage> conversationHistory,
            string summaryPrefix)
        {
            if (conversationHistory == null || conversationHistory.Count == 0)
            {
                return null;
            }

            var oldestMessage = conversationHistory[0];

            if (_conversationHistoryStore.IsSummaryMessage(oldestMessage, summaryPrefix))
            {
                return oldestMessage;
            }

            return null;
        }

        private List<ConversationMessage> GetOldestNonSummaryMessages(
            List<ConversationMessage> conversationHistory,
            int count,
            string summaryPrefix)
        {
            var oldestNonSummaryMessages = new List<ConversationMessage>();

            for (var i = 0; i < conversationHistory.Count; i++)
            {
                var message = conversationHistory[i];

                if (_conversationHistoryStore.IsSummaryMessage(message, summaryPrefix))
                {
                    continue;
                }

                oldestNonSummaryMessages.Add(message);

                if (oldestNonSummaryMessages.Count >= count)
                {
                    break;
                }
            }

            return oldestNonSummaryMessages;
        }

        private async System.Threading.Tasks.Task<string> BuildSummaryFromMessagesAsync(
            List<ConversationMessage> messagesToSummarize,
            int summarySizeLimitSentences,
            string summaryPrefix)
        {
            if (messagesToSummarize == null || messagesToSummarize.Count == 0)
            {
                return "No prior interactions were available for summarization.";
            }

            var summaryInputBuilder = new StringBuilder();

            for (var i = 0; i < messagesToSummarize.Count; i++)
            {
                var message = messagesToSummarize[i];

                if (message == null || string.IsNullOrWhiteSpace(message.Content))
                {
                    continue;
                }

                var contentToAppend = message.Content;

                if (_conversationHistoryStore.IsSummaryMessage(message, summaryPrefix))
                {
                    contentToAppend = _conversationHistoryStore.ExtractSummaryBody(message.Content, summaryPrefix);
                }

                summaryInputBuilder.AppendLine("Role: " + message.Role);
                summaryInputBuilder.AppendLine("Content: " + contentToAppend);
                summaryInputBuilder.AppendLine();
            }

            var summarizationPromptMessages = new List<OpenRouterChatClient.ChatMessage>
            {
                new OpenRouterChatClient.ChatMessage(
                    "system",
                    "You are compressing older conversation history into a rolling memory summary for a personal assistant. " +
                    "Preserve durable context such as ongoing projects, deadlines, important plans this month, recurring topics, relationships between people, medium-term goals, and anything that is still likely to matter in future conversation. " +
                    "Naturally let stale details decay in importance. " +
                    "Write plain prose only. " +
                    "Do not include timestamps. " +
                    "Do not include JSON. " +
                    "Do not include bullet points. " +
                    "Keep the summary to at most " + summarySizeLimitSentences + " sentences."),
                new OpenRouterChatClient.ChatMessage(
                    "user",
                    "Please summarize these older interactions into a compact rolling memory summary:\n\n" + summaryInputBuilder)
            };

            try
            {
                GlobalManager.I.State.AddLongRunningTaskOwner(this);

                var rawSummary = await GlobalManager.I.LlmClient.SendPromptAsync(
                    summarizationPromptMessages,
                    GlobalManager.I.Configuration.LlmModelStandard);

                if (string.IsNullOrWhiteSpace(rawSummary))
                {
                    LogWarning("[ConversationHistorySummarizer] LLM returned empty summary text. Falling back to local summary.");
                    return BuildFallbackSummary(messagesToSummarize, summarySizeLimitSentences, summaryPrefix);
                }

                var cleanedSummary = rawSummary.Trim();
                cleanedSummary = StripSummaryPrefixIfPresent(cleanedSummary, summaryPrefix);

                Log("[ConversationHistorySummarizer] Built rolled-up summary: " + cleanedSummary);

                return cleanedSummary;
            }
            catch (Exception exception)
            {
                GlobalManager.I.State.RemoveLongRunningTaskOwner(this);
                LogWarning("[ConversationHistorySummarizer] Failed to build LLM summary. Falling back to local summary. Exception: " + exception);
                return BuildFallbackSummary(messagesToSummarize, summarySizeLimitSentences, summaryPrefix);
            }
            finally
            {
                GlobalManager.I.State.RemoveLongRunningTaskOwner(this);
            }
        }

        private string BuildFallbackSummary(
            List<ConversationMessage> messagesToSummarize,
            int summarySizeLimitSentences,
            string summaryPrefix)
        {
            var summaryBuilder = new StringBuilder();
            var sentenceCount = 0;

            for (var i = 0; i < messagesToSummarize.Count; i++)
            {
                if (sentenceCount >= summarySizeLimitSentences)
                {
                    break;
                }

                var message = messagesToSummarize[i];

                if (message == null || string.IsNullOrWhiteSpace(message.Content))
                {
                    continue;
                }

                var content = message.Content;

                if (_conversationHistoryStore.IsSummaryMessage(message, summaryPrefix))
                {
                    content = _conversationHistoryStore.ExtractSummaryBody(content, summaryPrefix);
                }

                content = content.Replace("\n", " ").Replace("\r", " ").Trim();

                if (string.IsNullOrWhiteSpace(content))
                {
                    continue;
                }

                summaryBuilder.Append(message.Role);
                summaryBuilder.Append(" discussed ");
                summaryBuilder.Append(content);
                summaryBuilder.Append(". ");

                sentenceCount++;
            }

            return summaryBuilder.ToString().Trim();
        }

        private string StripSummaryPrefixIfPresent(string summaryText, string summaryPrefix)
        {
            if (string.IsNullOrWhiteSpace(summaryText))
            {
                return summaryText;
            }

            if (summaryText.StartsWith(summaryPrefix, StringComparison.OrdinalIgnoreCase))
            {
                var strippedSummary = summaryText.Substring(summaryPrefix.Length).TrimStart();

                if (strippedSummary.StartsWith(":"))
                {
                    strippedSummary = strippedSummary.Substring(1).TrimStart();
                }

                return strippedSummary;
            }

            return summaryText;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey