// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using Runtime.Reasoning.DataTypes;
using UnityEngine;

namespace Runtime.Reasoning
{
    public class ConversationHistoryStore : PearlBehaviour
    {
        public List<ConversationMessage> LoadConversationHistory(string historyFileName)
        {
            var loadedConversationHistory = new List<ConversationMessage>();
            var filePath = GetHistoryFilePath(historyFileName);

            if (!File.Exists(filePath))
            {
                Log("[ConversationHistoryStore] No existing conversation history file found at: " + filePath);
                return loadedConversationHistory;
            }

            try
            {
                var json = File.ReadAllText(filePath);

                if (string.IsNullOrWhiteSpace(json))
                {
                    LogWarning("[ConversationHistoryStore] Conversation history file was empty.");
                    return loadedConversationHistory;
                }

                var fileData = JsonConvert.DeserializeObject<ConversationHistoryFileData>(json);

                if (fileData?.ConversationHistory == null)
                {
                    LogWarning("[ConversationHistoryStore] Conversation history file did not contain valid history data.");
                    return loadedConversationHistory;
                }

                for (var i = 0; i < fileData.ConversationHistory.Count; i++)
                {
                    var message = fileData.ConversationHistory[i];

                    if (message == null)
                    {
                        continue;
                    }

                    loadedConversationHistory.Add(message);
                }

                Log("[ConversationHistoryStore] Loaded conversation history from disk: " + filePath);
            }
            catch (Exception exception)
            {
                LogError("[ConversationHistoryStore] Failed to load conversation history: " + exception);
            }

            return loadedConversationHistory;
        }

        public void SaveConversationHistory(string historyFileName, List<ConversationMessage> conversationHistory)
        {
            var filePath = GetHistoryFilePath(historyFileName);

            try
            {
                var fileData = new ConversationHistoryFileData
                {
                    ConversationHistory = new List<ConversationMessage>(conversationHistory)
                };

                var json = JsonConvert.SerializeObject(fileData, Formatting.Indented);
                var tempFilePath = filePath + ".tmp";

                File.WriteAllText(tempFilePath, json);

                if (File.Exists(filePath))
                {
                    File.Delete(filePath);
                }

                File.Move(tempFilePath, filePath);

                Log("[ConversationHistoryStore] Saved conversation history to disk: " + filePath);
            }
            catch (Exception exception)
            {
                LogError("[ConversationHistoryStore] Failed to save conversation history: " + exception);
            }
        }

        public bool IsSummaryMessage(ConversationMessage conversationMessage, string summaryPrefix)
        {
            if (conversationMessage == null)
            {
                return false;
            }

            if (string.IsNullOrWhiteSpace(conversationMessage.Content))
            {
                return false;
            }

            return conversationMessage.Content.StartsWith(summaryPrefix, StringComparison.OrdinalIgnoreCase);
        }

        public ConversationMessage CreateSummaryConversationMessage(string summaryPrefix, string summaryBody, string assistantRole)
        {
            var cleanedSummaryBody = string.IsNullOrWhiteSpace(summaryBody)
                ? "No older interactions were available for summarization."
                : summaryBody.Trim();

            var summaryContent = summaryPrefix + ":\n" + cleanedSummaryBody;

            return new ConversationMessage(assistantRole, summaryContent, string.Empty);
        }

        public string ExtractSummaryBody(string summaryContent, string summaryPrefix)
        {
            if (string.IsNullOrWhiteSpace(summaryContent))
            {
                return string.Empty;
            }

            if (!summaryContent.StartsWith(summaryPrefix, StringComparison.OrdinalIgnoreCase))
            {
                return summaryContent;
            }

            var strippedSummary = summaryContent.Substring(summaryPrefix.Length).TrimStart();

            if (strippedSummary.StartsWith(":"))
            {
                strippedSummary = strippedSummary.Substring(1).TrimStart();
            }

            return strippedSummary;
        }

        private string GetHistoryFilePath(string historyFileName)
        {
            var directoryPath = Application.persistentDataPath;

            try
            {
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }
            }
            catch (Exception exception)
            {
                LogWarning("[ConversationHistoryStore] Failed to ensure persistence directory exists: " + exception.Message);
            }

            return Path.Combine(directoryPath, historyFileName);
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey