// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Configuration;
using Runtime.Reasoning.DataTypes;
using Runtime.Utilities;

namespace Runtime.Reasoning
{
    public class PromptBuilder : PearlBehaviour
    {
        private readonly Dictionary<PromptCacheKey, string> _systemPromptCache = new Dictionary<PromptCacheKey, string>();

        private readonly struct PromptCacheKey
        {
            public readonly BehaviourMode BehaviourMode;
            public readonly QuerySource QuerySource;

            public PromptCacheKey(BehaviourMode behaviourMode, QuerySource querySource)
            {
                BehaviourMode = behaviourMode;
                QuerySource = querySource;
            }
        }

        public void Initialize()
        {
            SetInitialized();
        }

        public void ClearGeneratedPromptCache()
        {
            _systemPromptCache.Clear();
        }

        public string BuildSystemPrompt(QuerySource querySource, bool attachLocalTime = false)
        {
            if (!IsInitialized)
            {
                LogError("PromptBuilder is not initialized. Returning empty prompt.");
                return "";
            }

            var currentMode = GlobalManager.I.State.CurrentMode;
            var promptCacheKey = new PromptCacheKey(currentMode, querySource);

            if (_systemPromptCache.TryGetValue(promptCacheKey, out var cachedPrompt))
            {
                return AttachLocalTimeIfNeeded(cachedPrompt, attachLocalTime);
            }

            var globalConfiguration = GlobalManager.I.Configuration.GlobalPromptConfiguration;
            var modePromptConfiguration = GetResolvedModePromptConfiguration(currentMode);
            var stringBuilder = new StringBuilder(4096);

            AppendSectionHeader(stringBuilder, "Core Context");
            AppendLineIfNotEmpty(stringBuilder, "Purpose", globalConfiguration.Purpose);
            AppendLineIfNotEmpty(stringBuilder, "Mode Context", modePromptConfiguration.ModeContext);
            AppendLineIfNotEmpty(stringBuilder, "Base Personality", globalConfiguration.Personality);
            AppendLineIfNotEmpty(stringBuilder, "Additional Personality due to Mode", modePromptConfiguration.PersonalityAdditions);
            AppendLineIfNotEmpty(stringBuilder, "Your lore", globalConfiguration.Lore);
            AppendLineIfNotEmpty(stringBuilder, "Technical notes", globalConfiguration.TechnicalNotes);

            var responseInstructionsForSource = GetResponseInstructionsForQuerySource(globalConfiguration, querySource);

            AppendSectionHeader(stringBuilder, "Behavior Instructions");
            AppendLineIfNotEmpty(stringBuilder, "Response Instructions For Current Source", responseInstructionsForSource);
            AppendLineIfNotEmpty(stringBuilder, "Inbound Query Formatting Instructions", globalConfiguration.QueryFormatInstructions);
            AppendLineIfNotEmpty(stringBuilder, "Global Response Instructions", globalConfiguration.ResponseInstructionsGlobal);
            AppendLineIfNotEmpty(stringBuilder, "Response Instruction Additions due to Mode", modePromptConfiguration.ResponseInstructionAdditionsAllModes);

            AppendSectionHeader(stringBuilder, "Tooling");
            AppendBlockIfNotEmpty(stringBuilder, "Available Tools and Tool Usage Rules", GlobalManager.I.ToolRouter.PromptForTools);

            AppendSectionHeader(stringBuilder, "Output Contract");
            AppendBlockIfNotEmpty(stringBuilder, "Outbound Response Formatting Instructions", globalConfiguration.ResponseFormatInstructions);

            var generatedPrompt = stringBuilder.ToString().TrimEnd();
            _systemPromptCache[promptCacheKey] = generatedPrompt;

            return AttachLocalTimeIfNeeded(generatedPrompt, attachLocalTime);
        }

        private static string AttachLocalTimeIfNeeded(string prompt, bool attachLocalTime)
        {
            if (!attachLocalTime)
            {
                return prompt;
            }

            var utcNow = DateTime.UtcNow;
            var localTime = TimeUtility.ConvertUtcToConfiguredLocalTime(utcNow);
            var localTimeAustin = localTime.ToString("yyyy-MM-dd hh:mm:ss tt", CultureInfo.InvariantCulture);

            return $"The current local time in Austin is {localTimeAustin}.\n{prompt}";
        }

        private static ModePromptConfiguration GetResolvedModePromptConfiguration(BehaviourMode behaviourMode)
        {
            var defaultModePromptConfiguration = GlobalManager.I.Configuration.DefaultModePromptConfiguration;
            var modePromptConfigurations = GlobalManager.I.Configuration.ModePromptConfigurations;

            if (modePromptConfigurations == null)
            {
                return defaultModePromptConfiguration;
            }

            for (var modePromptConfigurationIndex = 0; modePromptConfigurationIndex < modePromptConfigurations.Length; modePromptConfigurationIndex++)
            {
                var modePromptConfiguration = modePromptConfigurations[modePromptConfigurationIndex];

                if (modePromptConfiguration == null)
                {
                    continue;
                }

                if (modePromptConfiguration.BehaviourMode == behaviourMode)
                {
                    return modePromptConfiguration;
                }
            }

            return defaultModePromptConfiguration;
        }

        private static string GetResponseInstructionsForQuerySource(GlobalPromptConfiguration globalConfiguration, QuerySource querySource)
        {
            if (querySource == QuerySource.Discord)
            {
                return globalConfiguration.ResponseInstructionsForDiscord;
            }

            if (querySource == QuerySource.Speech)
            {
                return globalConfiguration.ResponseInstructionsForSpeech;
            }

            if (querySource == QuerySource.AssistantSelf)
            {
                return globalConfiguration.ResponseInstructionsForSelf;
            }

            return null;
        }

        private static void AppendSectionHeader(StringBuilder stringBuilder, string sectionTitle)
        {
            if (stringBuilder.Length > 0)
            {
                stringBuilder.Append('\n');
            }

            stringBuilder.Append("=== ");
            stringBuilder.Append(sectionTitle);
            stringBuilder.Append(" ===");
            stringBuilder.Append('\n');
        }

        private static void AppendLineIfNotEmpty(StringBuilder stringBuilder, string label, string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return;
            }

            stringBuilder.Append(label);
            stringBuilder.Append(": ");
            stringBuilder.Append(value.Trim());
            stringBuilder.Append('\n');
        }

        private static void AppendBlockIfNotEmpty(StringBuilder stringBuilder, string label, string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return;
            }

            stringBuilder.Append(label);
            stringBuilder.Append(':');
            stringBuilder.Append('\n');
            stringBuilder.Append(value.Trim());
            stringBuilder.Append('\n');
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey