// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Configuration;
using Runtime.Reasoning.DataTypes;
using Runtime.Utilities;

namespace Runtime.Reasoning
{
    public class PromptBuilder : PearlBehaviour
    {
        private static readonly Dictionary<PromptCacheKey, string> s_systemPromptCache = new Dictionary<PromptCacheKey, string>();

        private readonly struct PromptCacheKey
        {
            public readonly BehaviourMode BehaviourMode;
            public readonly QuerySource QuerySource;

            public PromptCacheKey(BehaviourMode behaviourMode, QuerySource querySource)
            {
                BehaviourMode = behaviourMode;
                QuerySource = querySource;
            }
        }

        private void Start()
        {
            SetInitialized();
        }

        public static void ClearGeneratedPromptCache()
        {
            s_systemPromptCache.Clear();
        }

        public static string BuildSystemPrompt(QuerySource querySource, bool attachLocalTime = false)
        {
            var currentMode = GlobalManager.I.State.CurrentMode;
            var promptCacheKey = new PromptCacheKey(currentMode, querySource);
            var returnPrompt = "";

            if (s_systemPromptCache.TryGetValue(promptCacheKey, out var cachedPrompt))
            {
                returnPrompt = cachedPrompt;
            }
            else
            {
                var globalConfiguration = GlobalManager.I.Configuration.GlobalPromptConfiguration;
                var modePromptConfiguration = GetResolvedModePromptConfiguration(currentMode);

                var stringBuilder = new StringBuilder(2048);

                AppendLineIfNotEmpty(stringBuilder, "Purpose: ", globalConfiguration.Purpose);
                AppendLineIfNotEmpty(stringBuilder, "Mode Context: ", modePromptConfiguration.ModeContext);

                AppendLineIfNotEmpty(stringBuilder, "Base Personality: ", globalConfiguration.Personality);
                AppendLineIfNotEmpty(stringBuilder, "Additional Personality due to Mode: ", modePromptConfiguration.PersonalityAdditions);
                AppendLineIfNotEmpty(stringBuilder, "Your lore: ", globalConfiguration.Lore);
                AppendLineIfNotEmpty(stringBuilder, "Technical notes: ", globalConfiguration.TechnicalNotes);

                var responseInstructionsForSource = GetResponseInstructionsForQuerySource(globalConfiguration, querySource);
                AppendLineIfNotEmpty(stringBuilder, "Response Instructions: ", responseInstructionsForSource);

                AppendLineIfNotEmpty(stringBuilder, "Inbound Query formatting instructions: ", globalConfiguration.QueryFormatInstructions);
                AppendLineIfNotEmpty(stringBuilder, "Response Instructions: ", globalConfiguration.ResponseInstructionsGlobal);
                AppendLineIfNotEmpty(stringBuilder, "Response Instruction Additions due to Mode: ", modePromptConfiguration.ResponseInstructionAdditionsAllModes);
                AppendLineIfNotEmpty(stringBuilder, "Outbound Response formatting instructions: ", globalConfiguration.ResponseFormatInstructions);

                var generatedPrompt = stringBuilder.ToString();
                s_systemPromptCache[promptCacheKey] = generatedPrompt;
                returnPrompt = generatedPrompt;
            }

            if (attachLocalTime)
            {
                var utcNow = DateTime.UtcNow;
                var localTime = TimeUtility.ConvertUtcToConfiguredLocalTime(utcNow);
                var localTimeAustin = localTime.ToString("yyyy-MM-dd hh:mm:ss tt", CultureInfo.InvariantCulture);
                returnPrompt = $"The current local time in Austin is {localTimeAustin:hh:mm tt}.\n" + returnPrompt;
            }
            

            return returnPrompt;
        }

        private static ModePromptConfiguration GetResolvedModePromptConfiguration(BehaviourMode behaviourMode)
        {
            var defaultModePromptConfiguration = GlobalManager.I.Configuration.DefaultModePromptConfiguration;
            var modePromptConfigurations = GlobalManager.I.Configuration.ModePromptConfigurations;

            if (modePromptConfigurations == null)
            {
                return defaultModePromptConfiguration;
            }

            for (var modePromptConfigurationIndex = 0; modePromptConfigurationIndex < modePromptConfigurations.Length; modePromptConfigurationIndex++)
            {
                var modePromptConfiguration = modePromptConfigurations[modePromptConfigurationIndex];
                if (modePromptConfiguration == null)
                {
                    continue;
                }

                if (modePromptConfiguration.BehaviourMode == behaviourMode)
                {
                    return modePromptConfiguration;
                }
            }

            return defaultModePromptConfiguration;
        }

        private static string GetResponseInstructionsForQuerySource(GlobalPromptConfiguration globalConfiguration, QuerySource querySource)
        {
            if (querySource == QuerySource.Discord)
            {
                return globalConfiguration.ResponseInstructionsForDiscord;
            }

            if (querySource == QuerySource.Speech)
            {
                return globalConfiguration.ResponseInstructionsForSpeech;
            }

            if (querySource == QuerySource.AssistantSelf)
            {
                return globalConfiguration.ResponseInstructionsForSelf;
            }

            return null;
        }

        private static void AppendLineIfNotEmpty(StringBuilder stringBuilder, string label, string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return;
            }

            stringBuilder.Append(label);
            stringBuilder.Append(": ");
            stringBuilder.Append(value);
            stringBuilder.Append('\n');
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey