// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.IO;
using Configuration;
using NaughtyAttributes;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Runtime.Reasoning.DataTypes;
using Runtime.Utilities;
using UnityEngine;

namespace Runtime.Reasoning
{
    public class QueryHandler : PearlBehaviour
    {
        private bool _includeSystemPrompt = true;
        private int _maxRetainedConversationMessages => GlobalManager.I.Configuration.MaxRetainedConversationMessages;
        private int _maxJsonParseAttempts => GlobalManager.I.Configuration.MaxJsonParseRetries;
        private bool _auditHistoryToDiscord => GlobalManager.I.State.AuditModeEnabled;

        [Header("Persistence")]
        private string _historyFileName => GlobalManager.I.Configuration.ConversationHistoryFileName;

        [Header("Stats")]
        [SerializeField] private GameObject _thinkingIndicator;

        [ReadOnly]
        [SerializeField] private int _storedConversationMessageCount;

        [ReadOnly]
        [SerializeField] private int _userMessageCount;

        [ReadOnly]
        [SerializeField] private int _assistantMessageCount;

        [ReadOnly]
        [SerializeField] private string _currentLocalAustinTimeDisplay;

        [Header("Inspector Conversation History")]
        [SerializeField] private List<InspectorChatMessage> _inspectorConversationHistory = new List<InspectorChatMessage>();

        private readonly List<ConversationMessage> _conversationHistory = new List<ConversationMessage>();

        public void Initialize()
        {
            LoadHistoryFromDisk();
            RefreshStats();

            _thinkingIndicator.SetActive(false);

            SetInitialized();
        }

        [Button("Reset")]
        public void ResetHistory()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();
            SaveHistoryToDisk();
            RefreshStats();

            Log("[QueryHandler] Conversation history reset.");
            Log("[QueryHandler] System prompt is rebuilt fresh on every message. After this reset, the next request will use a freshly built system prompt with empty conversation history.");

            MarkDirty();
        }

        public async void HandleNewMessage(string messageContent, QuerySource source)
        {
            if (string.IsNullOrWhiteSpace(messageContent))
            {
                LogWarning("[QueryHandler] Ignoring empty message.");
                return;
            }

            Log("[QueryHandler] Received new message: " + messageContent);

            if (source != QuerySource.AssistantSelf)
            {
                GlobalManager.I.State.SetLastTimeUserInteractedToNow();
            }

            StructuredAssistantResponse structuredAssistantResponse = null;

            try
            {
                var userTimestamp = TimeUtility.GetCurrentLocalAustinTimeDisplay();
                var outboundMessageHistory = BuildOutboundMessageHistory(messageContent, userTimestamp, source);

                string rawResponse = null;

                _thinkingIndicator.SetActive(true);

                for (var attemptIndex = 0; attemptIndex < _maxJsonParseAttempts; attemptIndex++)
                {
                    rawResponse = await GlobalManager.I.LlmClient.SendPromptAsync(
                        outboundMessageHistory,
                        GlobalManager.I.Configuration.LlmModelStandard);

                    Log("[QueryHandler] Raw LLM response attempt " + (attemptIndex + 1) + ": " + rawResponse);

                    if (TryParseStructuredAssistantResponse(rawResponse, out structuredAssistantResponse))
                    {
                        break;
                    }

                    LogWarning("[QueryHandler] Failed to parse structured LLM response on attempt " + (attemptIndex + 1) + ".");
                }

                if (structuredAssistantResponse == null)
                {
                    LogError("[QueryHandler] Failed to get valid structured JSON response after " + _maxJsonParseAttempts + " attempts.");
                    return;
                }

                AddConversationMessage("user", messageContent, userTimestamp);
                AddConversationMessage("assistant", structuredAssistantResponse.reply, TimeUtility.GetCurrentLocalAustinTimeDisplay());
                TrimConversationHistoryToLimit();
                SaveHistoryToDisk();

                if (structuredAssistantResponse.ConversationState == AssistantConversationState.Reset)
                {
                    Log("[QueryHandler] Detected conversation reset request. Resetting history.");
                    ResetHistory();
                }

                SendResponseToSource(
                    structuredAssistantResponse.reply,
                    structuredAssistantResponse.Emotion,
                    messageContent,
                    source,
                    structuredAssistantResponse.ConversationState != AssistantConversationState.End);

                ExecuteToolsIfRequested(structuredAssistantResponse);

                if (structuredAssistantResponse.ConversationState == AssistantConversationState.End)
                {
                    Log("[QueryHandler] Detected end of conversation.");
                }
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Error processing message: " + exception);
            }
            finally
            {
                _thinkingIndicator.SetActive(false);
            }
        }

        private void ExecuteToolsIfRequested(StructuredAssistantResponse structuredAssistantResponse)
        {
            if (structuredAssistantResponse == null)
            {
                return;
            }

            if (structuredAssistantResponse.ToolCalls == null || structuredAssistantResponse.ToolCalls.Count == 0)
            {
                Log("[QueryHandler] No tools requested.");
                return;
            }

            var toolCallsToExecute = new List<StructuredToolCall>();

            for (var i = 0; i < structuredAssistantResponse.ToolCalls.Count; i++)
            {
                var toolCall = structuredAssistantResponse.ToolCalls[i];

                if (toolCall == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(toolCall.ToolName))
                {
                    LogWarning("[QueryHandler] Tool call at index " + i + " had empty toolName. Skipping.");
                    continue;
                }

                if (string.Equals(toolCall.ToolName, "None", StringComparison.OrdinalIgnoreCase))
                {
                    Log("[QueryHandler] Tool call at index " + i + " explicitly requested None. Skipping.");
                    continue;
                }

                toolCallsToExecute.Add(toolCall);
            }

            if (toolCallsToExecute.Count == 0)
            {
                Log("[QueryHandler] No executable tool calls remained after filtering.");
                return;
            }

            for (var i = 0; i < toolCallsToExecute.Count; i++)
            {
                var toolCall = toolCallsToExecute[i];

                var payloadJson = toolCall.ToolPayload == null
                    ? "{}"
                    : JsonConvert.SerializeObject(toolCall.ToolPayload);

                Log("[QueryHandler] Executing tool call " + (i + 1) + "/" + toolCallsToExecute.Count + ": " + toolCall.ToolName);
                Log("[QueryHandler] Tool payload: " + payloadJson);

                var toolExecutedSuccessfully = GlobalManager.I.ToolRouter.TryExecuteTool(
                    toolCall.ToolName,
                    payloadJson,
                    out var executionSummary);

                if (toolExecutedSuccessfully)
                {
                    Log("[QueryHandler] Tool executed successfully. Summary: " + executionSummary);

                    if (_auditHistoryToDiscord && !string.IsNullOrWhiteSpace(executionSummary))
                    {
                        GlobalManager.I.DiscordClient.SendDirectMessage("**Tool execution:** " + executionSummary);
                    }
                }
                else
                {
                    LogWarning("[QueryHandler] Tool execution failed. Summary: " + executionSummary);

                    if (_auditHistoryToDiscord && !string.IsNullOrWhiteSpace(executionSummary))
                    {
                        GlobalManager.I.DiscordClient.SendDirectMessage("**Tool execution failed:** " + executionSummary);
                    }
                }
            }
        }

        private void SendResponseToSource(
            string cleanedResponse,
            AssistantEmotionResponse emotion,
            string originalQuery,
            QuerySource source,
            bool promptAfterwards)
        {
            if (source == QuerySource.Discord)
            {
                GlobalManager.I.DiscordClient.SendDirectMessage(cleanedResponse);
                return;
            }

            if (source == QuerySource.Speech || source == QuerySource.AssistantSelf)
            {
                GlobalManager.I.SpeakAndEmoteController.SendPhraseAndEmotion(cleanedResponse, emotion, promptAfterwards);

                if (_auditHistoryToDiscord)
                {
                    if (source == QuerySource.AssistantSelf)
                    {
                        var auditMessage =
                            $"**Proactive thought from myself:** \"{originalQuery}\"\n\n**Emotion:** {emotion}\n\n**Spoken prompt sent to user:** \"{cleanedResponse}\"";
                        GlobalManager.I.DiscordClient.SendDirectMessage(auditMessage);
                    }
                    else
                    {
                        var auditMessage =
                            $"**Spoken query from user:** \"{originalQuery}\"\n\n**Emotion:** {emotion}\n\n**Spoken response sent to user:** \"{cleanedResponse}\"";
                        GlobalManager.I.DiscordClient.SendDirectMessage(auditMessage);
                    }
                }
            }
        }

        private List<OpenRouterChatClient.ChatMessage> BuildOutboundMessageHistory(
            string newestUserMessageContent,
            string newestUserTimestamp,
            QuerySource source)
        {
            var outboundMessageHistory = new List<OpenRouterChatClient.ChatMessage>();

            _currentLocalAustinTimeDisplay = TimeUtility.GetCurrentLocalAustinTimeDisplay();

            var systemPrompt = GlobalManager.I.PromptBuilder.BuildSystemPrompt(source, true);

            var systemPromptWithTimeContext =
                systemPrompt + "\n\n" +
                "local time: " + _currentLocalAustinTimeDisplay + "\n";

            Log("[QueryHandler] Full system prompt for this message:\n" + systemPromptWithTimeContext);
            Log("[QueryHandler] Conversation history count included in outbound prompt: " + _conversationHistory.Count);
            Log("[QueryHandler] Current query source: " + source);

            if (_includeSystemPrompt && !string.IsNullOrWhiteSpace(systemPrompt))
            {
                outboundMessageHistory.Add(new OpenRouterChatClient.ChatMessage("system", systemPromptWithTimeContext));
            }

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var existingMessage = _conversationHistory[i];

                outboundMessageHistory.Add(
                    new OpenRouterChatClient.ChatMessage(
                        existingMessage.Role,
                        FormatMessageForModel(existingMessage.Content, existingMessage.LocalTimestampDisplay, null)));
            }

            outboundMessageHistory.Add(
                new OpenRouterChatClient.ChatMessage(
                    "user",
                    FormatMessageForModel(newestUserMessageContent, newestUserTimestamp, source)));

            return outboundMessageHistory;
        }

        private string FormatMessageForModel(string content, string localTimestampDisplay, QuerySource? source)
        {
            var messagePrefix = "";

            if (source == QuerySource.AssistantSelf)
            {
                messagePrefix = "[This message is from the assistant speaking to itself as part of internal reflection and trying to think of something to ask the user proactively]\n\n";
            }

            var messageEnvelope = new ModelInputMessageEnvelope
            {
                local_time_austin = localTimestampDisplay,
                message = messagePrefix + content
            };

            if (source.HasValue)
            {
                messageEnvelope.current_query_source = source.Value.ToString();
            }

            return JsonConvert.SerializeObject(messageEnvelope, Formatting.None);
        }

        private bool TryParseStructuredAssistantResponse(string rawResponse, out StructuredAssistantResponse structuredAssistantResponse)
        {
            structuredAssistantResponse = null;

            Log("[QueryHandler] TryParseStructuredAssistantResponse called.");

            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                LogWarning("[QueryHandler] rawResponse was null or whitespace.");
                return false;
            }

            Log("[QueryHandler] rawResponse length: " + rawResponse.Length);
            Log("[QueryHandler] rawResponse preview: " + rawResponse.Substring(0, Math.Min(rawResponse.Length, 500)));

            var cleanedJson = ExtractLikelyJsonObject(rawResponse);

            if (string.IsNullOrWhiteSpace(cleanedJson))
            {
                LogWarning("[QueryHandler] ExtractLikelyJsonObject returned null or whitespace.");
                return false;
            }

            Log("[QueryHandler] cleanedJson length: " + cleanedJson.Length);
            Log("[QueryHandler] cleanedJson preview: " + cleanedJson.Substring(0, Math.Min(cleanedJson.Length, 500)));

            try
            {
                Log("[QueryHandler] Attempting JSON deserialization into StructuredAssistantResponse...");

                var parsedResponse = JsonConvert.DeserializeObject<StructuredAssistantResponse>(cleanedJson);

                if (parsedResponse == null)
                {
                    LogWarning("[QueryHandler] Deserialization succeeded but parsedResponse was null.");
                    return false;
                }

                Log("[QueryHandler] Deserialization succeeded.");

                if (string.IsNullOrWhiteSpace(parsedResponse.reply))
                {
                    LogWarning("[QueryHandler] parsedResponse.reply was null or whitespace.");
                    return false;
                }

                Log("[QueryHandler] parsedResponse.reply: " + parsedResponse.reply);

                if (parsedResponse.ToolCalls == null)
                {
                    Log("[QueryHandler] parsedResponse.ToolCalls was null. Initializing empty list.");
                    parsedResponse.ToolCalls = new List<StructuredToolCall>();
                }

                Log("[QueryHandler] parsedResponse.ToolCalls count: " + parsedResponse.ToolCalls.Count);

                for (var i = 0; i < parsedResponse.ToolCalls.Count; i++)
                {
                    var toolCall = parsedResponse.ToolCalls[i];

                    if (toolCall == null)
                    {
                        LogWarning("[QueryHandler] ToolCalls[" + i + "] was null.");
                        continue;
                    }

                    Log("[QueryHandler] ToolCalls[" + i + "] toolName: " + toolCall.ToolName);

                    if (toolCall.ToolPayload != null)
                    {
                        Log("[QueryHandler] ToolCalls[" + i + "] payload: " + JsonConvert.SerializeObject(toolCall.ToolPayload));
                    }
                    else
                    {
                        Log("[QueryHandler] ToolCalls[" + i + "] payload was null.");
                    }
                }

                parsedResponse.reply = parsedResponse.reply.Trim();

                structuredAssistantResponse = parsedResponse;

                Log("[QueryHandler] StructuredAssistantResponse parsing succeeded.");

                return true;
            }
            catch (Exception exception)
            {
                LogWarning("[QueryHandler] JSON parse exception full: " + exception);
                LogWarning("[QueryHandler] JSON parse exception type: " + exception.GetType().FullName);
                LogWarning("[QueryHandler] JSON parse exception message: " + exception.Message);
                LogWarning("[QueryHandler] JSON parse exception stack: " + exception.StackTrace);
                LogWarning("[QueryHandler] JSON that failed to deserialize:\n" + cleanedJson);

                return false;
            }
        }

        private string ExtractLikelyJsonObject(string rawResponse)
        {
            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                return null;
            }

            var trimmedResponse = rawResponse.Trim();

            var firstBraceIndex = trimmedResponse.IndexOf('{');
            var lastBraceIndex = trimmedResponse.LastIndexOf('}');

            if (firstBraceIndex >= 0 && lastBraceIndex > firstBraceIndex)
            {
                return trimmedResponse.Substring(firstBraceIndex, lastBraceIndex - firstBraceIndex + 1);
            }

            return null;
        }

        private void AddConversationMessage(string role, string content, string localTimestampDisplay)
        {
            var conversationMessage = new ConversationMessage(role, content, localTimestampDisplay);
            _conversationHistory.Add(conversationMessage);

            var inspectorMessage = new InspectorChatMessage(role, content, localTimestampDisplay);
            _inspectorConversationHistory.Add(inspectorMessage);

            RefreshStats();
            MarkDirty();
        }

        private void TrimConversationHistoryToLimit()
        {
            if (_maxRetainedConversationMessages <= 0)
            {
                return;
            }

            while (_conversationHistory.Count > _maxRetainedConversationMessages)
            {
                _conversationHistory.RemoveAt(0);
            }

            while (_inspectorConversationHistory.Count > _maxRetainedConversationMessages)
            {
                _inspectorConversationHistory.RemoveAt(0);
            }

            RefreshStats();
            MarkDirty();
        }

        private void RefreshStats()
        {
            _storedConversationMessageCount = _conversationHistory.Count;
            _userMessageCount = 0;
            _assistantMessageCount = 0;
            _currentLocalAustinTimeDisplay = TimeUtility.GetCurrentLocalAustinTimeDisplay();

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var message = _conversationHistory[i];

                if (message == null || string.IsNullOrWhiteSpace(message.Role))
                {
                    continue;
                }

                if (string.Equals(message.Role, "user", StringComparison.OrdinalIgnoreCase))
                {
                    _userMessageCount++;
                    continue;
                }

                if (string.Equals(message.Role, "assistant", StringComparison.OrdinalIgnoreCase))
                {
                    _assistantMessageCount++;
                }
            }
        }

        private string GetHistoryFilePath()
        {
            var directoryPath = Application.persistentDataPath;

            try
            {
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }
            }
            catch (Exception exception)
            {
                LogWarning("[QueryHandler] Failed to ensure persistence directory exists: " + exception.Message);
            }

            return Path.Combine(directoryPath, _historyFileName);
        }

        private void LoadHistoryFromDisk()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();

            var filePath = GetHistoryFilePath();

            if (!File.Exists(filePath))
            {
                Log("[QueryHandler] No existing conversation history file found at: " + filePath);
                MarkDirty();
                return;
            }

            try
            {
                var json = File.ReadAllText(filePath);

                if (string.IsNullOrWhiteSpace(json))
                {
                    LogWarning("[QueryHandler] Conversation history file was empty.");
                    MarkDirty();
                    return;
                }

                var fileData = JsonConvert.DeserializeObject<ConversationHistoryFileData>(json);

                if (fileData?.ConversationHistory == null)
                {
                    LogWarning("[QueryHandler] Conversation history file did not contain valid history data.");
                    MarkDirty();
                    return;
                }

                for (var i = 0; i < fileData.ConversationHistory.Count; i++)
                {
                    var message = fileData.ConversationHistory[i];

                    if (message == null)
                    {
                        continue;
                    }

                    _conversationHistory.Add(message);
                    _inspectorConversationHistory.Add(
                        new InspectorChatMessage(message.Role, message.Content, message.LocalTimestampDisplay));
                }

                TrimConversationHistoryToLimit();
                Log("[QueryHandler] Loaded conversation history from disk: " + filePath);
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Failed to load conversation history: " + exception);
            }

            RefreshStats();
            MarkDirty();
        }

        private void SaveHistoryToDisk()
        {
            var filePath = GetHistoryFilePath();

            try
            {
                var fileData = new ConversationHistoryFileData
                {
                    ConversationHistory = new List<ConversationMessage>(_conversationHistory)
                };

                var json = JsonConvert.SerializeObject(fileData, Formatting.Indented);
                var tempFilePath = filePath + ".tmp";

                File.WriteAllText(tempFilePath, json);

                if (File.Exists(filePath))
                {
                    File.Delete(filePath);
                }

                File.Move(tempFilePath, filePath);
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Failed to save conversation history: " + exception);
            }

            RefreshStats();
            MarkDirty();
        }

#if UNITY_EDITOR
        private void MarkDirty()
        {
            UnityEditor.EditorUtility.SetDirty(this);
        }
#else
        private void MarkDirty() {}
#endif

        [Serializable]
        private class ModelInputMessageEnvelope
        {
            public string local_time_austin;
            public string current_query_source;
            public string message;
        }

        [Serializable]
        public class ConversationMessage
        {
            public string Role;
            public string Content;
            public string LocalTimestampDisplay;

            public ConversationMessage(string role, string content, string localTimestampDisplay)
            {
                Role = role;
                Content = content;
                LocalTimestampDisplay = localTimestampDisplay;
            }
        }

        [Serializable]
        public class InspectorChatMessage
        {
            [ReadOnly]
            [SerializeField] private string _role;

            [ReadOnly]
            [SerializeField] private string _localTimestampDisplay;

            [TextArea(2, 8)]
            [ReadOnly]
            [SerializeField] private string _content;

            public string Role => _role;
            public string LocalTimestampDisplay => _localTimestampDisplay;
            public string Content => _content;

            public InspectorChatMessage(string role, string content, string localTimestampDisplay)
            {
                _role = role;
                _content = content;
                _localTimestampDisplay = localTimestampDisplay;
            }
        }

        [JsonConverter(typeof(StringEnumConverter))]
        public enum AssistantConversationState
        {
            Continue,
            End,
            Reset
        }

        [JsonConverter(typeof(StringEnumConverter))]
        public enum AssistantEmotionResponse
        {
            Neutral,
            Pissed,
            MildlyHappy,
            Ecstatic,
            Annoyed,
            Surprised
        }

        [Serializable]
        public class StructuredAssistantResponse
        {
            public string reply;

            [JsonProperty("conversationState")]
            public AssistantConversationState ConversationState = AssistantConversationState.Continue;

            [JsonProperty("emotion")]
            public AssistantEmotionResponse Emotion = AssistantEmotionResponse.Neutral;

            [JsonProperty("toolCalls")]
            public List<StructuredToolCall> ToolCalls = new List<StructuredToolCall>();
        }

        [Serializable]
        public class StructuredToolCall
        {
            [JsonProperty("toolName")]
            public string ToolName = "None";

            [JsonProperty("toolPayload")]
            public object ToolPayload;
        }

        [Serializable]
        public class ConversationHistoryFileData
        {
            public List<ConversationMessage> ConversationHistory = new List<ConversationMessage>();
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey```
