// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using Configuration;
using NaughtyAttributes;
using Newtonsoft.Json;
using Runtime.Reasoning.DataTypes;
using Runtime.Utilities;
using UnityEngine;

namespace Runtime.Reasoning
{
    public class QueryHandler : PearlBehaviour
    {
        private bool _includeSystemPrompt = true;
        private int _maxRetainedConversationMessages => GlobalManager.I.Configuration.MaxRetainedConversationMessages;
        private int _maxJsonParseAttempts => GlobalManager.I.Configuration.MaxJsonParseRetries;
        private bool _auditHistoryToDiscord => GlobalManager.I.State.AuditModeEnabled;

        [Header("Persistence")]
        private string _historyFileName => GlobalManager.I.Configuration.ConversationHistoryFileName;

        [Header("History Summarization")]
        [SerializeField] [Range(0.05f, 1.0f)] private float _fractionMessagesToTruncateWhenLimitHit = 0.2f;
        [SerializeField] private int _summarySizeLimitSentences = 20;
        [SerializeField] private string _summaryPrefix = "Summary of older interactions";

        [Header("Stats")]
        [SerializeField] private GameObject _thinkingIndicator;

        [ReadOnly]
        [SerializeField] private int _storedConversationMessageCount;

        [ReadOnly]
        [SerializeField] private int _userMessageCount;

        [ReadOnly]
        [SerializeField] private int _assistantMessageCount;

        [ReadOnly]
        [SerializeField] private string _currentLocalAustinTimeDisplay;

        [Header("Inspector Conversation History")]
        [SerializeField] private List<InspectorChatMessage> _inspectorConversationHistory = new List<InspectorChatMessage>();

        [Header("Helpers")]
        [SerializeField] private StructuredAssistantResponseParser _structuredAssistantResponseParser;
        [SerializeField] private ConversationHistoryStore _conversationHistoryStore;
        [SerializeField] private ConversationHistorySummarizer _conversationHistorySummarizer;

        private readonly List<ConversationMessage> _conversationHistory = new List<ConversationMessage>();

        public void Initialize()
        {
            InitializeHelperComponents();

            LoadHistoryFromDisk();
            RefreshStats();

            if (_thinkingIndicator != null)
            {
                _thinkingIndicator.SetActive(false);
            }

            SetInitialized();
        }

        private void InitializeHelperComponents()
        {
            if (_structuredAssistantResponseParser == null)
            {
                _structuredAssistantResponseParser = GetComponent<StructuredAssistantResponseParser>();

                if (_structuredAssistantResponseParser == null)
                {
                    _structuredAssistantResponseParser = gameObject.AddComponent<StructuredAssistantResponseParser>();
                }
            }

            if (_conversationHistoryStore == null)
            {
                _conversationHistoryStore = GetComponent<ConversationHistoryStore>();

                if (_conversationHistoryStore == null)
                {
                    _conversationHistoryStore = gameObject.AddComponent<ConversationHistoryStore>();
                }
            }

            if (_conversationHistorySummarizer == null)
            {
                _conversationHistorySummarizer = GetComponent<ConversationHistorySummarizer>();

                if (_conversationHistorySummarizer == null)
                {
                    _conversationHistorySummarizer = gameObject.AddComponent<ConversationHistorySummarizer>();
                }
            }
            
            if (_conversationHistorySummarizer != null && _conversationHistoryStore != null)
            {
                _conversationHistorySummarizer.Initialize(_conversationHistoryStore);
                Log("[QueryHandler] ConversationHistorySummarizer initialized with ConversationHistoryStore.");
            }
            else
            {
                LogError("[QueryHandler] Failed to initialize summarizer/store helper references.");
            }
            
            _structuredAssistantResponseParser.SetLogLevel(CurrentLogLevel);
            _conversationHistoryStore.SetLogLevel(CurrentLogLevel);
            _conversationHistorySummarizer.SetLogLevel(CurrentLogLevel);
            
            _conversationHistorySummarizer.Initialize(_conversationHistoryStore);
        }

        [Button("Reset")]
        public void ResetHistory()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();
            SaveHistoryToDisk();
            RefreshStats();

            Log("[QueryHandler] Conversation history reset.");
            Log("[QueryHandler] System prompt is rebuilt fresh on every message. After this reset, the next request will use a freshly built system prompt with empty conversation history.");

            MarkDirty();
        }

        public async void HandleNewMessage(string messageContent, QuerySource source)
        {
            if (string.IsNullOrWhiteSpace(messageContent))
            {
                LogWarning("[QueryHandler] Ignoring empty message.");
                return;
            }

            Log("[QueryHandler] Received new message: " + messageContent);

            if (source != QuerySource.AssistantSelf)
            {
                GlobalManager.I.State.SetLastTimeUserInteractedToNow();
            }

            StructuredAssistantResponse structuredAssistantResponse = null;

            try
            {
                var userTimestamp = TimeUtility.GetCurrentLocalAustinTimeDisplay();
                var outboundMessageHistory = BuildOutboundMessageHistory(messageContent, userTimestamp, source);

                string rawResponse = null;

                if (_thinkingIndicator != null)
                {
                    _thinkingIndicator.SetActive(true);
                }

                for (var attemptIndex = 0; attemptIndex < _maxJsonParseAttempts; attemptIndex++)
                {
                    rawResponse = await GlobalManager.I.LlmClient.SendPromptAsync(
                        outboundMessageHistory,
                        GlobalManager.I.Configuration.LlmModelStandard);

                    Log("[QueryHandler] Raw LLM response attempt " + (attemptIndex + 1) + ": " + rawResponse);

                    if (_structuredAssistantResponseParser.TryParseStructuredAssistantResponse(rawResponse, out structuredAssistantResponse))
                    {
                        break;
                    }

                    LogWarning("[QueryHandler] Failed to parse structured LLM response on attempt " + (attemptIndex + 1) + ".");
                }

                if (structuredAssistantResponse == null)
                {
                    LogError("[QueryHandler] Failed to get valid structured JSON response after " + _maxJsonParseAttempts + " attempts.");
                    return;
                }

                AddConversationMessage("user", messageContent, userTimestamp);
                AddConversationMessage("assistant", structuredAssistantResponse.reply, TimeUtility.GetCurrentLocalAustinTimeDisplay());

                await SummarizeHistoryIfNeededAsync();

                SaveHistoryToDisk();

                if (structuredAssistantResponse.ConversationState == AssistantConversationState.Reset)
                {
                    Log("[QueryHandler] Detected conversation reset request. Resetting history.");
                    ResetHistory();
                }

                SendResponseToSource(
                    structuredAssistantResponse.reply,
                    structuredAssistantResponse.Emotion,
                    messageContent,
                    source,
                    structuredAssistantResponse.ConversationState != AssistantConversationState.End);

                ExecuteToolsIfRequested(structuredAssistantResponse);

                if (structuredAssistantResponse.ConversationState == AssistantConversationState.End)
                {
                    Log("[QueryHandler] Detected end of conversation.");
                }
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Error processing message: " + exception);
            }
            finally
            {
                if (_thinkingIndicator != null)
                {
                    _thinkingIndicator.SetActive(false);
                }
            }
        }
        
        private async System.Threading.Tasks.Task SummarizeHistoryIfNeededAsync()
        {
            if (_conversationHistorySummarizer == null)
            {
                LogError("[QueryHandler] Cannot summarize history because _conversationHistorySummarizer is null.");
                return;
            }

            Log("[QueryHandler] Checking whether history summarization is needed. " +
                "Current message count: " + _conversationHistory.Count +
                ", Max retained message count: " + _maxRetainedConversationMessages);

            var previousConversationHistoryCount = _conversationHistory.Count;

            var summarizedConversationHistory = await _conversationHistorySummarizer.SummarizeHistoryIfNeededAsync(
                _conversationHistory,
                _maxRetainedConversationMessages,
                _fractionMessagesToTruncateWhenLimitHit,
                _summarySizeLimitSentences,
                _summaryPrefix,
                "assistant");

            _conversationHistory.Clear();
            _conversationHistory.AddRange(summarizedConversationHistory);

            Log("[QueryHandler] History summarization check complete. " +
                "Previous count: " + previousConversationHistoryCount +
                ", New count: " + _conversationHistory.Count);

            RebuildInspectorConversationHistoryFromConversationHistory();
            RefreshStats();
            MarkDirty();
        }

        private void ExecuteToolsIfRequested(StructuredAssistantResponse structuredAssistantResponse)
        {
            if (structuredAssistantResponse == null)
            {
                return;
            }

            if (structuredAssistantResponse.ToolCalls == null || structuredAssistantResponse.ToolCalls.Count == 0)
            {
                Log("[QueryHandler] No tools requested.");
                return;
            }

            var toolCallsToExecute = new List<StructuredToolCall>();

            for (var i = 0; i < structuredAssistantResponse.ToolCalls.Count; i++)
            {
                var toolCall = structuredAssistantResponse.ToolCalls[i];

                if (toolCall == null)
                {
                    continue;
                }

                if (string.IsNullOrWhiteSpace(toolCall.ToolName))
                {
                    LogWarning("[QueryHandler] Tool call at index " + i + " had empty toolName. Skipping.");
                    continue;
                }

                if (string.Equals(toolCall.ToolName, "None", StringComparison.OrdinalIgnoreCase))
                {
                    Log("[QueryHandler] Tool call at index " + i + " explicitly requested None. Skipping.");
                    continue;
                }

                toolCallsToExecute.Add(toolCall);
            }

            if (toolCallsToExecute.Count == 0)
            {
                Log("[QueryHandler] No executable tool calls remained after filtering.");
                return;
            }

            for (var i = 0; i < toolCallsToExecute.Count; i++)
            {
                var toolCall = toolCallsToExecute[i];

                var payloadJson = toolCall.ToolPayload == null
                    ? "{}"
                    : JsonConvert.SerializeObject(toolCall.ToolPayload);

                Log("[QueryHandler] Executing tool call " + (i + 1) + "/" + toolCallsToExecute.Count + ": " + toolCall.ToolName);
                Log("[QueryHandler] Tool payload: " + payloadJson);

                var toolExecutedSuccessfully = GlobalManager.I.ToolRouter.TryExecuteTool(
                    toolCall.ToolName,
                    payloadJson,
                    out var executionSummary);

                if (toolExecutedSuccessfully)
                {
                    Log("[QueryHandler] Tool executed successfully. Summary: " + executionSummary);

                    if (_auditHistoryToDiscord && !string.IsNullOrWhiteSpace(executionSummary))
                    {
                        GlobalManager.I.DiscordClient.SendDirectMessage("**Tool execution:** " + executionSummary);
                    }
                }
                else
                {
                    LogWarning("[QueryHandler] Tool execution failed. Summary: " + executionSummary);

                    if (_auditHistoryToDiscord && !string.IsNullOrWhiteSpace(executionSummary))
                    {
                        GlobalManager.I.DiscordClient.SendDirectMessage("**Tool execution failed:** " + executionSummary);
                    }
                }
            }
        }

        private void SendResponseToSource(
            string cleanedResponse,
            AssistantEmotionResponse emotion,
            string originalQuery,
            QuerySource source,
            bool promptAfterwards)
        {
            if (source == QuerySource.Discord)
            {
                GlobalManager.I.DiscordClient.SendDirectMessage(cleanedResponse);
                return;
            }

            if (source == QuerySource.Speech || source == QuerySource.AssistantSelf)
            {
                GlobalManager.I.SpeakAndEmoteController.SendPhraseAndEmotion(cleanedResponse, emotion, promptAfterwards);

                if (_auditHistoryToDiscord)
                {
                    if (source == QuerySource.AssistantSelf)
                    {
                        var auditMessage =
                            $"**Proactive thought from myself:** \"{originalQuery}\"\n\n**Emotion:** {emotion}\n\n**Spoken prompt sent to user:** \"{cleanedResponse}\"";
                        GlobalManager.I.DiscordClient.SendDirectMessage(auditMessage);
                    }
                    else
                    {
                        var auditMessage =
                            $"**Spoken query from user:** \"{originalQuery}\"\n\n**Emotion:** {emotion}\n\n**Spoken response sent to user:** \"{cleanedResponse}\"";
                        GlobalManager.I.DiscordClient.SendDirectMessage(auditMessage);
                    }
                }
            }
        }

        private List<OpenRouterChatClient.ChatMessage> BuildOutboundMessageHistory(
            string newestUserMessageContent,
            string newestUserTimestamp,
            QuerySource source)
        {
            var outboundMessageHistory = new List<OpenRouterChatClient.ChatMessage>();

            _currentLocalAustinTimeDisplay = TimeUtility.GetCurrentLocalAustinTimeDisplay();

            var systemPrompt = GlobalManager.I.PromptBuilder.BuildSystemPrompt(source, true);

            var systemPromptWithTimeContext =
                systemPrompt + "\n\n" +
                "local time: " + _currentLocalAustinTimeDisplay + "\n";

            Log("[QueryHandler] Full system prompt for this message:\n" + systemPromptWithTimeContext);
            Log("[QueryHandler] Conversation history count included in outbound prompt: " + _conversationHistory.Count);
            Log("[QueryHandler] Current query source: " + source);

            if (_includeSystemPrompt && !string.IsNullOrWhiteSpace(systemPromptWithTimeContext))
            {
                outboundMessageHistory.Add(new OpenRouterChatClient.ChatMessage("system", systemPromptWithTimeContext));
            }

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var existingMessage = _conversationHistory[i];

                if (_conversationHistoryStore.IsSummaryMessage(existingMessage, _summaryPrefix))
                {
                    outboundMessageHistory.Add(
                        new OpenRouterChatClient.ChatMessage(
                            existingMessage.Role,
                            existingMessage.Content));

                    continue;
                }

                outboundMessageHistory.Add(
                    new OpenRouterChatClient.ChatMessage(
                        existingMessage.Role,
                        FormatMessageForModel(existingMessage.Content, existingMessage.LocalTimestampDisplay, null)));
            }

            outboundMessageHistory.Add(
                new OpenRouterChatClient.ChatMessage(
                    "user",
                    FormatMessageForModel(newestUserMessageContent, newestUserTimestamp, source)));

            return outboundMessageHistory;
        }

        private string FormatMessageForModel(string content, string localTimestampDisplay, QuerySource? source)
        {
            var messagePrefix = "";

            if (source == QuerySource.AssistantSelf)
            {
                messagePrefix = "[This message is from the assistant speaking to itself as part of internal reflection and trying to think of something to ask the user proactively]\n\n";
            }

            var messageEnvelope = new ModelInputMessageEnvelope
            {
                local_time_austin = localTimestampDisplay,
                message = messagePrefix + content
            };

            if (source.HasValue)
            {
                messageEnvelope.current_query_source = source.Value.ToString();
            }

            return JsonConvert.SerializeObject(messageEnvelope, Formatting.None);
        }

        private void AddConversationMessage(string role, string content, string localTimestampDisplay)
        {
            var conversationMessage = new ConversationMessage(role, content, localTimestampDisplay);
            _conversationHistory.Add(conversationMessage);

            var inspectorMessage = new InspectorChatMessage(role, content, localTimestampDisplay);
            _inspectorConversationHistory.Add(inspectorMessage);

            RefreshStats();
            MarkDirty();
        }

        private void RefreshStats()
        {
            _storedConversationMessageCount = _conversationHistory.Count;
            _userMessageCount = 0;
            _assistantMessageCount = 0;
            _currentLocalAustinTimeDisplay = TimeUtility.GetCurrentLocalAustinTimeDisplay();

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var message = _conversationHistory[i];

                if (message == null || string.IsNullOrWhiteSpace(message.Role))
                {
                    continue;
                }

                if (string.Equals(message.Role, "user", StringComparison.OrdinalIgnoreCase))
                {
                    _userMessageCount++;
                    continue;
                }

                if (string.Equals(message.Role, "assistant", StringComparison.OrdinalIgnoreCase))
                {
                    _assistantMessageCount++;
                }
            }
        }

        private void RebuildInspectorConversationHistoryFromConversationHistory()
        {
            _inspectorConversationHistory.Clear();

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var message = _conversationHistory[i];

                if (message == null)
                {
                    continue;
                }

                _inspectorConversationHistory.Add(
                    new InspectorChatMessage(
                        message.Role,
                        message.Content,
                        message.LocalTimestampDisplay));
            }
        }

        private void LoadHistoryFromDisk()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();

            var loadedHistory = _conversationHistoryStore.LoadConversationHistory(_historyFileName);

            for (var i = 0; i < loadedHistory.Count; i++)
            {
                var message = loadedHistory[i];

                if (message == null)
                {
                    continue;
                }

                _conversationHistory.Add(message);
            }

            RebuildInspectorConversationHistoryFromConversationHistory();
            RefreshStats();
            MarkDirty();
        }

        private void SaveHistoryToDisk()
        {
            _conversationHistoryStore.SaveConversationHistory(_historyFileName, _conversationHistory);

            RefreshStats();
            MarkDirty();
        }

#if UNITY_EDITOR
        private void MarkDirty()
        {
            UnityEditor.EditorUtility.SetDirty(this);
        }
#else
        private void MarkDirty() {}
#endif
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey