// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Configuration;
using NaughtyAttributes;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Runtime.Reasoning.DataTypes;
using Runtime.Utilities;
using UnityEngine;

namespace Runtime.Reasoning
{
    public class QueryHandler : PearlBehaviour
    {
        private bool _includeSystemPrompt = true;
        private int _maxRetainedConversationMessages => GlobalManager.I.Configuration.MaxRetainedConversationMessages;
        private int _maxJsonParseAttempts => GlobalManager.I.Configuration.MaxJsonParseRetries;
        private bool _auditHistoryToDiscord => GlobalManager.I.State.AuditModeEnabled;

        [Header("Persistence")]
        private string _historyFileName => GlobalManager.I.Configuration.ConversationHistoryFileName;

        [Header("Stats")]
        [ReadOnly]
        [SerializeField] private int _storedConversationMessageCount;

        [ReadOnly]
        [SerializeField] private int _userMessageCount;

        [ReadOnly]
        [SerializeField] private int _assistantMessageCount;

        [ReadOnly]
        [SerializeField] private string _currentLocalAustinTimeDisplay;

        [Header("Inspector Conversation History")]
        [SerializeField] private List<InspectorChatMessage> _inspectorConversationHistory = new List<InspectorChatMessage>();

        private readonly List<ConversationMessage> _conversationHistory = new List<ConversationMessage>();

        public event Action<AssistantModeResponse> OnModeChangedEvent;
        public event Action<AssistantToggleResponse> OnAuditModeChangedEvent;
        public event Action<AssistantToggleResponse> OnQuietModeChangedEvent;
        public event Action<AssistantToggleResponse> OnRespondToNameChangedEvent;

        public void Initialize()
        {
            LoadHistoryFromDisk();
            RefreshStats();
            
            OnModeChangedEvent += OnModeChanged;
            OnAuditModeChangedEvent += OnAuditModeChanged;
            OnQuietModeChangedEvent += OnQuietModeChanged;
            OnRespondToNameChangedEvent += OnRespondToNameChanged;
            
            SetInitialized();
        }
        
        public void OnDestroy()
        {
            OnModeChangedEvent -= OnModeChanged;
            OnAuditModeChangedEvent -= OnAuditModeChanged;
            OnQuietModeChangedEvent -= OnQuietModeChanged;
            OnRespondToNameChangedEvent -= OnRespondToNameChanged;
        }

        [Button("Reset")]
        public void ResetHistory()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();
            SaveHistoryToDisk();
            RefreshStats();
            Log("[QueryHandler] Conversation history reset.");
            MarkDirty();
        }

        public async void HandleNewMessage(string messageContent, QuerySource source)
        {
            if (string.IsNullOrWhiteSpace(messageContent))
            {
                LogWarning("[QueryHandler] Ignoring empty message.");
                return;
            }

            Log("[QueryHandler] Received new message: " + messageContent);

            try
            {
                var userTimestamp = TimeUtility.GetCurrentLocalAustinTimeDisplay();
                var outboundMessageHistory = BuildOutboundMessageHistory(messageContent, userTimestamp, source);

                StructuredAssistantResponse structuredAssistantResponse = null;
                string rawResponse = null;

                for (var attemptIndex = 0; attemptIndex < _maxJsonParseAttempts; attemptIndex++)
                {
                    rawResponse = await GlobalManager.I.LlmClient.SendPromptAsync(outboundMessageHistory, GlobalManager.I.Configuration.LlmModelStandard);
                    Log("[QueryHandler] Raw LLM response attempt " + (attemptIndex + 1) + ": " + rawResponse);

                    if (TryParseStructuredAssistantResponse(rawResponse, out structuredAssistantResponse))
                    {
                        break;
                    }

                    LogWarning("[QueryHandler] Failed to parse structured LLM response on attempt " + (attemptIndex + 1) + ".");
                }

                if (structuredAssistantResponse == null)
                {
                    LogError("[QueryHandler] Failed to get valid structured JSON response after " + _maxJsonParseAttempts + " attempts.");
                    return;
                }

                ApplyStructuredAssistantResponseChanges(structuredAssistantResponse);

                AddConversationMessage("user", messageContent, userTimestamp);
                AddConversationMessage("assistant", structuredAssistantResponse.reply, TimeUtility.GetCurrentLocalAustinTimeDisplay());
                TrimConversationHistoryToLimit();
                SaveHistoryToDisk();

                if (structuredAssistantResponse.ConversationState == AssistantConversationState.Reset)
                {
                    Log("[QueryHandler] Detected conversation reset request. Resetting history.");
                    ResetHistory();
                }

                SendResponseToSource(
                    structuredAssistantResponse.reply,
                    messageContent,
                    source,
                    structuredAssistantResponse.ConversationState != AssistantConversationState.End);

                if (structuredAssistantResponse.ConversationState == AssistantConversationState.End)
                {
                    Log("[QueryHandler] Detected end of conversation.");
                }
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Error processing message: " + exception);
            }
        }

        private void ApplyStructuredAssistantResponseChanges(StructuredAssistantResponse structuredAssistantResponse)
        {
            if (structuredAssistantResponse == null)
            {
                return;
            }

            if (structuredAssistantResponse.Mode != AssistantModeResponse.NoChange)
            {
                Log("[QueryHandler] Invoking OnModeChanged: " + structuredAssistantResponse.Mode);
                OnModeChangedEvent?.Invoke(structuredAssistantResponse.Mode);
            }

            if (structuredAssistantResponse.AuditMode != AssistantToggleResponse.NoChange)
            {
                Log("[QueryHandler] Invoking OnAuditModeChanged: " + structuredAssistantResponse.AuditMode);
                OnAuditModeChangedEvent?.Invoke(structuredAssistantResponse.AuditMode);
            }

            if (structuredAssistantResponse.QuietMode != AssistantToggleResponse.NoChange)
            {
                Log("[QueryHandler] Invoking OnQuietModeChanged: " + structuredAssistantResponse.QuietMode);
                OnQuietModeChangedEvent?.Invoke(structuredAssistantResponse.QuietMode);
            }

            if (structuredAssistantResponse.RespondToName != AssistantToggleResponse.NoChange)
            {
                Log("[QueryHandler] Invoking OnRespondToNameChanged: " + structuredAssistantResponse.RespondToName);
                OnRespondToNameChangedEvent?.Invoke(structuredAssistantResponse.RespondToName);
            }
        }
        
        private void OnModeChanged(AssistantModeResponse newMode)
        {
            // TODO-RPB: Implement mode changes.
            Log("[QueryHandler] Mode change requested: " + newMode);
            switch (newMode)
            {
                case AssistantModeResponse.NoChange:
                    break;
                case AssistantModeResponse.Chill:
                    GlobalManager.I.State.CurrentMode = BehaviourMode.Chill;
                    break;
                case AssistantModeResponse.ProductiveHobby:
                    GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveHobby;
                    break;
                case AssistantModeResponse.ProductiveWork:
                    GlobalManager.I.State.CurrentMode = BehaviourMode.ProductiveWork;
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(newMode), newMode, null);
            }
        }
        
        private void OnAuditModeChanged(AssistantToggleResponse newAuditMode)
        {
            Log("[QueryHandler] Audit mode change requested: " + newAuditMode);

            switch (newAuditMode)
            {
                case AssistantToggleResponse.NoChange:
                    break;
                case AssistantToggleResponse.On:
                    GlobalManager.I.State.AuditModeEnabled = true;
                    break;
                case AssistantToggleResponse.Off:
                    GlobalManager.I.State.AuditModeEnabled = false;
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(newAuditMode), newAuditMode, null);
            }
        }
        
        private void OnQuietModeChanged(AssistantToggleResponse newQuietMode)
        {
            Log("[QueryHandler] Quiet mode change requested: " + newQuietMode);
            
            switch (newQuietMode)
            {
                case AssistantToggleResponse.NoChange:
                    break;
                case AssistantToggleResponse.On:
                    GlobalManager.I.State.QuietModeEnabled = true;
                    break;
                case AssistantToggleResponse.Off:
                    GlobalManager.I.State.QuietModeEnabled = false;
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(newQuietMode), newQuietMode, null);
            }
        }
        
        private void OnRespondToNameChanged(AssistantToggleResponse newRespondToName)
        {
            Log("[QueryHandler] Respond to name change requested: " + newRespondToName);

            switch (newRespondToName)
            {
                case AssistantToggleResponse.NoChange:
                    break;
                case AssistantToggleResponse.On:
                    GlobalManager.I.State.RespondToNameEnabled = true;
                    break;
                case AssistantToggleResponse.Off:
                    GlobalManager.I.State.RespondToNameEnabled = false;
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(newRespondToName), newRespondToName, null);
            }
        }
        

        private void SendResponseToSource(string cleanedResponse, string originalQuery, QuerySource source, bool promptAfterwards)
        {
            if (source == QuerySource.Discord)
            {
                GlobalManager.I.DiscordClient.SendDirectMessage(cleanedResponse);
            }
            else if (source == QuerySource.Speech)
            {
                GlobalManager.I.SpeakAndEmoteController.SendPhraseAndGetEmotion(cleanedResponse, promptAfterwards);

                if (_auditHistoryToDiscord)
                {
                    var auditMessage = $"**Spoken query from user:** \"{originalQuery}\"\n\n**Spoken response sent to user:** \"{cleanedResponse}\"";
                    GlobalManager.I.DiscordClient.SendDirectMessage(auditMessage);
                }
            }
        }

        private List<OpenRouterChatClient.ChatMessage> BuildOutboundMessageHistory(
            string newestUserMessageContent,
            string newestUserTimestamp,
            QuerySource source)
        {
            var outboundMessageHistory = new List<OpenRouterChatClient.ChatMessage>();

            _currentLocalAustinTimeDisplay = TimeUtility.GetCurrentLocalAustinTimeDisplay();

            var systemPrompt = PromptBuilder.BuildSystemPrompt(source, true);

            var systemPromptWithTimeContext =
                systemPrompt + "\n\n" +
                "local time: " + _currentLocalAustinTimeDisplay + "\n";

            if (_includeSystemPrompt && !string.IsNullOrWhiteSpace(systemPrompt))
            {
                outboundMessageHistory.Add(new OpenRouterChatClient.ChatMessage("system", systemPromptWithTimeContext));
            }

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var existingMessage = _conversationHistory[i];

                outboundMessageHistory.Add(
                    new OpenRouterChatClient.ChatMessage(
                        existingMessage.Role,
                        FormatMessageForModel(existingMessage.Content, existingMessage.LocalTimestampDisplay, null)));
            }

            outboundMessageHistory.Add(
                new OpenRouterChatClient.ChatMessage(
                    "user",
                    FormatMessageForModel(newestUserMessageContent, newestUserTimestamp, source)));

            return outboundMessageHistory;
        }

        private string FormatMessageForModel(string content, string localTimestampDisplay, QuerySource? source)
        {
            var messageEnvelope = new ModelInputMessageEnvelope
            {
                local_time_austin = localTimestampDisplay,
                message = content
            };

            if (source.HasValue)
            {
                messageEnvelope.current_query_source = source.Value.ToString();
            }

            return JsonConvert.SerializeObject(messageEnvelope, Formatting.None);
        }

        private bool TryParseStructuredAssistantResponse(string rawResponse, out StructuredAssistantResponse structuredAssistantResponse)
        {
            structuredAssistantResponse = null;

            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                return false;
            }

            var cleanedJson = ExtractLikelyJsonObject(rawResponse);

            if (string.IsNullOrWhiteSpace(cleanedJson))
            {
                return false;
            }

            try
            {
                var parsedResponse = JsonConvert.DeserializeObject<StructuredAssistantResponse>(cleanedJson);

                if (parsedResponse == null)
                {
                    return false;
                }

                if (string.IsNullOrWhiteSpace(parsedResponse.reply))
                {
                    return false;
                }

                parsedResponse.reply = parsedResponse.reply.Trim();

                structuredAssistantResponse = parsedResponse;
                return true;
            }
            catch (Exception exception)
            {
                LogWarning("[QueryHandler] JSON parse exception: " + exception.Message);
                return false;
            }
        }

        private string ExtractLikelyJsonObject(string rawResponse)
        {
            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                return null;
            }

            var trimmedResponse = rawResponse.Trim();

            var firstBraceIndex = trimmedResponse.IndexOf('{');
            var lastBraceIndex = trimmedResponse.LastIndexOf('}');

            if (firstBraceIndex >= 0 && lastBraceIndex > firstBraceIndex)
            {
                return trimmedResponse.Substring(firstBraceIndex, lastBraceIndex - firstBraceIndex + 1);
            }

            return null;
        }

        private void AddConversationMessage(string role, string content, string localTimestampDisplay)
        {
            var conversationMessage = new ConversationMessage(role, content, localTimestampDisplay);
            _conversationHistory.Add(conversationMessage);

            var inspectorMessage = new InspectorChatMessage(role, content, localTimestampDisplay);
            _inspectorConversationHistory.Add(inspectorMessage);

            RefreshStats();
            MarkDirty();
        }

        private void TrimConversationHistoryToLimit()
        {
            if (_maxRetainedConversationMessages <= 0)
            {
                return;
            }

            while (_conversationHistory.Count > _maxRetainedConversationMessages)
            {
                _conversationHistory.RemoveAt(0);
            }

            while (_inspectorConversationHistory.Count > _maxRetainedConversationMessages)
            {
                _inspectorConversationHistory.RemoveAt(0);
            }

            RefreshStats();
            MarkDirty();
        }

        private void RefreshStats()
        {
            _storedConversationMessageCount = _conversationHistory.Count;
            _userMessageCount = 0;
            _assistantMessageCount = 0;
            _currentLocalAustinTimeDisplay = TimeUtility.GetCurrentLocalAustinTimeDisplay();

            for (var i = 0; i < _conversationHistory.Count; i++)
            {
                var message = _conversationHistory[i];

                if (message == null || string.IsNullOrWhiteSpace(message.Role))
                {
                    continue;
                }

                if (string.Equals(message.Role, "user", StringComparison.OrdinalIgnoreCase))
                {
                    _userMessageCount++;
                    continue;
                }

                if (string.Equals(message.Role, "assistant", StringComparison.OrdinalIgnoreCase))
                {
                    _assistantMessageCount++;
                }
            }
        }

        private string GetHistoryFilePath()
        {
            var directoryPath = Application.persistentDataPath;

            try
            {
                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }
            }
            catch (Exception exception)
            {
                LogWarning("[QueryHandler] Failed to ensure persistence directory exists: " + exception.Message);
            }

            return Path.Combine(directoryPath, _historyFileName);
        }

        private void LoadHistoryFromDisk()
        {
            _conversationHistory.Clear();
            _inspectorConversationHistory.Clear();

            var filePath = GetHistoryFilePath();

            if (!File.Exists(filePath))
            {
                Log("[QueryHandler] No existing conversation history file found at: " + filePath);
                MarkDirty();
                return;
            }

            try
            {
                var json = File.ReadAllText(filePath);

                if (string.IsNullOrWhiteSpace(json))
                {
                    LogWarning("[QueryHandler] Conversation history file was empty.");
                    MarkDirty();
                    return;
                }

                var fileData = JsonConvert.DeserializeObject<ConversationHistoryFileData>(json);

                if (fileData?.ConversationHistory == null)
                {
                    LogWarning("[QueryHandler] Conversation history file did not contain valid history data.");
                    MarkDirty();
                    return;
                }

                for (var i = 0; i < fileData.ConversationHistory.Count; i++)
                {
                    var message = fileData.ConversationHistory[i];

                    if (message == null)
                    {
                        continue;
                    }

                    _conversationHistory.Add(message);
                    _inspectorConversationHistory.Add(
                        new InspectorChatMessage(message.Role, message.Content, message.LocalTimestampDisplay));
                }

                TrimConversationHistoryToLimit();
                Log("[QueryHandler] Loaded conversation history from disk: " + filePath);
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Failed to load conversation history: " + exception);
            }

            RefreshStats();
            MarkDirty();
        }

        private void SaveHistoryToDisk()
        {
            var filePath = GetHistoryFilePath();

            try
            {
                var fileData = new ConversationHistoryFileData
                {
                    ConversationHistory = new List<ConversationMessage>(_conversationHistory)
                };

                var json = JsonConvert.SerializeObject(fileData, Formatting.Indented);
                var tempFilePath = filePath + ".tmp";

                File.WriteAllText(tempFilePath, json);

                if (File.Exists(filePath))
                {
                    File.Delete(filePath);
                }

                File.Move(tempFilePath, filePath);
            }
            catch (Exception exception)
            {
                LogError("[QueryHandler] Failed to save conversation history: " + exception);
            }

            RefreshStats();
            MarkDirty();
        }

#if UNITY_EDITOR
        private void MarkDirty()
        {
            UnityEditor.EditorUtility.SetDirty(this);
        }
#else
        private void MarkDirty() {}
#endif

        [Serializable]
        private class ModelInputMessageEnvelope
        {
            public string local_time_austin;
            public string current_query_source;
            public string message;
        }

        [Serializable]
        public class ConversationMessage
        {
            public string Role;
            public string Content;
            public string LocalTimestampDisplay;

            public ConversationMessage(string role, string content, string localTimestampDisplay)
            {
                Role = role;
                Content = content;
                LocalTimestampDisplay = localTimestampDisplay;
            }
        }

        [Serializable]
        public class InspectorChatMessage
        {
            [ReadOnly]
            [SerializeField] private string _role;

            [ReadOnly]
            [SerializeField] private string _localTimestampDisplay;

            [TextArea(2, 8)]
            [ReadOnly]
            [SerializeField] private string _content;

            public string Role => _role;
            public string LocalTimestampDisplay => _localTimestampDisplay;
            public string Content => _content;

            public InspectorChatMessage(string role, string content, string localTimestampDisplay)
            {
                _role = role;
                _content = content;
                _localTimestampDisplay = localTimestampDisplay;
            }
        }

        [JsonConverter(typeof(StringEnumConverter))]
        public enum AssistantConversationState
        {
            Continue,
            End,
            Reset
        }

        [JsonConverter(typeof(StringEnumConverter))]
        public enum AssistantModeResponse
        {
            NoChange,
            Chill,
            ProductiveHobby,
            ProductiveWork
        }

        [JsonConverter(typeof(StringEnumConverter))]
        public enum AssistantToggleResponse
        {
            NoChange,
            On,
            Off
        }

        [Serializable]
        private class StructuredAssistantResponse
        {
            public string reply;

            [JsonProperty("conversationState")]
            public AssistantConversationState ConversationState = AssistantConversationState.Continue;

            [JsonProperty("mode")]
            public AssistantModeResponse Mode = AssistantModeResponse.NoChange;

            [JsonProperty("auditMode")]
            public AssistantToggleResponse AuditMode = AssistantToggleResponse.NoChange;

            [JsonProperty("quietMode")]
            public AssistantToggleResponse QuietMode = AssistantToggleResponse.NoChange;

            [JsonProperty("respondToName")]
            public AssistantToggleResponse RespondToName = AssistantToggleResponse.NoChange;
        }

        [Serializable]
        private class ConversationHistoryFileData
        {
            public List<ConversationMessage> ConversationHistory = new List<ConversationMessage>();
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey