// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using Runtime.Reasoning.DataTypes;

namespace Runtime.Reasoning
{
    public class StructuredAssistantResponseParser : PearlBehaviour
    {
        public bool TryParseStructuredAssistantResponse(string rawResponse, out StructuredAssistantResponse structuredAssistantResponse)
        {
            structuredAssistantResponse = null;

            Log("[StructuredAssistantResponseParser] TryParseStructuredAssistantResponse called.");

            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                LogWarning("[StructuredAssistantResponseParser] rawResponse was null or whitespace.");
                return false;
            }

            Log("[StructuredAssistantResponseParser] rawResponse length: " + rawResponse.Length);
            Log("[StructuredAssistantResponseParser] rawResponse preview: " + rawResponse.Substring(0, Math.Min(rawResponse.Length, 500)));

            var cleanedJson = ExtractLikelyJsonObject(rawResponse);

            if (string.IsNullOrWhiteSpace(cleanedJson))
            {
                LogWarning("[StructuredAssistantResponseParser] ExtractLikelyJsonObject returned null or whitespace.");
                return false;
            }

            Log("[StructuredAssistantResponseParser] cleanedJson length: " + cleanedJson.Length);
            Log("[StructuredAssistantResponseParser] cleanedJson preview: " + cleanedJson.Substring(0, Math.Min(cleanedJson.Length, 500)));

            try
            {
                Log("[StructuredAssistantResponseParser] Attempting JSON deserialization into StructuredAssistantResponse...");

                var parsedResponse = Newtonsoft.Json.JsonConvert.DeserializeObject<StructuredAssistantResponse>(cleanedJson);

                if (parsedResponse == null)
                {
                    LogWarning("[StructuredAssistantResponseParser] Deserialization succeeded but parsedResponse was null.");
                    return false;
                }

                Log("[StructuredAssistantResponseParser] Deserialization succeeded.");

                if (string.IsNullOrWhiteSpace(parsedResponse.reply))
                {
                    LogWarning("[StructuredAssistantResponseParser] parsedResponse.reply was null or whitespace.");
                    return false;
                }

                Log("[StructuredAssistantResponseParser] parsedResponse.reply: " + parsedResponse.reply);

                if (parsedResponse.ToolCalls == null)
                {
                    Log("[StructuredAssistantResponseParser] parsedResponse.ToolCalls was null. Initializing empty list.");
                    parsedResponse.ToolCalls = new System.Collections.Generic.List<StructuredToolCall>();
                }

                Log("[StructuredAssistantResponseParser] parsedResponse.ToolCalls count: " + parsedResponse.ToolCalls.Count);

                for (var i = 0; i < parsedResponse.ToolCalls.Count; i++)
                {
                    var toolCall = parsedResponse.ToolCalls[i];

                    if (toolCall == null)
                    {
                        LogWarning("[StructuredAssistantResponseParser] ToolCalls[" + i + "] was null.");
                        continue;
                    }

                    Log("[StructuredAssistantResponseParser] ToolCalls[" + i + "] toolName: " + toolCall.ToolName);

                    if (toolCall.ToolPayload != null)
                    {
                        Log("[StructuredAssistantResponseParser] ToolCalls[" + i + "] payload: " + Newtonsoft.Json.JsonConvert.SerializeObject(toolCall.ToolPayload));
                    }
                    else
                    {
                        Log("[StructuredAssistantResponseParser] ToolCalls[" + i + "] payload was null.");
                    }
                }

                parsedResponse.reply = parsedResponse.reply.Trim();

                structuredAssistantResponse = parsedResponse;

                Log("[StructuredAssistantResponseParser] StructuredAssistantResponse parsing succeeded.");

                return true;
            }
            catch (Exception exception)
            {
                LogWarning("[StructuredAssistantResponseParser] JSON parse exception full: " + exception);
                LogWarning("[StructuredAssistantResponseParser] JSON parse exception type: " + exception.GetType().FullName);
                LogWarning("[StructuredAssistantResponseParser] JSON parse exception message: " + exception.Message);
                LogWarning("[StructuredAssistantResponseParser] JSON parse exception stack: " + exception.StackTrace);
                LogWarning("[StructuredAssistantResponseParser] JSON that failed to deserialize:\n" + cleanedJson);

                return false;
            }
        }

        public string ExtractLikelyJsonObject(string rawResponse)
        {
            if (string.IsNullOrWhiteSpace(rawResponse))
            {
                return null;
            }

            var trimmedResponse = rawResponse.Trim();

            var firstBraceIndex = trimmedResponse.IndexOf('{');
            var lastBraceIndex = trimmedResponse.LastIndexOf('}');

            if (firstBraceIndex >= 0 && lastBraceIndex > firstBraceIndex)
            {
                return trimmedResponse.Substring(firstBraceIndex, lastBraceIndex - firstBraceIndex + 1);
            }

            return null;
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey