// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using DefaultNamespace;
using NaughtyAttributes;
using UnityEngine;
using UnityEngine.Networking;

public class OpenAISpeechToText : MonoBehaviour
{
    [Header("OpenAI")]
    private string _openAIApiKey => Secrets.OpenAIApiKey;
    [SerializeField] private string _transcriptionModelName = "gpt-4o-transcribe";

    [Header("Listening")]
    [SerializeField] private GameObject _isListeningIndicator;
    [SerializeField] private float _preRollSeconds = 0.15f;

    [Header("Debug")]
    [SerializeField] private bool _logVerboseResponse = true;
    [SerializeField] [ReadOnly] private bool _isListening;
    [SerializeField] [ReadOnly] private bool _isTranscriptionInProgress;
    [SerializeField] [ReadOnly] private long _captureStartSampleValueIndex;
    [SerializeField] [ReadOnly] private long _captureEndSampleValueIndex;

    private MicrophoneInputController MicrophoneInputController => GlobalManager.I.MicrophoneInputController;

    [Button("StartListening")]
    public void StartListening()
    {
        if (_isListening)
        {
            Debug.LogWarning("[OpenAISpeechToText] Already listening.");
            return;
        }

        if (_isTranscriptionInProgress)
        {
            Debug.LogWarning("[OpenAISpeechToText] Cannot start listening while transcription is in progress.");
            return;
        }

        if (MicrophoneInputController == null)
        {
            Debug.LogError("[OpenAISpeechToText] MicrophoneInputController reference is missing.");
            return;
        }

        if (!MicrophoneInputController.IsMicrophoneRunning)
        {
            Debug.LogError("[OpenAISpeechToText] MicrophoneInputController is not running.");
            return;
        }

        var preRollSampleValueCount = Mathf.RoundToInt(_preRollSeconds * MicrophoneInputController.RecordingSampleRate * MicrophoneInputController.ChannelCount);
        _captureStartSampleValueIndex = Math.Max(0, MicrophoneInputController.TotalSampleValuesCaptured - preRollSampleValueCount);
        _captureEndSampleValueIndex = _captureStartSampleValueIndex;
        _isListening = true;

        _isListeningIndicator?.SetActive(true);

        Debug.Log("[OpenAISpeechToText] Listening started.");
    }

    public void Update()
    {
        if (_isListening && MicrophoneInputController.CurrentSpeechActivityState == MicrophoneInputController.SpeechActivityState.Inactive)
        {
            StopListeningAndSend();
        }
    }
    
    [Button("StopListeningAndSend")]
    public void StopListeningAndSend()
    {
        if (!_isListening)
        {
            Debug.LogWarning("[OpenAISpeechToText] Not currently listening.");
            return;
        }

        if (MicrophoneInputController == null)
        {
            Debug.LogError("[OpenAISpeechToText] MicrophoneInputController reference is missing.");
            CleanupListeningState();
            return;
        }

        _captureEndSampleValueIndex = MicrophoneInputController.TotalSampleValuesCaptured;
        var trimmedAudioClip = MicrophoneInputController.CreateAudioClipFromRecentSampleValues(
            _captureStartSampleValueIndex,
            _captureEndSampleValueIndex,
            "microphone_recording");

        CleanupListeningState();

        if (trimmedAudioClip == null)
        {
            Debug.LogWarning("[OpenAISpeechToText] No trimmed audio clip was created.");
            return;
        }

        StartCoroutine(TranscribeAudioClipCoroutine(trimmedAudioClip, "microphone_recording.wav"));
    }
    
    private IEnumerator TranscribeAudioClipCoroutine(AudioClip audioClip, string fileName)
    {
        if (_isTranscriptionInProgress)
        {
            Debug.LogWarning("[OpenAISpeechToText] Transcription is already in progress.");
            yield break;
        }

        _isTranscriptionInProgress = true;

        if (string.IsNullOrWhiteSpace(_openAIApiKey))
        {
            Debug.LogError("[OpenAISpeechToText] OpenAI API key is missing.");
            _isTranscriptionInProgress = false;
            yield break;
        }

        if (audioClip == null)
        {
            Debug.LogError("[OpenAISpeechToText] AudioClip is null.");
            _isTranscriptionInProgress = false;
            yield break;
        }

        var wavBytes = ConvertAudioClipToWavBytes(audioClip);

        if (wavBytes == null || wavBytes.Length == 0)
        {
            Debug.LogError("[OpenAISpeechToText] WAV conversion failed.");
            _isTranscriptionInProgress = false;
            yield break;
        }

        var formSections = new List<IMultipartFormSection>();
        formSections.Add(new MultipartFormFileSection("file", wavBytes, fileName, "audio/wav"));
        formSections.Add(new MultipartFormDataSection("model", _transcriptionModelName));

        using (var unityWebRequest = UnityWebRequest.Post("https://api.openai.com/v1/audio/transcriptions", formSections))
        {
            unityWebRequest.SetRequestHeader("Authorization", "Bearer " + _openAIApiKey);

            yield return unityWebRequest.SendWebRequest();

            if (unityWebRequest.result != UnityWebRequest.Result.Success)
            {
                Debug.LogError("[OpenAISpeechToText] Transcription request failed: " + unityWebRequest.error);
                Debug.LogError("[OpenAISpeechToText] Response body: " + unityWebRequest.downloadHandler.text);
                _isTranscriptionInProgress = false;
                yield break;
            }

            var rawResponseText = unityWebRequest.downloadHandler.text;

            if (_logVerboseResponse)
            {
                Debug.Log("[OpenAISpeechToText] Raw transcription response: " + rawResponseText);
            }

            var transcriptionResponse = JsonUtility.FromJson<OpenAITranscriptionResponse>(rawResponseText);

            if (transcriptionResponse == null)
            {
                Debug.LogError("[OpenAISpeechToText] Failed to parse transcription response.");
                _isTranscriptionInProgress = false;
                yield break;
            }
            else
            {
                GlobalManager.I.QueryHandler.HandleNewMessage(transcriptionResponse.text, QuerySource.Microphone);
            }

            Debug.Log("[OpenAISpeechToText] Transcript: " + transcriptionResponse.text);
        }

        _isTranscriptionInProgress = false;
    }

    private byte[] ConvertAudioClipToWavBytes(AudioClip audioClip)
    {
        var sampleCount = audioClip.samples * audioClip.channels;
        var sampleData = new float[sampleCount];
        audioClip.GetData(sampleData, 0);

        var pcm16Bytes = ConvertFloatSamplesToPcm16Bytes(sampleData);

        using (var memoryStream = new MemoryStream())
        using (var binaryWriter = new BinaryWriter(memoryStream))
        {
            var channelCount = audioClip.channels;
            var sampleRate = audioClip.frequency;
            var bitsPerSample = 16;
            var byteRate = sampleRate * channelCount * bitsPerSample / 8;
            var blockAlign = channelCount * bitsPerSample / 8;
            var subChunkTwoSize = pcm16Bytes.Length;
            var chunkSize = 36 + subChunkTwoSize;

            binaryWriter.Write(new[] { 'R', 'I', 'F', 'F' });
            binaryWriter.Write(chunkSize);
            binaryWriter.Write(new[] { 'W', 'A', 'V', 'E' });

            binaryWriter.Write(new[] { 'f', 'm', 't', ' ' });
            binaryWriter.Write(16);
            binaryWriter.Write((short)1);
            binaryWriter.Write((short)channelCount);
            binaryWriter.Write(sampleRate);
            binaryWriter.Write(byteRate);
            binaryWriter.Write((short)blockAlign);
            binaryWriter.Write((short)bitsPerSample);

            binaryWriter.Write(new[] { 'd', 'a', 't', 'a' });
            binaryWriter.Write(subChunkTwoSize);
            binaryWriter.Write(pcm16Bytes);

            binaryWriter.Flush();
            return memoryStream.ToArray();
        }
    }

    private byte[] ConvertFloatSamplesToPcm16Bytes(float[] sampleData)
    {
        var pcm16Bytes = new byte[sampleData.Length * 2];
        var pcm16ByteIndex = 0;

        for (var sampleIndex = 0; sampleIndex < sampleData.Length; sampleIndex++)
        {
            var clampedSample = Mathf.Clamp(sampleData[sampleIndex], -1.0f, 1.0f);
            var pcm16Sample = (short)(clampedSample * short.MaxValue);

            var sampleBytes = BitConverter.GetBytes(pcm16Sample);
            pcm16Bytes[pcm16ByteIndex] = sampleBytes[0];
            pcm16Bytes[pcm16ByteIndex + 1] = sampleBytes[1];
            pcm16ByteIndex += 2;
        }

        return pcm16Bytes;
    }

    private void CleanupListeningState()
    {
        _isListening = false;
        _captureStartSampleValueIndex = 0;
        _captureEndSampleValueIndex = 0;
        _isListeningIndicator?.SetActive(false);
    }

    [Serializable]
    private class OpenAITranscriptionResponse
    {
        public string text;
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey