// Generated by ChatGPT and Riko Balakit/Pearl Grey

using System;
using System.Collections;
using System.Collections.Concurrent;
using System.IO;
using System.Net.Sockets;
using System.Threading;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Events;

namespace Inputs.SpeechToText
{
    public class WakeWordSidecarClient : MonoBehaviour
    {
        [SerializeField] private string _host = "127.0.0.1";
        [SerializeField] private int _port = 17777;
        [SerializeField] private bool _connectOnStart = true;
        [SerializeField] private GameObject _wakeWordDebugIndicator;
    
        private TcpClient _tcpClient;
        private Thread _readerThread;
        private volatile bool _isRunning;
        private readonly ConcurrentQueue<Action> _mainThreadActions = new ConcurrentQueue<Action>();
    
        [SerializeField]
        public UnityEvent OnWakeWordTriggeredEvent;

        private Coroutine _currentWakeWordDebugIndicatorCoroutine;

        [Serializable]
        private class WakeWordSidecarMessage
        {
            public string type;
            public double timestampUnixSeconds;
        }

        private void Start()
        {
            if (_connectOnStart)
            {
                ConnectToWakeWordSidecar();
            }
        }

        private void Update()
        {
            while (_mainThreadActions.TryDequeue(out var action))
            {
                action?.Invoke();
            }
        }

        private void OnDestroy()
        {
            DisconnectFromWakeWordSidecar();
        }

        public void ConnectToWakeWordSidecar()
        {
            if (_isRunning)
            {
                Debug.LogWarning("[WakeWordSidecarClient] Already connected or connecting.");
                return;
            }

            _isRunning = true;
            _readerThread = new Thread(ReaderThreadLoop);
            _readerThread.IsBackground = true;
            _readerThread.Start();
        }

        public void DisconnectFromWakeWordSidecar()
        {
            _isRunning = false;

            try
            {
                _tcpClient?.Close();
            }
            catch (Exception exception)
            {
                Debug.LogWarning("[WakeWordSidecarClient] Error while closing TCP client: " + exception.Message);
            }

            _tcpClient = null;

            if (_readerThread != null && _readerThread.IsAlive)
            {
                _readerThread.Join(500);
            }

            _readerThread = null;
        }

        private void ReaderThreadLoop()
        {
            while (_isRunning)
            {
                try
                {
                    Debug.Log("[WakeWordSidecarClient] Connecting to wake word sidecar...");
                    _tcpClient = new TcpClient();
                    _tcpClient.NoDelay = true;
                    _tcpClient.Connect(_host, _port);

                    Debug.Log("[WakeWordSidecarClient] Connected to wake word sidecar.");

                    using var networkStream = _tcpClient.GetStream();
                    using var streamReader = new StreamReader(networkStream);

                    while (_isRunning && _tcpClient.Connected)
                    {
                        var line = streamReader.ReadLine();

                        if (string.IsNullOrWhiteSpace(line))
                        {
                            continue;
                        }

                        HandleIncomingMessage(line);
                    }
                }
                catch (Exception exception)
                {
                    Debug.LogWarning("[WakeWordSidecarClient] Connection error: " + exception.Message);
                }

                if (_isRunning)
                {
                    Thread.Sleep(1000);
                }
            }
        }

        private void HandleIncomingMessage(string rawMessage)
        {
            WakeWordSidecarMessage sidecarMessage = null;

            try
            {
                sidecarMessage = JsonConvert.DeserializeObject<WakeWordSidecarMessage>(rawMessage);
            }
            catch (Exception exception)
            {
                Debug.LogWarning("[WakeWordSidecarClient] Failed to parse message: " + rawMessage + " Exception: " + exception.Message);
                return;
            }

            if (sidecarMessage == null)
            {
                Debug.LogWarning("[WakeWordSidecarClient] Parsed null message.");
                return;
            }

            if (sidecarMessage.type == "wake_word_detected")
            {
                _mainThreadActions.Enqueue(() =>
                {
                    Debug.Log("[WakeWordSidecarClient] Wake word detected from sidecar at unix time: " + sidecarMessage.timestampUnixSeconds);

                    OnWakeWordTriggered();
                });
            }
            else
            {
                Debug.Log("[WakeWordSidecarClient] Unknown sidecar message type: " + sidecarMessage.type);
            }
        }

        [NaughtyAttributes.Button]
        private void WakeWordTestTrigger()
        {
            OnWakeWordTriggered();
        }
        public void OnWakeWordTriggered()
        {
            GlobalManager.I.MicrophoneInputController.SetSpeechActivityStateToActive();
            OnWakeWordTriggeredEvent?.Invoke();
            if(_currentWakeWordDebugIndicatorCoroutine != null)
            {
                StopCoroutine(_currentWakeWordDebugIndicatorCoroutine);
            }
            _currentWakeWordDebugIndicatorCoroutine = StartCoroutine(ShowWakeWordDebugIndicatorCoroutine());
        }

        private IEnumerator ShowWakeWordDebugIndicatorCoroutine()
        {
            _wakeWordDebugIndicator.SetActive(true);
            yield return new WaitForSeconds(3f);
            _wakeWordDebugIndicator.SetActive(false);
        }
    }
}

// Generated by ChatGPT and Riko Balakit/Pearl Grey