// Generated by ChatGPT and Riko Balakit / Pearl Grey

using System.Collections;
using System.Security;
using System.Text;
using UnityEngine;
using UnityEngine.Networking;
namespace Runtime.TextToSpeech
{
    public class AzureTtsUnityPlayer : BaseTtsUnityPlayer
    {

        private string _azureRegion => GlobalManager.I.Configuration.AzureTtsRegion;


        private string _voiceName => GlobalManager.I.Configuration.AzureTtsVoiceName;

        protected override IEnumerator GenerateAudioClipCoroutine(
            string textToSpeak,
            System.Action<AudioClip> onSuccess)
        {
            var url = $"https://{_azureRegion}.tts.speech.microsoft.com/cognitiveservices/v1";

            var ssml = BuildSsml(textToSpeak);
            var ssmlBytes = Encoding.UTF8.GetBytes(ssml);

            using var request = new UnityWebRequest(url, UnityWebRequest.kHttpVerbPOST);
            request.uploadHandler = new UploadHandlerRaw(ssmlBytes);
            request.downloadHandler = new DownloadHandlerAudioClip(url, AudioType.MPEG);

            request.SetRequestHeader("Ocp-Apim-Subscription-Key", Secrets.AZURE_TTS_API_KEY);
            request.SetRequestHeader("Content-Type", "application/ssml+xml");
            request.SetRequestHeader("X-Microsoft-OutputFormat", "audio-24khz-48kbitrate-mono-mp3");
            request.SetRequestHeader("User-Agent", "RitsukoUnity");

            yield return request.SendWebRequest();

            if (request.result != UnityWebRequest.Result.Success)
            {
                LogError($"Azure TTS Error: {request.error}");
                yield break;
            }

            var audioClip = DownloadHandlerAudioClip.GetContent(request);

            if (audioClip == null)
            {
                LogError("Azure TTS Error: Downloaded AudioClip was null.");
                yield break;
            }

            onSuccess?.Invoke(audioClip);
        }

        private string BuildSsml(string textToSpeak)
        {
            var escapedTextToSpeak = SecurityElement.Escape(textToSpeak);

            return
                $@"<speak version=""1.0"" xml:lang=""en-US""
xmlns=""http://www.w3.org/2001/10/synthesis""
xmlns:mstts=""http://www.w3.org/2001/mstts"">
  <voice name=""{_voiceName}"">
    {escapedTextToSpeak}
  </voice>
</speak>";
        }
    }
}

// Generated by ChatGPT and Riko Balakit / Pearl Grey