// Generated by ChatGPT and Riko Balakit / Pearl Grey

using System.Collections;
using NaughtyAttributes;
using UnityEngine;
namespace Runtime.TextToSpeech
{
    public abstract class BaseTtsUnityPlayer : PearlBehaviour
    {
        private string _textToSpeak = "";

        private Coroutine _speakCoroutine;
        private AudioClip _currentAudioClip;

        public bool IsSpeaking => _speakCoroutine != null;
        
        public AudioClip CurrentAudioClip => _currentAudioClip;

        [Button("Generate and Play")]
        private void GenerateAndPlayFromInspector()
        {
            GenerateAndPlay(_textToSpeak);
        }

        private void Start()
        {
            SetInitialized();
        }

        public void GenerateAndPlay(string textToSpeak)
        {
            if (_speakCoroutine != null)
            {
                StopSpeaking();
            }

            _speakCoroutine = StartCoroutine(GenerateAndPlayCoroutine(textToSpeak));
        }

        public void StopSpeaking()
        {
            if (_speakCoroutine != null)
            {
                StopCoroutine(_speakCoroutine);
                _speakCoroutine = null;
            }

            
            GlobalManager.I.AvatarController.AudioSource?.Stop();
            
        }

        public void SetTextToSpeakInstantly(string textToSpeak)
        {
            _textToSpeak = textToSpeak;
        }

        public void SetAudioClipInstantly(AudioClip audioClip, bool stopPlayback = true)
        {
            _currentAudioClip = audioClip;

            if (stopPlayback == true)
            {
                GlobalManager.I.AvatarController.AudioSource.Stop();
            }

            GlobalManager.I.AvatarController.AudioSource.clip = audioClip;
        }

        protected virtual void OnDestroy()
        {
            StopSpeaking();
        }

        private IEnumerator GenerateAndPlayCoroutine(string textToSpeak)
        {
            yield return GenerateAudioClipCoroutine(
                textToSpeak,
                onSuccess: generatedAudioClip =>
                {
                    _currentAudioClip = generatedAudioClip;

                    GlobalManager.I.AvatarController.AudioSource.loop = false;
                    GlobalManager.I.AvatarController.AudioSource.clip = generatedAudioClip;
                    GlobalManager.I.AvatarController.AudioSource.Play();
                });

            if (GlobalManager.I.AvatarController.AudioSource.clip != null && GlobalManager.I.AvatarController.AudioSource.isPlaying == true)
            {
                while (GlobalManager.I.AvatarController.AudioSource.isPlaying == true)
                {
                    yield return null;
                }
            }


            float PERIOD_TO_WAIT_BEFORE_LISTENING_FOR_RESPONSE_SECONDS = 0.5f;
            yield return new WaitForSeconds(PERIOD_TO_WAIT_BEFORE_LISTENING_FOR_RESPONSE_SECONDS);

            _speakCoroutine = null;
        }

        protected abstract IEnumerator GenerateAudioClipCoroutine(
            string textToSpeak,
            System.Action<AudioClip> onSuccess);
    }
}

// Generated by ChatGPT and Riko Balakit / Pearl Grey