// Generated by ChatGPT and Riko Balakit / Pearl Grey

using System;
using System.Collections;
using System.Text;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Networking;
namespace Runtime.TextToSpeech
{
    public class ElevenLabsTtsUnityPlayer : BaseTtsUnityPlayer
    {
        protected override IEnumerator GenerateAudioClipCoroutine(
            string textToSpeak,
            Action<AudioClip> onSuccess)
        {
            var url = $"https://api.elevenlabs.io/v1/text-to-speech/{GlobalManager.I.Configuration.ElevenLabsTtsVoiceId}/stream";

            var payload = new ElevenLabsRequest
            {
                text = textToSpeak,
                model_id = GlobalManager.I.Configuration.ElevenLabsTtsModelId
            };

            var json = JsonConvert.SerializeObject(payload);
            var jsonBytes = Encoding.UTF8.GetBytes(json);

            using var request = new UnityWebRequest(url, UnityWebRequest.kHttpVerbPOST);

            request.uploadHandler = new UploadHandlerRaw(jsonBytes);
            request.downloadHandler = new DownloadHandlerAudioClip(url, AudioType.MPEG);

            request.SetRequestHeader("Content-Type", "application/json");
            request.SetRequestHeader("xi-api-key", Secrets.ELEVENLABS_API_KEY);

            yield return request.SendWebRequest();

            if (request.result != UnityWebRequest.Result.Success)
            {
                LogError($"ElevenLabs TTS Error: {request.error}");
                onSuccess?.Invoke(null);
                yield break;
            }

            var clip = DownloadHandlerAudioClip.GetContent(request);

            if (clip == null)
            {
                LogError("ElevenLabs returned null AudioClip.");
                onSuccess?.Invoke(null);
                yield break;
            }

            onSuccess?.Invoke(clip);
        }

        private class ElevenLabsRequest
        {
            public string text;
            public string model_id;
        }
    }
}

// Generated by ChatGPT and Riko Balakit / Pearl Grey